### ISSUE TITLE
Unable to resolve type for Startup class ctor in Cli

### ISSUE THREAD

**Issue by christophwille** [domaindrivendev/Swashbuckle.AspNetCore#1007]
Version 4.0.1 of the Cli

Unhandled Exception: System.InvalidOperationException: Unable to resolve service for type 'MyProject.IStartupService' while attempting to activate 'MyProject.Startup'.

We have a Program.cs that uses 

            return WebHost.CreateDefaultBuilder(args)
                .ConfigureServices(s =>
                {
                    s.AddTransient<IStartupService, StartupService>();
                })
                .UseApplicationInsights()
                .UseStartup<TStartup>();

And a corresponding Startup(.cs) that has a constructor expecting this IStartupService:

    public class Startup
    {
        public Startup(IStartupService env) : base(env)
        {
        }

When running dotnet swagger... the above mentioned exception is thrown.

**Comment by christophwille** [comment]
I have created a super-simple with the Cli installed, so simply build to repro the error.

[SwaggerDocGenWDep.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/2759419/SwaggerDocGenWDep.zip)

**Comment by domaindrivendev** [comment]
So, a lot has changed since this issue was created, and if you still have this issue I would recommend wiring up the CLI stuff from scratch using the docs here:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#swashbuckleaspnetcorecli

Also, because you're registering additional services in your `Program.cs` file as opposed to your `Startup.cs` file, you'll also need to use a custom host factory for the CLI tool to ensure it runs with the same host configuration as your actual app:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore#use-the-cli-tool-with-a-custom-host-configuration

I just pulled down your repro app, followed the above steps and the CLI tool worked without issue.
