### ISSUE TITLE
Custom Index Sample App - Enhancements Needed

### ISSUE THREAD

**Issue by bmbell** [domaindrivendev/Swashbuckle.AspNetCore#1008]
Hi,

The custom index sample application seems to really only give a very trivial example of removing the info section of the rendered output: (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/CustomUIIndex/Swagger/index.html)

Additionally, this example links to some reference documentation that doesn't give a lot of help with how to make some changes to the swagger-ui-specific output.  Upon some web searches, I found this to provide some additional information on plug-ins:

https://swagger.io/docs/open-source-tools/swagger-ui/customization/plugin-api/

In the documentation, it gives an example of how to wrap a component:

```
const MyWrapBuiltinComponentPlugin = function(system) {
  return {
    wrapComponents: {
      info: (Original, system) => (props) => {
        return <div>
          <h3>Hello world! I am above the Info component.</h3>
          <Original {...props} />
        </div>
      }
    }
  }
}
```

I can see how this fits in with the custom index.html file that we can specify within Swashbuckle.  However, I am not sure how to return tags in Javascript because it will just return an error: "Uncaught SyntaxError: Unexpected token <".   

Therefore, I would love to see a sample application that shows inserting content around the info component using the plug-in sytem.  Or some suggestions on how to do this.  This would seem like it would be a typical use-case for those that want a custom index.html file.  Thanks!

**Comment by domaindrivendev** [comment]
This is a UI concern and therefore, as per the [issue guidelines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/ISSUE_TEMPLATE.md), should be posted to the [swagger-ui project](https://github.com/swagger-api/swagger-ui) instead of here. The swagger-ui tool is bundled with Swashbuckle for convenience, but it's developed independently and therefore, it's maintainers would be best placed to assist with complex customization use-cases.

If you do find something and want to submit a PR, I'd be happy to add it to the example here.
