### ISSUE TITLE
How can I load header upfront when launched Swagger?

### ISSUE THREAD

**Issue by jaydeept** [domaindrivendev/Swashbuckle.AspNetCore#1009]
I have created a .Net Core 2.2 web project where I have implemented micro-services and I'm using swagger there. I got some headers like DB provider and DB connection string where I am populating default values using` SwaggerGenOptions OperationFilter()`.

Now, I have written a small JavaScript function to change the connection string based on the DB provider in the swagger page so if someone selects another DB provider the connection string should also get changed which is coming from a custom JavaScript file. I am injecting this JavaScript file using `SwaggerUIOptions:InjectJavascript()`.

The problem with this approach is when I ask for attribute value after launching swagger page, it doesn't populate anything. I actually need to expand the operation and need to click on the "Try Out" button to let the value get populated. Seems that when we launch the swagger, the page isn't getting loaded fully but as we expand and click on the "Try-Out", it includes other JavaScript files to load required attributes. Is there any way to load page fully or at-least inject my JavaScript at the end?

Currently, I need to check every time whether the onClick event happened and if the `event.target.className` is matching with the "Try Out" button then only invoke my custom logic but that involves performance degradation.

**Comment by domaindrivendev** [comment]
As per the [issue guidelines](ISSUE_TEMPLATE.md), this is a UI concern and should be posted to the swagger-ui project (https://github.com/swagger-api/swagger-ui) instead of Swashbuckle.

Given the amount of customization that you're doing, I would recommend providing a custom swagger-ui `index.html`, where you have full control of the JavaScript DOM, as described [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#customize-indexhtml)
