### ISSUE TITLE
Using Swagger with [Consumes]

### ISSUE THREAD

**Issue by dkonyayev** [domaindrivendev/Swashbuckle.AspNetCore#1040]
Using syntax below with [Consumes] I get Swagger generation error due to overloaded POST verb. What is my workaround for this case?

[HttpPost]
[Consumes("application/json")]
public async Task<ActionResult> PostObject([FromBody] object value)
{
}

[HttpPost]
[Consumes("multipart/form-data")]
public async Task<ActionResult> PostBinary(byte[] file)
{
}

**Comment by domaindrivendev** [comment]
Due to the internal implementation of the Swagger generator (it assumes a 1:1 relationship between action method and `OpenAPI Operation`), this scenario is not well supported out of the box.

However I can offer a couple of workarounds:

1) The simplest thing to do would be to just pick one of the operations (e.g. the one you expect to be used more frequently) and _only_ document that one. This can be done with the following config setting

```csharp
service.AddSwaggerGen(c =>
{
  …
    c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());
    // Use First or Last depending on your choice.
}
```

2) If you _really_ need to document both versions of the op, you can use the above configuration to keep the JSON version and then enrich the corresponding Operation description with an Operation filter:

```csharp
service.AddSwaggerGen(c =>
{
  …
    c.ResolveConflictingActions(apiDescriptions => apiDescriptions.First());

    c.OperationFilter<FormDataOperationFilter>()
}

// FormDataOperationFilter.cs
publicclass FormDataOperationFilter : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        // Identify relevant operations by convention - e.g. action
        if (!context.MethodInfo.Name == "PostObject") return;

        operation.RequestBody.Content.Add("multipart/form-data", new OpenApiMediaType
        {
            Schema = new OpenApiSchema
            {
                Type = "object",
                Properties = new Dictionary<string, OpenApiSchema>
                {
                    ["file"] = new OpenApiSchema { Type = "string", Format = "binary" }
                }
            }
        });
    }
}
```

A little hacky but it works!
