### ISSUE TITLE
5.0.0-preview ProducesResponseTypeAttribute with void type produces type ProblemDetails

### ISSUE THREAD

**Issue by kingmotley** [domaindrivendev/Swashbuckle.AspNetCore#1043]
Thanks for contributing to Swashbuckle.AspNetCore! As per the [contributing guidelines](CONTRIBUTING.md), please adhere to the following rules of thumb before submitting your issue:

1. If it's not a bug report, feature request or PR, don't submit it here. Post to Stackoverflow instead.
2. If your issue is specifically a UI concern, don't submit it here. Post to the [swagger-ui repo](https://github.com/swagger-api/swagger-ui).
3. For bug reports, specify the version your using and provide clear repro steps.

**Comment by kingmotley** [comment]
[ProducesResponseType(typeof(void),(int)HttpStatusCode.NotAcceptable)]
is producing a response type of ProblemDetails, where it should be returning a response type of void.

[ProducesResponseType((int)HttpStatusCode.NotAcceptable)] is doing the same thing unsurprisingly since it is the equivalent to the above.

**Comment by domaindrivendev** [comment]
Swashbuckle relies on the low-level API Description abstractions surfaced by the ASP.NET Core framework to generate corresponding Swagger/OAI Operations. I've been able to repro your issue in ASP.NET Core 2.2 and can confirm that the framework itself is surfacing the wrong information here.

That is, the corresponding `ApiResponseType.Type` is set to `ProblemDetails` instead of null.

Could you please post an issue to the following repo?
https://github.com/aspnet/AspNetCore/issues

**Comment by ratzvasky** [comment]
As a workaround, you can also disable the default mapping to a ProblemDetails when an error occurred. 

https://stackoverflow.com/questions/56341749/hide-swagger-bad-response-example-model-in-net-core-2-2

**Comment by martincostello** [comment]
Closing as external.

**Comment by randyburden** [comment]
Workaround: Add this to your startup code:

```csharp
builder.Services.AddControllers()
	.ConfigureApiBehaviorOptions(options =>
	{
		options.SuppressMapClientErrors = true;
	});
```
