### ISSUE TITLE
SchemaFilter set Description is overwritten by XML comment

### ISSUE THREAD

**Issue by sandersaares** [domaindrivendev/Swashbuckle.AspNetCore#1073]
I have a SchemaFilter that sets schema.Description. The idea is to append some text to the description. However, I find that the filter runs before the XML documentation text is added. The XML documentation text therefore overwrites what my filter adds.

I would expect schema filters to run after the XML documentation has been incorporated, not before, so I can actually post-process the final schema objects.

**Comment by domaindrivendev** [comment]
As it happens, the enrichment from XML comments is actually implemented as a set of filters itself. If you look under the hood of `IncludeXmlComments` you'll see that it's simply wiring up a couple of built-in filters. Because filters run in the order they're added, you should be able to achieve what you want by just invoking the call to `IncludeXmlComments` _before_ you add your filters. Not immediately obvious to be fair!

**Comment by sandersaares** [comment]
I see. Yeah, that makes sense. I wonder if it is possible to make it more obvious somehow? Maybe a name like `IncludeXmlCommentsFilter()` might be more explicit about its nature?

**Comment by domaindrivendev** [comment]
That would make sense but would be a breaking change to introduce at this point. Perhaps I'll introduce this in a later version.
