### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by daliri72** [domaindrivendev/Swashbuckle.AspNetCore#1081]
I use it but when project running show this error

```
Errors 
Parser error on line 15
end of the stream or a document separator is expected

```
What's wrong?

**Comment by domaindrivendev** [comment]
Please provide and _exact_ set of repro steps.

**Comment by Adskoy** [comment]
I was able to reproduce it somehow (rc3 with netcore preview 3)
![Annotation 2019-03-28 121923](https://user-images.githubusercontent.com/46523393/55137837-d76ea980-5153-11e9-8c34-602d2f581f99.png)
This problem began to occur after publishing app to Azure App Service or runnig it locally with IIS instead of Kestrel (which is working ok). 
Locally with IIS when I try to access swagger.json I recieve
`GET https://localhost:44314/swagger/v1/swagger.json net::ERR_SPDY_PROTOCOL_ERROR 200`
and when I try to get swagger.json from app published to Azure i recieve full swagger json with no opening bracket:
`
  "openapi": "3.0.1",
  "info": {
    "title": "My API - V1",
    "version": "v1"
  }}
`
One of the options to get it running on published app is to remove these publishing params from project file:
`    <AspNetCoreHostingModel>OutOfProcess</AspNetCoreHostingModel>
    <AspNetCoreModuleName>AspNetCoreModuleV2</AspNetCoreModuleName>`

Honestly, that's really strange.

**Comment by domaindrivendev** [comment]
Looks like a dup of #1121.
