### ISSUE TITLE
Authorize dialog's are all wrong / non functional.

### ISSUE THREAD

**Issue by SledgeHammer01** [domaindrivendev/Swashbuckle.AspNetCore#1097]
Enabling the authorize dialog through:

				options.AddSecurityDefinition("Bearer", new OAuth2Scheme
				{
					Flow = "xxx",
					TokenUrl = "/token"
				});

All flows are incorrect / broken:

password - should only show username and password, not clientid & clientsecret those are part of the client_credentials flow... you are sending clientid & secret with a password grant which is wrong.

application - not sure what this is supposed to be, but clientid and secret only are shown, but the authorize button just results in a bad request error since you aren't picking up the values from the text boxes.

**Comment by domaindrivendev** [comment]
These sound like gripes with the UI itself rather than the Swagger generation and therefore, as per the issue guidelines, should be submitted to the [swagger-ui](https://github.com/swagger-api/swagger-ui) project instead of Swashbuckle.

Also - this is _free_ open source software and so I'd suggest softening the tone a little if you actually want the maintainers to help you.
