### ISSUE TITLE
Try It Out results in confusing / out of sync UI / non functional

### ISSUE THREAD

**Issue by SledgeHammer01** [domaindrivendev/Swashbuckle.AspNetCore#1098]
Clicking the Try It Now button on a method results in a bunch of weird behavior:

1) You get 2 cancel buttons
2) Neither cancel button undoes what you just typed
3) Clicking the top cancel button cancels correctly and exits edit mode, but clicking the bottom button just exits edit mode, but still leaves the method in try it now mode, so the top cancel button is not reset
4) This results in no way to get back to the original example

**Comment by domaindrivendev** [comment]
These sound like gripes with the UI itself rather than the Swagger generation and therefore, as per the issue guidelines, should be submitted to the [swagger-ui](https://github.com/swagger-api/swagger-ui) project instead of Swashbuckle.

Also - this is _free_ open source software and so I'd suggest softening the tone a little if you actually want the maintainers to help you.
