### ISSUE TITLE
Support for catch-all parameter syntax

### ISSUE THREAD

**Issue by oakio** [domaindrivendev/Swashbuckle.AspNetCore#1100]
Swagger not supported catch-all parameter in route `/foo/{**bar}`.

When sending a request via SwaggerUI, parameter `bar` will be escaped. In this case, all `'/'` will be replaced with `%2F`.

Steps to reproduce:
1. Open Swagger UI
2. Set parameter `bar` with value "abc/def"
3. Send request.
```
[Route("foo/{**bar}")]
public Baz Get(string bar) { }
```
Expected: `bar` equal to "abc/def"
Actual: `bar` equal to ''abc%2Fdef

Swashbuckle.AspNetCore 4.0.1

**Comment by superkartoffel** [comment]
I can report that this is an issue for me too.
But I'm not sure you can fix this, since the OpenAPI spec only allows unencoded reserved characters in query parameters and not url paramters. See [spec on Parameter.allowReserved](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.0.md)
Also swagger-UI has disabled it some time ago. See [PR 1331](https://github.com/swagger-api/swagger-js/pull/1331)

**Comment by krispenner** [comment]
While the OpenAPI spec may not allow for it, it is still quiet convenient since API gateways such as Azure API Management will allow/use it so that unencoded reserved characters can be used in a `path` parameter.

If you would like to enable this, here is an operation filter I wrote to override Swashbuckle's stripping of the asterisks by adding it back in.

```cs
public class FixCatchAllPathOperations : IOperationFilter
{
    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        var template = context?.ApiDescription?.ActionDescriptor?.AttributeRouteInfo?.Template;

        if (operation == null || template == null)
        {
            return;
        }

        var match = Regex.Match(template, @"{\*\*?([a-zA-Z0-9]+)}", RegexOptions.Compiled);

        if (match.Success)
        {
            var name = match.Groups[1].Value;
            context.ApiDescription.RelativePath = context.ApiDescription.RelativePath.Replace($"{{{name}}}", $"{{*{name}}}");

            // Optionally, ensure there is a matching parameter for good measure.
            operation.Parameters.Single(p => p.Name == name);
        }
    }
}
```
