### ISSUE TITLE
Global ConsumesAttribute filter doesn't populate consumes property properly

### ISSUE THREAD

**Issue by blakeholl** [domaindrivendev/Swashbuckle.AspNetCore#1130]
I can add a global filter for Produces attribute, and all controller actions are correctly populated with the desired produces values.  However, when I attempt to do the same for Consumes attribute, no controller actions are populated with the desired consumes values.

`services.AddMvc(options =>
            {
                options.Filters.Add(new ConsumesAttribute("application/json"));
                options.Filters.Add(new ProducesAttribute("application/json"));
            });`

Will produce swagger.json as follows:

` "consumes": [
          "application/json-patch+json",
          "application/json",
          "application/*+json"
        ],
        "produces": [
          "application/json"
        ],`

If I directly apply the `[Consumes("application/json")]` attribute to the controller or action the following swagger.json is output:
`"consumes": [
          "application/json"
        ],
        "produces": [
          "application/json"
        ],`

**Comment by vaishnavkishan** [comment]
I am using .net core 3.1 and Swashbuckle 5.3.3 and it is still not working correctly.

**Comment by domaindrivendev** [comment]
There's a few things going here and what you're observing is more to do with the way in which ASP.NET Core handles the `ConsumesAttribute` under-the-hood than Swahbuckle itself. Specifically, the attribute does not give you the level of control over supported media types that you might expect it to.

I'll elaborate on this in a moment but first I wanted to direct you to the [following comment in a separate issue](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1296#issuecomment-577831898). This describes the best approach that I'm aware of at present to fine tune the input and output media types that your API will support, and if you use this approach the generated docs will honor this 100%.

However, to elaborate further on what's going on with the `ConsumesAttribute`, it's worth noting that your application of the attribute _is in fact_ altering the supported request media types, just not at the level of granularity you're expecting. To demonstrate this, try the following and you'll see a different set of values:

```csharp
c.Filters.Add(new ConsumesAttribute("text/json"));
```

Under-the-hood, ASP.NET Core keeps track of this and other metadata for every API operation that's exposed by your app and surfaces it as a collection of `ApiDescription` instances. Swashbuckle depends heavily on this data to generate corresponding operation descriptions in the Swagger/OpenAPI format. One of the properties exposed and used by Swashbuckle is the `ApiDescription.SupportedRequestFormats` property and for some reason, when you apply the `ConsumesAttribute` with a media type of `application/json`, globally OR at the controller/action level, ASP.NET Core populates that property with _multiple_ values that appear to be variations of that `application/json` media type.

Therefore, Swashbuckle will (by design) output a `consumes` entry for each one because they're the request media types that ASP.NET Core is telling Swashbuckle are supported by the application.

**Comment by Thieund** [comment]
Please try to remove this formatter: `o.InputFormatters.RemoveType<NewtonsoftJsonPatchInputFormatter>();`
