### ISSUE TITLE
bug in API testing for WEB API with optional parameters

### ISSUE THREAD

**Issue by SteveStrong** [domaindrivendev/Swashbuckle.AspNetCore#118]
[HttpGet("{datasetName?}")]
public string Get(string datasetName) {
}

If you mark a WebAPI using the syntax above  the ? to define the datasetName as optional in the swagger ui,   No matter what you type in the text field  the value always returns as {datasetName}

There is no way to specify another value in the swagger test UI

**Comment by Deilan** [comment]
I also confirm that.

**Comment by chaitanyagurrapu** [comment]
+1. This makes it very annoying to use when we have lots of controllers with optional parameters

**Comment by domaindrivendev** [comment]
This is a [Swagger](http://swagger.io/specification/) limitation. It uses the path (including path parameters) to uniquely identify an Operation and so you can't create optional parameters in the "path". It wants you to treat these as separate operations - one with the parameter and one without.

**Comment by chaitanyagurrapu** [comment]
But surely we can automatically generate the two different end points in the swagger json? 

So if I have a method in the Accounts controller like so ..
```csharp
    [HttpGet("{id?}")] 
    public async Task<IEnumerable<Account>> GetAccount(int? id)
    {
    ...

```
It generates a swagger Json that looks like this ...

    paths: {
        /api/Accounts: {
            get: {
                tags: [
                "Accounts"
                ],
                operationId: "ApiAccountsGet",
            }
        }
    },
    ...
        /api/Accounts/{id}: {
            get: {
                tags: [
                "Accounts"
                ],
                operationId: "ApiAccountsByIdGet",
    ...

Which was clearly my intention with the optional id parameter all along. Why force me to split it into 

```csharp
    [HttpGet("{id}")] 
    public async Task<IEnumerable<Account>> GetAccount(int id)
    {
    ...
    }
    [HttpGet] 
    public async Task<IEnumerable<Account>> GetAccount()
    {
    ...
```
to generate the required json? It is just more boiler plate code that requires me to give up a feature provided by the framework.

The swagger format itself might not support optional parameters, but it doesn't need to. It is just an intermediate format like IL or Java byte code or Assembly. Surely we shouldn't be giving up high level features because it is not supported directly by a single "Assembly Instruction" so to speak. If we can interpret the intent of high level code, we can generate whatever low level code we need to implement that intention. And all of this will still maintain interoperability.

**Comment by domaindrivendev** [comment]
Well, it's all a matter of preference. What you call "boiler plate" I would call good "separation of concerns". I would much prefer the separation because they're two different resources which represent two different use-cases - retrieving a specific account and retrieving a list of accounts.

But that's my own subjective view and you're correct SB could implement some smarts to generate separate Swagger Operations. However, this would increase the complexity within SB because it leverages AspNet Core's built-in metadata layer - ApiExplorer, transforming it's ApiDescriptions, which are per action, into Swagger Operations.

Also, the time I spend on this project is limited, particularly as it doesn't pay any bills, and there's other issues I want to get to first. But, if you'd like to tackle this with a PR that would be awesome!

**Comment by domaindrivendev** [comment]
Re-opening so we can continue tracking it

**Comment by chaitanyagurrapu** [comment]
Thanks @domaindrivendev . I will try and have a look, as long as there are no objections or things that I might have missed or misunderstood.

**Comment by domaindrivendev** [comment]
I'm going to close this one as there's been no follow-up and I have no problem with the current functionality. In fact, I would encourage against overloading actions with optional parameters.

**Comment by jnal** [comment]
I also think letting SB generate different endpoints will be helpful given that this is being offered by the .net framework itself. Is there a way I can do a workaround to override this implementation?
