### ISSUE TITLE
No RequestBody description is generated (5.0.0-rc2)

### ISSUE THREAD

**Issue by cjkrome** [domaindrivendev/Swashbuckle.AspNetCore#1203]
Example of controller action:

```
/// <summary>Some summary</summary>
/// <param name="param1">Some description for the parameter.</param>
/// <returns>Okay</returns>
[HttpPost]
public async Task<IActionResult> Post([FromBody] SomeObject param1)
{
    return Ok();
}
```

Expected generated JSON:

```
...
"paths": {
  "/api/v1/test": {
    "post": {
      "summary": "Some summary",
      "requestBody": {
        "description": "Some description for the parameter.",
        "content": {
          ....
        }
  ....
```

Actual JSON:
```
...
"paths": {
  "/api/v1/test": {
    "post": {
      "summary": "Some summary",
      "requestBody": {
        "content": {
          ....
        }
  ....
```

**Comment by lcarrere** [comment]
Hello there,

We have encountered the same issue. More critical for us is also the lack of [Required] annotation handling in such case: IE:

[HttpPost]
public async Task<IActionResult> Post([FromBody] [Required] SomeObject param1)
{
    return Ok();
}

I don't know it it should be considered as a bug of Swashbuckle or an OpenAPI 3 standard consequence so it would be great to have a feedback to act accordingly. Maybe this can be workaround-ed by using an operation filter?

Thanks for any hint,

Loïc Carrère

**Comment by domaindrivendev** [comment]
@cjkrome - your request is a legitimate feature request but not something I can prioritize right now as I'm working hard to get the official 5.0.0 release (which includes NetCore 3.0 compatibility & OA3 support) shipped. I'm adding to the backlog for now.

@israellot - yours is a separate problem and therefore I'd ask for you to post as a separate issue so I can track it more effectively. With that said, I also beleive it may a non-issue if you pull down the latest code available on [myget.org as a preview package](I can't repro this on the latest code. There's no official Nuget yet (still working through some bugs before official release) but if you download the [latest preview from my.get.org](https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) things should be working. ). So please try this out first.

**Comment by cjkrome** [comment]
@domaindrivendev - Thanks! That will work for me. I appreciate the feedback.

**Comment by lcarrere** [comment]
Hello @domaindrivendev. I don't think it should be considered as a separate request. I am really talking about the issue described by @cjkrome. I think you should consider that as a critical regression based on the previous version. In my opinion this is making automatic SDK generation (at least in .NET) unusable. Using latest source code base does not solve anything. To illustrate the consequence I am attaching a screenshot of generated code (before / faster) which is caused by a missing requestBody in the json produced by Swashbuckle.  
![dif](https://user-images.githubusercontent.com/10449406/62821662-a5953700-bb78-11e9-863c-91953dc4ed04.png)

With best regards,

Loïc Carrère

**Comment by lcarrere** [comment]
Update: Actually it is possible I was still on the RC2. I think your package here is corrupted: https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore
