### ISSUE TITLE
Feature request: Allow schema format configuration on SwaggerDoc level

### ISSUE THREAD

**Issue by sergey-tihon** [domaindrivendev/Swashbuckle.AspNetCore#1258]
Currently I have to choose what format I need (Swagger or OpenApi) for all schemas at once.

If I want to continue use V2:
```fsharp
app.UseSwagger(fun c ->
   c.SerializeAsV2 <- true
) |> ignore
```

Would be really nice to let user specify it on SwaggerDoc level
```fsharp
services.AddSwaggerGen(fun c ->
     c.SwaggerDoc("v1", OpenApiInfo(Title = "My API", Version = "v1", Schema.V2 ||| Schema.V3));
     c.SwaggerDoc("v2", OpenApiInfo(Title = "My API", Version = "v2"));
) |> ignore
```

and then configure Swagger UI to show all
```fsharp
app.UseSwaggerUI(fun c ->
     c.SwaggerEndpoint("/swagger/v1/swagger.json", "My Swagger API v1");
     c.SwaggerEndpoint("/swagger/v1/openapi.json", "My OpenApi API v1");
     c.SwaggerEndpoint("/swagger/v2/openapi.json", "My OpenApi API v2");
) |> ignore
```

this will for sure smoother migration and let keep existing swagger-based automation to work for a while.

**Comment by domaindrivendev** [comment]
With the latest version `5.6.3`, this is already possible. The key is that the Swagger/OpenAPI format (v2 vs v3) occurs at serialization time and is therefore a concern of the `Swagger` middleware as opposed to the `SwaggerGen` services. Because of this, you can configure two instances of the same middleware with and without the `SerializeAsV2` flag:

```csharp
app.UseSwagger(c =>
{
    c.RouteTemplate = "swagger/{documentName}/swagger.json";
    c.SerializeAsV2 = true;
});

app.UseSwagger(c =>
{
    c.RouteTemplate = "/swagger/{documentName}/openapi.json";
});
```
