### ISSUE TITLE
v4 to v5 upgrade guide

### ISSUE THREAD

**Issue by slipdef** [domaindrivendev/Swashbuckle.AspNetCore#1262]
Spent some time to find the upgrade guide here, no success.

**Comment by lust4life** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v5.0.0-rc2/README-v5.md#swashbuckleaspnetcoreswaggergen 

maybe some help can be found here.

**Comment by domaindrivendev** [comment]
As 5.0.0 is still pre-release, documentation still needs work. With that said, I've just released `5.0.0-r3` and provided upgrade/release notes [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v5.0.0-rc3)
.
This is the last planned pre-release before 5.0.0 and if rc3 doesn't raise any major issues I'll be publishing the stable version before end of month. You'll also notice that the readme has now been updated to reflect 5.0.0-rc3 instead of 4.0.0.
