### ISSUE TITLE
[5.0.0-rc4] OpenApiOperation Consumes and Produces

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle.AspNetCore#1296]
Perhaps it would be good to add a compatibility package that gives you better insight to what things moved to even if it throws not implemented exceptions. I have the following simple operation filter that would only say we support Json. I know that produces and consumes became paths (at least that's what I took from the what's new video and I read the release notes) but no idea even looking at the api signature what this would become. Perhaps a wiki or docs updates on common examples on upgrading?

```cs
public class MyOperationFilter : IOperationFilter {
        public void Apply(Operation operation, OperationFilterContext context) {
            operation.Consumes.Clear();
            operation.Consumes.Add("application/json");
            
            operation.Produces.Clear();
            operation.Produces.Add("application/json");
        }
    }
```
To
```cs
 public class MyOperationFilter : IOperationFilter {
        public void Apply(OpenApiOperation operation, OperationFilterContext context) {
            operation.???.Clear();
            operation.???.Add("application/json");
            
            operation.???.Clear();
            operation.???.Add("application/json");
        }
    }
```

**Comment by niemyjski** [comment]
@domaindrivendev Is there any chance you could offer any insight on this?

**Comment by niemyjski** [comment]
I think I figured it out, I added 

```

    [Consumes("application/json")]
    [Produces("application/json")]
```
to my base controller and now it only shows that.

**Comment by ArtemStepanov** [comment]
I have many services with many APIs and controllers, so I wanted to know too how can I handle `operation.Consumes` with V3. Hope that authors will make some "HOWTO MIGRATE FROM V2 TO V3".

**Comment by portal7** [comment]
same case, for file upload, all examples around the web refers version 2 rather 5.0.0.0-rc4

**Comment by SergNikitinSharpDev** [comment]
> I have many services with many APIs and controllers, so I wanted to know too how can I handle `operation.Consumes` with V3. Hope that authors will make some "HOWTO MIGRATE FROM V2 TO V3".

You can try global mvc filter: https://stackoverflow.com/q/59491791/2793919

**Comment by Lung314** [comment]
@niemyjski 

> I think I figured it out, I added
> 
> ```
> 
>     [Consumes("application/json")]
>     [Produces("application/json")]
> ```
> 
> to my base controller and now it only shows that.

I didn't quite understand your solution. I tried a few things based off what you said and got things working on my end. I want to confirm if I got the right idea:

When migrating from Swashbuckle to v5 because of updating dotnet to v3, the Solution to Consume/Produce the desired format is to **REMOVE** the OperationFilter (if you are only using it for Consumes/Produces) entirely and add the attributes [Consume("InsertFormatHere")] and [Produce("InsertFormatHere")] into the base controller. 

Correct me if I am wrong?

**Comment by domaindrivendev** [comment]
Like most things with Swashbuckle, the optimal approach is to let the _actual_ application behavior drive the documentation. For Swashbuckle, the code is the truth, and so it's pretty dam accurate at describing _actual_ behavior, but not always _intended_ behavior. There's a subtle difference here that's important in the context of Swashbuckle.

In your case, your _intention_ is for your API to only accept/respond with JSON media types. However, (documentation aside) have you done anything with your application config to make that intention a reality - i.e. does your application block requests with different media types?

As pointed out above, you can control this at the controller/action level with the `Consumes` and `Produces` attributes and Swashbuckle will honor this accordingly. However, you can also control this at the global level by tweaking configured `InputFormatters` and `OutputFormatters`, and again ... Swashbuckle will honor this accordingly. For example, if there's an Xml formatter enabled, you can disable it as follows:

```csharp
services.AddControllers()
    .AddMvcOptions(c =>
    {
        c.InputFormatters.RemoveType<XmlSerializerInputFormatter>();
        c.OutputFormatters.RemoveType<XmlSerializerOutputFormatter>();
    });
```

Or, if you wanted to restrict the JSON-specific media types to just "application/json" (i.e. not "text/json"), you could configure the Json formatters as follows:

```csharp
services.AddControllers()
    .AddMvcOptions(c =>
    {
        var jsonInputFormatter = c.InputFormatters.OfType<SystemTextJsonInputFormatter>().First();
        jsonInputFormatter.SupportedMediaTypes.Remove("text/json");
        jsonInputFormatter.SupportedMediaTypes.Remove("application/*+json");

        var jsonOutputFormatter = c.OutputFormatters.OfType<SystemTextJsonOutputFormatter>().First();
        jsonOutputFormatter.SupportedMediaTypes.Remove("text/json");
        jsonOutputFormatter.SupportedMediaTypes.Remove("application/*+json");
    });
```

**Comment by hasancemcerit** [comment]
The global MVC filter, both from `AddMvc` or `AddMvcOptions` does not seem to work for .net core 3.1.

**Comment by Mys73rion** [comment]
> I think I figured it out, I added
> 
> ```
> 
>     [Consumes("application/json")]
>     [Produces("application/json")]
> ```
> 
> to my base controller and now it only shows that.

I had to add the type in produces like:
`{Produces("application/json", "application/xml", Type = typeof(FooBar))}`
Otherwise, Swashbuckle didn't care about the produces.

Consumes worked fine.

**Comment by francoscarpa** [comment]
I continue to not understand how I should replace `operation.Consumes.Clear()` and `operation.Produces.Clear()`. Can anyone help me?

**Comment by niemyjski** [comment]
You don't anymore, you just define only the attributes you need on the action or controller level and only those will be populated. I'd be rather selective and only put the attributes for produces on the controller actions that return data and the consumes on those that take it (put/post)

**Comment by francoscarpa** [comment]
I defined `[Consumes("application/json")]` and `[Produces("application/json")]` on a class that derives form `ControllerBase`. Do I just get rid of those four lines of code then?

**Comment by niemyjski** [comment]
Yes

**Comment by domaindrivendev** [comment]
@niemyjski - can this be closed?

**Comment by Dried09** [comment]
Why is it closed while no solution provided? All described here is just a workaround. How is it can be migrated from previous implementation to recent _correctly_?

**Comment by domaindrivendev** [comment]
The correct approach (not a workaround) is described above https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1296#issuecomment-577831898

**Comment by wyatt-troia-msft** [comment]
@domaindrivendev What do we need to do if we're using Newtonsoft.json?

> Or, if you wanted to restrict the JSON-specific media types to just "application/json" (i.e. not "text/json"), you could configure the Json formatters as follows:
> 
> ```cs
> services.AddControllers()
>     .AddMvcOptions(c =>
>     {
>         var jsonInputFormatter = c.InputFormatters.OfType<SystemTextJsonInputFormatter>().First();
>         jsonInputFormatter.SupportedMediaTypes.Remove("text/json");
>         jsonInputFormatter.SupportedMediaTypes.Remove("application/*+json");
> 
>         var jsonOutputFormatter = c.OutputFormatters.OfType<SystemTextJsonOutputFormatter>().First();
>         jsonOutputFormatter.SupportedMediaTypes.Remove("text/json");
>         jsonOutputFormatter.SupportedMediaTypes.Remove("application/*+json");
>     });
> ```

**Comment by wyatt-troia-msft** [comment]
It is unfortunate that "produces" and "consumes" aren't exposed on the operation object any longer.

**Comment by juniwang** [comment]
We want to stop writing `produces` and `consumes` on each operation since we already set it globally(previously `SwaggerDocument.Produces` and `SwaggerDocument.Consumers`). Any way to archive this? writing the same value everywhere sounds superfluous.

**Comment by midgetspy** [comment]
None of the solutions above address my use case, which is as follows:

My application uses `MediaTypeApiVersionReader` for ApiVersioning which means that it expects the version to be part of the `Content-Type` header of the request eg `Content-Type: application/json; v=3.0`.

Swashbuckle doesn't support this (https://github.com/domaindrivendev/Swashbuckle.WebApi/issues/1133), so the UI provides only `application/json` in the "Request Content Type" dropdown rather than each version as expected. This means that the UI is not able to make requests to anything but the default API version.

In order to remedy this I had previously used an IOperationFilter which manually populated `Produces` and `Consumes` with a list of media types which included the versions. This changed what was populated in the "Request Content Type" dropdown in the UI and allowed users to make requests to different API versions from the UI.

The removal of `Consumes`/`Produces` seems to leave no workaround for the lack of Media Type API versioning support. @domaindrivendev is there a new way to work around this or is it now simply impossible to use Swashbuckle if you also use Media Type API versioning?

**Comment by domaindrivendev** [comment]
@midgetspy firstly, you can still use an `IOperationFilter` to add/remove/edit the media types that are supported by a given operation. But, because v3 of the Swagger/OpenAPI spec [models these concepts differently](https://swagger.io/docs/specification/media-types/), and SB is now based on v3, you'll need to understand those difference and then update your filter configuration accordingly.

Secondly, there is no reason why you shouldn't be able to use Swashbuckle along with API versioning by media type. But, to do this it would be good to know how your actually implementing that versioning strategy in your ASP.NET Core app. Are you using `Microsoft.AspNetCore.Mvc.Versioning`? If so then I know for a fact that it integrates fairly seamlessly with Swashbuckle including support for versioning by media type. Here's some related docs that might be helpful:

- [Integrating ASP.NET API Versioning with Swashbuckle](https://github.com/dotnet/aspnet-api-versioning/tree/ms/samples/aspnetcore/SwaggerSample)
- [Versioning by Media Type with ASP.NET API Versioning](https://github.com/dotnet/aspnet-api-versioning/wiki/Versioning-by-Media-Type)

If you're using something else then perhaps you could create a very simple sample app to demonstrate and push up to github so I can pull down and troubleshoot.
