### ISSUE TITLE
Showing descriptions (from XML comments) for UDT properties

### ISSUE THREAD

**Issue by wizofaus** [domaindrivendev/Swashbuckle.AspNetCore#1303]
Version: Swashbuckle.AspNetCore - 4.0.1

Currently if a property in an object is of UDT/schema, and Xml comments have been configured properly, Swashbuckle generates the swagger.json as

                               "aUsefulProperty": {
                                     "$ref":"#/definitions/MyPropertyModel",
                                       "description":"XML summary field for my property"
                               }

even though the spec specifically says that when $ref is present, all other sibling fields are ignored (see https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1150). The upshot of this is that the description is never shown.
While you can include a description in the MyPropertyModel definition, if you have two properties of the same type (using the same model), they can't have different descriptions. They can't even have different meta-properties such as whether they are required.

In the end after much experimentation I was able to get this to work using a schema filter that does:

```
                    foreach (var prop in schema.Properties.Values)
                        if (prop.Ref != null)
                        {
                            prop.AllOf = new[] { new Schema { Ref = prop.Ref } };
                            prop.Ref = null;
                        }
```
And this actually works perfectly - you can combine a "description" with an "allOf" that has a single $ref entry, and the UI works as expected (showing the xml summary for the property as the description if present, otherwise showing the one for the class).

But would it be reasonable to expect Swashbuckle to do this automatically, or have a simpler/more-obvious way of achieving this?  Is there any change in this regard in v5.0.0?

**Comment by wizofaus** [comment]
(BTW I realise this code has been signficantly rewritten since v4.0.1, and I'm looking into whether the latest version will help or not)

**Comment by domaindrivendev** [comment]
If you upgrade to the latest version `5.0.0-rc4` (very close to stable release), then I believe the invalid output issue is resolved - i.e. descriptions are only provided with inline schema definitions.

However, as you pointed out there's still no easy way to provide "contextual" descriptions for different properties that use the same custom type. This is a structural constraint that also limits the ability to use other contextual meta-properties, however `required` is _not_ one of these. Because, `required` is actually a collection of property names defined at the containing schema level, you _can in fact_ indicate when specific properties are required, and this should work out-of-the-box.

I had put this down to a Swagger/OpenAPI limitation but admittedly hadn't thought of the `allOf` workaround you mention above. I'm not sure how this might impact some of the client generators, which are often used in conjunction with Swashbuckle, so would need to investigate that a little further. But, off the top of my head, it seems like that may be an approach that could work well, and should be supported out-of-the-box. Interested in submitting a PR?

**Comment by wizofaus** [comment]
Yes sorry you're right regarding 'required'.
I don't mind submitting a PR but what sort of options you do think should exist to control this behaviour?
As it is I'm still using 4.0.1 (in fact, only just upgraded to that from 3.0.0!).

**Comment by domaindrivendev** [comment]
As of `v5.1.0`, there's an optional setting `UseAllOfToExtendReferenceSchemas`, which will cause the generator to "extend" reference schemas with the `allOf` approach you suggested above, enabling descriptions to be included.

**Comment by wizofaus** [comment]
Thanks and good that you made it optional as unfortunately it doesn't play well with swagger-codegen.

**Comment by lonix1** [comment]
`UseAllOfToExtendReferenceSchemas` : it was hard to discover this feature as it isn't in the docs. But it works nicely, thanks!
