### ISSUE TITLE
Wrong PackageReference in Swashbuckle.AspNetCore.Swagger.csproj ?

### ISSUE THREAD

**Issue by tebeco** [domaindrivendev/Swashbuckle.AspNetCore#1308]
Hello.

As you can see here :
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/ad91d72078e1e2276824b38e2483c1d8ab6e5376/src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj#L21-L24
It seems that this nuget (if still supposed to be `aspnetcore3` compliant), need to also target `netcoreapp3.0`

And this `PackageReference` need to be toggle featured based on `$(TargetFramework)`,
That would be `FrameworkReference` for `netcoreapp3.0` then ?
As you can see here :
https://www.nuget.org/packages/Microsoft.AspNetCore.Mvc.Core
Last release was 2.2.5, so it's probably within the Metapackage (that is now part of the `FrameworkReference`

I'm not sure it will behave nicelly on `netcoreapp3.0` + `aspnetcore3.0` (blow at runtime ?) is v5.0.0 is shipped with that assembly => `MissingMethodException`

**Comment by domaindrivendev** [comment]
As it stands, v5.0.0-rc4 is fully compatible with versions 2 & 3 of ASP.Net Core - i.e. it doesn't blow up 😉 

This is because the `PackageReference` syntax used above states that Swashbuckle requires a version of ASP.NET Core ">=" 2.0.0. See [here](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files#controlling-dependency-version) for more info on how this syntax is used to control dependency versions.

**Comment by domaindrivendev** [comment]
Not sure what you mean by "this dependency does not exist anymore". Follow the same link you posted and click the "+ Show More" link at the bottom of the page and you'll see it listed.

Regarding the rest of your points, I'm not exactly sure of the point you're trying to make - very possible a lack of knowledge/context on my side. Perhaps you could provide a concise set of repro steps that demonstrate the problem or some steps to walk me through the hypothetical chain of events you're concerned about?

At a high level though - I will say it's my preference to keep dependency versions as low as possible so that my library can be used by as many applications as possible without forcing them to upgrade their dependencies. I also prefer this over multi-targeting as it simplifies the Swashbuckle code/build process etc. In some cases the multi-targeting can't be avoided but in this case the project compiles against ASP.NET 2.0.0 and works perfectly well with 3.0.0 so I prefer to keep things simple and avoid multi-targeting. If breaking change are introduced with newer version of a depenency, then I will multi-target as neccessary.

**Comment by domaindrivendev** [comment]
Thanks for the references - I'll try read through to get a better understanding of all this.

**Comment by tebeco** [comment]
I swear i tried to setup my new laptop to provide a PR to help
i hope i'll have a full setup by tomorrow ;)

also if it helps anyone here is a gist i attempted to made since this specific question is on going since 3.0 :
https://gist.github.com/tebeco/a6e0d9a3885a0a36e702795219bd4fe9

**Comment by tebeco** [comment]
@domaindrivendev 

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs#L21-L22

can you explain what are these test doing ?
No that "pubternal" Api have been removed, so you have suggestion to make the equivalent for `aspnetcore3.0` ?

https://github.com/aspnet/Announcements/issues/377
https://github.com/aspnet/AspNetCore/issues/8306
https://github.com/dotnet/docs/issues/14708

**Comment by tebeco** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1316

**Comment by tebeco** [comment]
@domaindrivendev if you got idea on how Integration test works in 

I also asked for idea here https://github.com/aspnet/AspNetCore/issues/14954
These 4 points are kinda troubling for me as i'm not really sure about the intention of this all big `FakeApiDescriptionGroupCollectionProvider` doing.
I do get it's used to help the test in a technical way, but as i do not know in detail how `Swashbuckle` works, i'm struggling to understand the intention and so the way to find a fix

**Comment by tebeco** [comment]
here is a potential bug spotted during the PR : 

the use of `Obsolete` API of `Newtsonsoft` :  
`var converter = new StringEnumConveter(bool)`  
`Microsoft.AspNetCore.Mvc.Newtonsoft...m` introduced to help the migration in v3.0 uses `Newtonsoft v12.x`  
`StringEnumConverter` now have a `NamingStrategy` member. It is a RefType so its default value is `null`
it seems that is some scenario and unit test of `Swashbuckle` code run end up throwing `NullReferenceException`

I'm not sure thought if it can happen in production code or only `test code` of this repo
there's multiple place of the code relying on `Obsolete` api if this repository itself so it's kinda weird to understand how should i try to fix it

**Comment by domaindrivendev** [comment]
> These 4 points are kinda troubling for me as i'm not really sure about the intention of this all big FakeApiDescriptionGroupCollectionProvider doing

At it's core, Swashbuckle converts the `ApiDescriptions`, produced by the ASP.NET Core framework, into Swagger/OpenApi `Operations`. So, `ApiDescriptions` are input to many of the Swashbuckle unit tests. Rather than hand crafting them for each test, I opted to leverage the framework code that generates them. Unfortunately, this wasn't as easy as you might think outside of an up-and-running ASP.NET Core application, and so I had to create a fairly ugly test class to pull the relevant pieces together in a unit test context.

However, up to now, it's required very little change and so the tradeoff has been very beneficial - allowing for "fast" tests that take inputs with state that is extremely close to the real thing.

As the `ApiExplorer` unit tests leverage this same technique, albeit for the "Act" step instead of the "Arrange" step), I ended up basing the `FakeApiDescriptionGroupCollectionProvider` on the following:

https://github.com/aspnet/AspNetCore/blob/master/src/Mvc/Mvc.ApiExplorer/test/DefaultApiDescriptionProviderTest.cs#L1886.

**Comment by tebeco** [comment]
thx
i'll take a look at these tests to get a grip on it.
As said in the PR if you are confident with the version opened on the right and the rest you made so far
I can try to :
* change the title here
* bump 2.0 to 2.1 in all test (PR 1)
* cross target only the unit / integration test (no duplicate for test as much as possible) (PR 2)
* do i create another PR duplicating all unit test but using `UseRouting()` and `UseEndpoints()` ? (PR 3)
* then continue the ongoing PR (full cross target PR)

that way you could either release 5.0.0 now or after PR 1 / 2 (maybe 3) (it's your go on that)
* 5.0.0 can be released without the first one for sure
* PR 2 and 3 are more like a quality / regression check, but as you previously said nobody really found (yet) a scenario where is blow at runtime (it will happened if `swashbuckle` use an api of an assembly that changed during 3.x and i would have seen it during cross target i believe)
* full cross targeting will wait a bit longer
* it could be a 5.1 later on for full cross targeting
* i have the feeling that lots of people are waiting for the release and don't want to block people still targeting 2.x

Sorry for the delay everytime, i mostly see your answer the day after or late in the afternoon (from France)
i'll see this morning if i can surface the 2 first PR as it feels smaller and easier (i hope)

**Comment by tebeco** [comment]
FYI :
Regarding the Full cross targeting, i got lots of help from @pranavkm here : https://github.com/tebeco/Swashbuckle.AspNetCore/pull/1

This fixed a lots of the complexity :
https://github.com/tebeco/Swashbuckle.AspNetCore/blob/c9431bc5543eb86445fde8a0719160c164a2f8a5/test/Swashbuckle.AspNetCore.SwaggerGen.Test/Fixtures/Fakes/FakeApiDescriptionGroupCollectionProvider.cs#L139-L147

**Comment by tebeco** [comment]
FYI :

I'm splitting the PR in small other one, i did not thought this first one would be a tough one :D

Currently trying to bump references / dependencies :
* `xunit` to `2.4.1` (latest because test project)
* `netcoreapp2.0` to `netcoreapp2.1`
* `PackageReference 2.0.0` to `PackageReference 2.1.0`

I'm having troubles ... with unit test again :
* Again, the test again `CancellationToken`
* Again, the 3 tests with `json` `ContentType`
* Again, the test with `xml` `ContentType`

(i changed the Issue title as you can see to let you release by the time i managed to make everything works)
