### ISSUE TITLE
<list><item> etc. doesn't work for XML comments (4.0.1)

### ISSUE THREAD

**Issue by wizofaus** [domaindrivendev/Swashbuckle.AspNetCore#1322]
According to https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/xmldoc/list we're supposed to use 
```
    <list type="bullet">  
      <item>  
        <term>term</term>  
        <description>description</description>  
      </item>  
    </list>  
```
for bulleted lists in XML comments. But for swashbuckle and generating swagger, this doesn't work as expected, rather you need to use `<ul><li>...</li></ul>` or better `<dl><dt>...</dt><dd>..</dd></dl>`.

**Comment by voroninp** [comment]
I've mistakenly created [similar issue](https://github.com/domaindrivendev/Swashbuckle/issues/1342) for other repo.

**Comment by domaindrivendev** [comment]
By design, Swashbuckle supports a very specific subset of the XML comment tags as this turns out to be a convenient way for API authors to incorporate human-friendly descriptions into their API descriptions.

Supporting all of them would add significant complexity to the project. I think the current subset supports the majority of use cases and therefore I've no plans to make any enhancements in this area at present.

**Comment by wizofaus** [comment]
But this is explicitly what Microsoft say should be used?
I'd be happy to have a crack at implementing, I don't understand why you would just close it...

**Comment by domaindrivendev** [comment]
XML comments were created to document C# code, not Http-based API’s. As a convenient feature, Swashbuckle “supports” piggybacking a subset of that technology to describe http-based APIs but that is not their original purpose.
