### ISSUE TITLE
CVE-2017-11879

### ISSUE THREAD

**Issue by smiles3983** [domaindrivendev/Swashbuckle.AspNetCore#1332]
Due to the below vulnerability with .net core 2.0, we have to abandon use of Swagger in our organization. 

https://nvd.nist.gov/vuln/detail/CVE-2017-11879

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/ece92f826527d532bb1e3312ba683d3ee4807c8b/src/Swashbuckle.AspNetCore.Swagger/Swashbuckle.AspNetCore.Swagger.csproj#L22

**Comment by domaindrivendev** [comment]
Swashbuckle shouldn't be responsible for which version of ASP .NET Core you run your application on. The above merely states that Swashbuckle will work on 2.0.0 or upwards. If you're application runs on ASP.NET Core, you should explicitly set the core version in your app rather than relying on the transitive dependency through Swashbuckle.

**Comment by domaindrivendev** [comment]
With that said, we will likely increment the min supported version to 2.1 in the upcoming release of `Swashbuckle.AspNetCore.5.0.0`

**Comment by smiles3983** [comment]
yeah, were using 2.2, but NuGet still installs the 2.0 versions due to the dependency version specified.  So the NexusIQ security checks still see it as a threat, even though we are not executing it.
