### ISSUE TITLE
ASP.NET Core 3.0 - Swagger does not take property naming policy into account

### ISSUE THREAD

**Issue by GiorgioG** [domaindrivendev/Swashbuckle.AspNetCore#1343]
In an ASP.NET Core 3.0 API app, I need snake casing support.  When I do the following, the output generated by Swashbuckle (5.0.0-rc-4) ignores the property naming policy. 

`    services.AddControllers().AddJsonOptions(options =>
            {
                options.JsonSerializerOptions.PropertyNamingPolicy = new SnakeCasePropertyNamingPolicy();
            });`

**Comment by GiorgioG** [comment]
I managed to figure out a way to get this to work using a schema filter.  This doesn't seem like the cleanest way but it works.

Here's the relevant code for anyone else looking to cobble this together:
https://gist.github.com/GiorgioG/d674892da20369d2a7869cdc1bf7d41b

**Comment by artemsv** [comment]
It seems it fails to generate description for snake cased properties... Even if they use JsonPropertyName ("prop_name") attribute and not the whole policy...

**Comment by domaindrivendev** [comment]
This version defaults to honoring System.Text.Json (as opposed to Newtonsoft) serializer behavior. You need to expicitly opt-in to honoring Newtonsoft as described in the readme:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft

**Comment by V0ldek** [comment]
It does not honor System.Text.Json, though. If I set a custom naming policy for System.Text.Json and then include swagger gen it still generates the properties in camelCase:

```csharp
builder.Services.ConfigureHttpJsonOptions(
    x =>
    {
        x.SerializerOptions.PropertyNamingPolicy = new JsonSnakeCaseNamingPolicy();
    });

builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();
```

**Comment by drmohundro** [comment]
@V0ldek I'm seeing the same thing, but I was able to get snake casing to work with SwaggerGen and Minimal APIs like this:

```cs
    builder.Services.AddTransient<ISerializerDataContractResolver>(_ => new JsonSerializerDataContractResolver(
        new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower, }
    ));
```

I was able to find references to this at: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerGen/DependencyInjection/SwaggerGenServiceCollectionExtensions.cs#L33-L43 and it seems like there may be a bug there because the code in the `#else` just uses the default `JsonSerializerOptions` if the code isn't `NETSTANDARD2_0`:

That's why plugging in your own `ISerializerDataContractResolver` fixes it.
