### ISSUE TITLE
ValidationProblemDetails vs ProblemDetails

### ISSUE THREAD

**Issue by Kevweir** [domaindrivendev/Swashbuckle.AspNetCore#1412]
I posted a lengthy detailed comment about the problem over at NSwag repo but the same problem applies when I tried using Swashbuckle.AspNetCore.   I've been working with both...

https://github.com/RicoSuter/NSwag/issues/2571

**Comment by Kevweir** [comment]
I appreciate the OpenAPI spec is platform agnostic which brings up the interesting dilemma of why even include ProblemDetails if it can't be used in any concrete implementations without being changed.  The problematic part of course being Extensions as no vendor that I know of supports that naming convention directly.  Perhaps this isn't an issue for the spec to address but is more a downstream problem and how client generates deal with Extensions???

**Comment by domaindrivendev** [comment]
If I'm understanding your issue correctly, you seem to be saying that Swashbuckle _auto-generates_ "error" response descriptions based on the `ProblemDetails` type as opposed to the `ValidationProblemDetails` type. I'm a little confused by this because in fact, Swashbuckle doesn't auto-generate _any_ "error" response descriptions. If you want to include error responses, you need to explicitly decorate your action with `ProducesResponseType` attributes, and indicate the response type yourself. For example:

```csharp
[ProducesResponseType(typeof(ValidationProblemDetails), 400)]
public IActionResult CreateOrder([FromBody]Order order)
```

**Comment by Kevweir** [comment]
How embarrassing.  After many hours of looking through documentation and searching the web I did not find this documented anywhere but in retrospect it should have been obvious.  Thanks you!
