### ISSUE TITLE
own topbar with the logo title and link

### ISSUE THREAD

**Issue by kostyrin** [domaindrivendev/Swashbuckle.AspNetCore#1436]
Own layout  is broken after update to 5.0.0-rc5. then checked [the sample](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/CustomUIIndex/Swagger/index.html). then will be ok. but there is not info how to change the topbar. Is there a better way to set own topbar? should to be like this
![image](https://user-images.githubusercontent.com/8361000/71520971-72eda000-28c7-11ea-9d1d-a874b7a825ee.png)

**Comment by domaindrivendev** [comment]
This is really a question for the [swagger-ui folks](https://github.com/swagger-api/swagger-ui/) rather than Swashbuckle. Here's a related ticket there:

https://github.com/swagger-api/swagger-ui/issues/4390

Once you've figured out how to do it with swagger-ui, you should be able to incorporate via Swashbuckle using custom CSS/JS injection or fully customized index.html.

**Comment by martincostello** [comment]
Closing as external.
