### ISSUE TITLE
Swapped Order of Nested Objects? OperationId from controller function name?

### ISSUE THREAD

**Issue by skrawn** [domaindrivendev/Swashbuckle.AspNetCore#1447]
Hi, I'm almost done with my transition from .NET Core 2.2 to 3.1 but I'm stuck on one last issue with Swashbuckle where my response objects aren't serialized in the same order.

When I have these two objects:
```
    public class ControllerResponse<T>
    {
        [JsonProperty(PropertyName = "data", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public T Data { get; set; }

        [JsonProperty(PropertyName = "error", DefaultValueHandling = DefaultValueHandling.Ignore)]
        public string Error { get; set; }
    }

    public class ComplexResponse
    {
        public Guid Id { get; set; }
        public string Garbage { get; set; }
    }
```
And a controller that returns ComplexResponse at the type of ControllerResponse:
```
        [HttpGet]
        [Route("complex")]
        public ControllerResponse<ComplexResponse> GetGarbage()
```

Under Swashbuckle 4.0.1:
```
    "/api/v1/WeatherForecast/complex": {
      "get": {
        "tags": ["WeatherForecast"],
        "operationId": "GetGarbage",
        "consumes": [],
        "produces": ["text/plain", "application/json", "text/json"],
        "parameters": [],
        "responses": {
          "200": { "description": "Success", "schema": { "$ref": "#/definitions/ControllerResponse[ComplexResponse]" } }
        }
      }
    }
```

Under Swashbuckle 5.0.0:
```
    "/api/v1/WeatherForecast/complex": {
      "get": {
        "tags": ["WeatherForecast"],
        "produces": ["text/plain","application/json","text/json"],
        "responses": {
          "200": {"description": "Success","schema": {"$ref": "#/definitions/ComplexResponseControllerResponse"} }
        }
      }
    }
```

This means that all of the models in UI in front of this API need to be refactored to have their names fixed. It would be awesome if the models matched the old spec! Is there a setting I've missed that could fix this?

The other problem that I've found a work-around for is how Swashbuckle 4 would default to using the function name of an endpoint as the operationId. I can work-around that by setting the Name field `[HttpGet("complex", Name = "GetGarbage"]` but it would be great to have the original functionality back.

Two projects to replicate this behavior:
[WebApplication1](https://github.com/skrawn/WebApplication1) - .NET Core 3.1 & Swashbuckle 5.0.0
[WebApplication2](https://github.com/skrawn/WebApplication2) - .NET Core 2.2 & Swashbuckle 4.0.1

**Comment by domaindrivendev** [comment]
For the second problem you mentioned, see https://github.com/domaindrivendev/Swashbuckle.AspNetCore#assign-explicit-operationids, specifically "Option 2" is what you're looking for to maintain the old behavior

For the actual issue, I'm not sure I fully understand. Are you referring to the `schemaId` that's generated and used to reference shared schema's from the `definitions` dictionary. If so, it's worth noting that the pattern used out-of-the-box has changed in this version by design. The old pattern is actually invalid as per the JSON Schema specification (because of the `[,]` characters). Although I wouldn't recommend it, you _could_ revert to the old pattern by applying your own strategy via the `CustomSchemaIds` config setting. See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/752 for more context around the rationale for this change.
