### ISSUE TITLE
Support specifying response type in xml <response> element

### ISSUE THREAD

**Issue by mchandschuh** [domaindrivendev/Swashbuckle.AspNetCore#1458]
Currently we can specify different expected response codes and a description of each using the follow syntax in XML comments:
``` xml
<response code="200">The operation completed successfully.</response>
```

I prefer the XML comments over the `[SwaggerResponse]` attribute as, to me, it seems cleaner visually and also doesn't go to waste as the information it regurgitated throughout various code editors and library packages. After browsing the code, I was able to locate where we [resolve the `<response>` element and convert it into the response meta data](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/XmlComments/XmlCommentsOperationFilter.cs#L125).

It seems as though it should be fairly easy to add support for a `type` attribute in the `response` element.  Granted, at this stage we would only have a string type name, but my hunch is that we'll be able to confidently resolve a full `Type` object when we go to serialize the actual document. Another option, as a convenience to those using IDEs w/ deep XML/type support, we could support the type reference via the `<seealso>` tag, which tools such as Visual Studio, automatically expect to contain a member reference. This would provide users the ability to use the XML documentation to affect all textual documentation for a given operation, vs right now it's either all attributes (via `[SwaggerOperation]` or an amalgamation of the attributes and XML docs.

Proposed Syntax 1:
``` xml
<response code="200" type="My.Full.Type.Name">My response description<response>
```

Proposed Syntax 2
``` xml
<response code="202">My response description.<seealso cref="My.Full.Type.Name"/></response>
```

In #2, common toolchains are already able to use the current scope to resolve symbols within the `<seealso>` tag which provides some code completion/sanity check as well as some brevity over the full type name approach, so often you'll be able to just write `Name` instead of `My.Full.Type.Name`. IIRC, Roslyn has functions that would be able to resolve the type name into a FQTN based on the current file scope the XML comment occupies.

I'm happy to implement the change, but wanted to check with the community first to confirm I'm thinking about this correctly. Let me know what everyone thinks and if there's anything I'm overlooking with my approach.

Thanks!

**Comment by domaindrivendev** [comment]
TBH, I have no desire to extend the integration with XML comments.

**Comment by domaindrivendev** [comment]
I have no desire to extend the integration with XML comments at present. Unlike yourself, I prefer to express this information as code rather than text as it provides design-time discovery (intellisense) and keeps the docs more tightly in sync with the actual implementation (i.e. via type safety)

Furthermore, ASP.NET Core already provides the `ProducesResponseTypeAttribute`, from which `SwaggerResponseAttribute` is derived, as the canonical method for describing response codes and/or types that can't be infeferred from the action signature. By using either of these, the additional information will be exposed in the `ApiExplorer` data (lower-level API metadata exposed by ASP.NET Core directly) as well as Swagger.
