### ISSUE TITLE
Swashbuckle does not work with ASP .Net core 3.1

### ISSUE THREAD

**Issue by TonyTroeff** [domaindrivendev/Swashbuckle.AspNetCore#1512]
I followed this tutorial here (https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-3.1&tabs=visual-studio) and this is the error I'm getting after I run the application: 
![image](https://user-images.githubusercontent.com/33567383/73577068-a69e8580-4484-11ea-9ba4-fb947c9dff82.png)

I'm working with ASP .Net Core 3.1, Swashbuckle.AspNetCore 5.0.0 and Microsoft.OpenApi 1.1.4.

**Comment by domaindrivendev** [comment]
You must have some old DLLs lying around as the type referenced in the error is not even present in the 5.0.0 build. Try clearing your build artifacts

**Comment by TonyTroeff** [comment]
I see, but that did not help - clean, rebuild did not help. manually removed all "bin" and "obj" folders but still nothing helped me. This issue happened after upgrading your package from 5.0.0-rc4 to 5.0.0

**Comment by tautvydasversockas** [comment]
Same here! After I upgraded from 5.0.0-rc4 to 5.0.0 I started getting the same error. At the end I downgraded back to 5.0.0-rc4 and it works now.

**Comment by domaindrivendev** [comment]
@TonyTroeff or @tautvydasversockas - obviously I can't repro your issue, otherwise my entire integration test suite would be failing. As I can't do much without a local repro, perhaps one of you could take a few mins to create a minimal application from scratch that repro's the issue and then post it to Github where I can pull it down and take a look?

**Comment by tautvydasversockas** [comment]
@domaindrivendev and @TonyTroeff - I think I found the issue.

My nuget packages before swagger upgrade:

- Swashbuckle.AspNetCore - Version="5.0.0-rc4"
- Swashbuckle.AspNetCore.Swagger - Version="5.0.0-rc4"
- Swashbuckle.AspNetCore.SwaggerUI - Version="5.0.0-rc4"
- MicroElements.Swashbuckle.FluentValidation - Version="3.0.0-rc.2"

I upgraded first three of them to version 5.0.0 and the swagger started throwing errors.
However, while debugging I realised that MicroElements.Swashbuckle.FluentValidation nuget has newer version 3.0.0-rc.5. I upgraded MicroElements.Swashbuckle.FluentValidation to version 3.0.0-rc.5 and the issue seems to be gone.

All in all, it seems that MicroElements.Swashbuckle.FluentValidation nuget version 3.0.0-rc.2 doesn't work very well with other version 5.0.0 swagger nuget packages (at least one of the first 3).

I think this issue can be closed :)
