### ISSUE TITLE
SwaggerApplicationConvention should be optional

### ISSUE THREAD

**Issue by hikalkan** [domaindrivendev/Swashbuckle.AspNetCore#154]
Hi,

SwaggerApplicationConvention is defined like that:

``` C#
public class SwaggerApplicationConvention : IApplicationModelConvention
{
    public void Apply(ApplicationModel application)
    {
        application.ApiExplorer.IsVisible = true;
        foreach (var controller in application.Controllers)
        {
            controller.ApiExplorer.GroupName = controller.ControllerName;
        }
    }
}
```

It overrides GroupName by ControllerName. I believe it should be optional. Because it overrides my custom Group names.

**Comment by kirk-marple** [comment]
Have you found a workaround for this?  I'm not getting any custom group names, and this seems to be why.

**Comment by hikalkan** [comment]
I couldn't.

**Comment by domaindrivendev** [comment]
Hey there. If you goal is custom grouping of operations in the swagger-ui, then you can use the __GroupActionsBy__ config option. This overrides the default which is based on controller name.

However, there's few additional things to note ..

1. In the latest code (preview only available on MyGet), I've renamed this to __TagActionsBy__ as it's more reflective of what's happening in the generated Swagger (i.e. adding a tag to operations). The UI does use this to apply the grouping but from a Swagger generation perspective (SB's primary concern), it's applying tags.

2. In the latest code, I've removed the hardcoded assignment of GroupName from the application convention, and pull controller name directly from the action descriptor when determining the default tag for operations. This seemed a little better because it free's up GroupName for a higher level of grouping, such as API version, which I believe to be one of the primary use-cases it was created for.

**Comment by domaindrivendev** [comment]
@hikalkan - if you're still setting GroupName for your own purposes, there's a couple of changes in the latest version you should be aware of. Before going into the details, note that the package has been renamed from Swashbuckle.6.0.0-* to Swashbuckle.AspNetCore.1.0.0-* (1.0.0-rc1 currently available on Nuget).

In the latest version, "GroupName" is no longer set by Swashbuckle. However, the generator DOES use the GroupName value to split operation descriptions into one or more Swagger documents. More on this here - https://github.com/domaindrivendev/Swashbuckle.AspNetCore#generate-multiple-swagger-documents.

I'm not sure what you're using custom GroupName's for but it's my understanding that attribute was introduced into ASP.NET Core primarily to support describing multiple API versions and this fits quite nicely with the latest Swashbuckle behavior. That is, you define one or more Swagger Documents (e.g. 1 document per version) and then assign actions to a document via the "GroupName" attribute (by attribute or convention).

So, perhaps these new semantics will fit your use-case well. If not though, you can override this behavior and assign your own custom strategy for including actions in the defined Swagger documents:

```csharp
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new Info { Version = "v1", Title = "API V1" });
    c.DocInclusionPredicate((docName, api) => true); // include all actions regardless of GroupName
});

**Comment by hikalkan** [comment]
Thank you very much for the information. I'll try it.

**Comment by Littlemenace** [comment]
I have just spent the last day trying to work out why the ApiExplorer in my .NET Core 2.2 project listed all controllers in my combined MVC / API project and not just the ones marked with the [ApiController] attribute and discovered it was the convention added by the .AddSwaggerGen extension on IServiceCollection.

Would it be possible to add an option into the startup configuration to disable the automatic convention registration of the SwaggerApplicationConvention class?

For anyone looking for a resolution to this, you can simply add the following after calling .AddSwaggerGen:
`//services.Configure<MvcOptions>(c => { c.Conventions.RemoveType<SwaggerApplicationConvention>(); });`

P.S. thank you for all the hard work put into this, without this project things would have taken so much longer...
