### ISSUE TITLE
Properties description of schema is empty in swagger.json when use [DataMemberAttribute]

### ISSUE THREAD

**Issue by ThomasEA** [domaindrivendev/Swashbuckle.AspNetCore#1584]
I'm using OpenApi 3.01 and AspNet Core.
When using the DataMember attribute to change the name of a property, it is changed in swagger.json, but the description of that property in the model XML file is not being displayed.
Steps to reproduce this issue:

```
[DataContract]
public class Item
  {

    public Item(){}

    /// <summary>
    /// Id of item description
    /// </summary>
    /// <value>Id</value>
    [DataMember]
    public int Id {get; set;}

    /// <summary>
    /// Name of item description
    /// </summary>
    /// <value>Name</value>
    [DataMember(Name = "NameOfItem")]
    public int Name {get; set;}
}
```
The Name property will be displayed in swagger.json as NameOfItem, however you description will not be shown.

But if change the property to NameOfItem as in the following code, the text 'Name of item description' is displayed in the schema description:
```
[DataContract]
public class Item
  {

    public Item(){}

    /// <summary>
    /// Id of item description
    /// </summary>
    /// <value>Id</value>
    [DataMember]
    public int Id {get; set;}

    /// <summary>
    /// Name of item description
    /// </summary>
    /// <value>Name</value>
    [DataMember(Name = "NameOfItem")]
    public int NameOfItem {get; set;}
}
```

**Comment by domaindrivendev** [comment]
Which serializer are your using - _Newtonsoft_ or _System.Text.Json (STJ)_? I'm asking because the latter DOES NOT currently honor these attributes when serializing to JSON (see https://github.com/dotnet/runtime/issues/30009). Therefore, it wouldn't make any sense for SB to honor these either in that case.

Newtonsoft on the other hand DOES honor these attributes, and therefore so will SB ... provided it's configured correctly.

Perhaps you don't have SB configured correctly for Newtonsoft. Please make sure you've followed the steps [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft) correctly and then try again.

**Comment by ThomasEA** [comment]
I was using Swashbuckle.AspNetCore.Newtonsoft 5.0.0 instead of 5.1.0. I changed the .csproj file to 5.0.1 and the description of the schema members was displayed correctly in swagger.json.
Issue solved.
Thank you for your help.
