### ISSUE TITLE
It's impossible to use different naming strategy for query parameters

### ISSUE THREAD

**Issue by bajdka** [domaindrivendev/Swashbuckle.AspNetCore#1588]
**Used versions:**
Swashbuckle.AspNetCore 5.2.0
Swashbuckle.AspNetCore.Newtonsoft 5.2.0

**Steps to reproduce:**
I use following model of query parameters: id & pass.
```
    [JsonObject(NamingStrategyType = typeof(CamelCaseNamingStrategy))]
    public class OfferStatusGetRequest
    {
        public Guid Id { get; set; }
        public string Pass { get; set; }
    }
```
I tried also setting property name `[JsonProperty(PropertyName = "id")]` but it didn't affect the schema.

**Actual result:**
- query parameters names are written in pascal case (Id, Pass)
```
"parameters": [
          {
            "name": "Id",
            "in": "query",
            "schema": {
              "type": "string",
              "format": "uuid"
            }
          },
          {
            "name": "Pass",
            "in": "query",
            "schema": {
              "type": "string",
              "nullable": true
            }
}
```

**Expected result:**
- query parameters names are written in camel case (based on NamingStrategyType or PropertyName): id, pass

**Comment by domaindrivendev** [comment]
Swashbuckle aside, applying serializer attributes/settings have absolutely zero effect on "query-bound" models. In fact, the serializer (in this case Newtonsoft) only comes into play when deserializing into a "body-bound" model. So, from an API implementation perspective - you're use of the `JsonObjectAttribute` is completely redundant if the model is bound to query parameters (i.e. via `[FromQuery]`).

If you really want to change the naming strategy for query parameters, then you need to configure "model-binding" as opposed to "serializer" behavior. For example, if you wanted to apply snake-case, you could do it as follows:

```csharp
    public class PagingParams
    {
        [FromQuery(Name = "page-no")]
        public int PageNo { get; set; }
        [FromQuery(Name = "page-size")]
        public int PageSize { get; set; }
    }
```

Now ... back to Swashbuckle. It will automatically honor the binding configuration above. So, you could use this approach. However, if you're goal is to merely "document" them in camelCase rather than PascalCase (ASP.NET Core will accept either), and you're not actually looking to change the binding behavior, then Swashbuckle has a handy setting `DescribeAllParametersInCamelCase` that you can apply globally.

**Comment by bajdka** [comment]
I'm very grateful for the detailed explanation. And also positively surprised with `DescribeAllParametersInCamelCase` option being already there - it will do the required job in my case. Thank you!

**Comment by arisliang** [comment]
> Swashbuckle aside, applying serializer attributes/settings have absolutely zero effect on "query-bound" models. In fact, the serializer (in this case Newtonsoft) only comes into play when deserializing into a "body-bound" model. So, from an API implementation perspective - you're use of the `JsonObjectAttribute` is completely redundant if the model is bound to query parameters (i.e. via `[FromQuery]`).
> 
> If you really want to change the naming strategy for query parameters, then you need to configure "model-binding" as opposed to "serializer" behavior. For example, if you wanted to apply snake-case, you could do it as follows:
> 
>     public class PagingParams
>     {
>         [FromQuery(Name = "page-no")]
>         public int PageNo { get; set; }
>         [FromQuery(Name = "page-size")]
>         public int PageSize { get; set; }
>     }
> Now ... back to Swashbuckle. It will automatically honor the binding configuration above. So, you could use this approach. However, if you're goal is to merely "document" them in camelCase rather than PascalCase (ASP.NET Core will accept either), and you're not actually looking to change the binding behavior, then Swashbuckle has a handy setting `DescribeAllParametersInCamelCase` that you can apply globally.

Just for a feedback, in aspnetcore 8.0, and Swashbuckle.AspNetCore 9.0.3
- `[FromQuery(Name = "page-no")]` does not seem to work anymore.
- the global configuration `DescribeAllParametersInCamelCase` still works.
