### ISSUE TITLE
Readonly properties

### ISSUE THREAD

**Issue by SkinnySackboy** [domaindrivendev/Swashbuckle.AspNetCore#1592]
Hi,

Firstly, thanks for your hard work!

I have just switched to v5.2.1 and previous readonly properties are no longer being generated with the "readonly" attribute. So somethign like:

public string Code { get; }

get generated to (using C# AutoRest):

public string Code { get; set; }

Previously this was only happenin on enums, but is now happening on everything, including value types. Is this a bug or by design?

Thanks in advance.

**Comment by domaindrivendev** [comment]
Do you know which serializer, Newtonsoft or System.Text.Json (STJ), is in use by your application? The `readonly` flag is derived according to "serializer behavior". STJ requires properties to have public setters for de-serialization. Newtonsoft on the other hand, _does_ support de-serialization of payload values into properties with no public setter, provided the declaring type has a constructor with a parameter of the same name.

So, if you're using Newtonsoft AND your DTOs have constructors for setting the properties, then the `readonly` flag WILL NOT be set, and this is by design. Could this be the case?

If this is not the case, then it could be a bug and I would suggest creating a minimal sample app that repro's the issue, and posting to github where I can pull down and repro myself.

**Comment by SkinnySackboy** [comment]
Thanks for the quick reply!

We are using Newtonsoft and our DTOs do indeed have constructors for setting these properties. This was already the case previously and in v4.0.1 at least it was creating readonly fields, but I see your point so this almost certainly isn't a bug.

Thanks again.

**Comment by domaindrivendev** [comment]
No problem. Given that you're using Newtonsoft AND you have the constructors, then I imagine your API will in fact accept those values in the payload. Therefore, `readOnly = false` seems like the correct outcome.

**Comment by SkinnySackboy** [comment]
Thanks again @domaindrivendev
