### ISSUE TITLE
Enable extending SchemaGenerator

### ISSUE THREAD

**Issue by sergiomcalzada** [domaindrivendev/Swashbuckle.AspNetCore#1611]
The SchemaGenerator can be extended because none of its members are virtual.

I have an `Evelope<T>` class such schema should be generated as `T`, but can't do it without extending the  `Schemagenerator` class.

It could be done overriding `GenerateSchemaForType` but the method is not virtual.

Thanks in advance

**Comment by domaindrivendev** [comment]
I have no desire to make intentionally private methods public/protected as this will increase the public surface area of the Swashbuckle library and make it much harder for me to make internal refactors without breaking existing consumers.

Have you looked at the intentionally exposed extensibility options in the readme. The following sections may be of use for your particular use case:

- https://github.com/domaindrivendev/Swashbuckle.AspNetCore#override-schema-for-specific-types
- https://github.com/domaindrivendev/Swashbuckle.AspNetCore#extend-generator-with-operation-schema--document-filters

If these don't meet your needs then you can still provide a custom implementation of `ISchemaGenerator` that's based on the default. But, rather than using inheritance, you can use simple composition as follows:

```csharp
// CustomerSchemaGenerator.cs
public class CustomSchemaGenerator : ISchemaGenerator
{
    private readonly SchemaGenerator _defaultSchemaGenerator;

    public CustomSchemaGenerator(
        SchemaGeneratorOptions generatorOptions,
        IDataContractResolver dataContractResolver)
    {
        _defaultSchemaGenerator = new SchemaGenerator(generatorOptions, dataContractResolver);
    }

    public OpenApiSchema GenerateSchema(
        Type type,
        SchemaRepository schemaRepository,
        MemberInfo memberInfo = null,
        ParameterInfo parameterInfo = null)
    {
        var effectiveType = (type.IsConstructedGenericType && type.GetGenericTypeDefinition() == typeof(Envelope<>))
            ? type.GetGenericArguments()[0]
            : type;

        return _defaultSchemaGenerator.GenerateSchema(effectiveType, schemaRepository, memberInfo, parameterInfo);
    }
}
```

```csharp
// Startup.cs
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "Test API", Version = "v1" });
});

// Replace the default generator with your custom implementation
services.Replace(ServiceDescriptor.Transient<ISchemaGenerator, CustomSchemaGenerator>());
```

**Comment by sergiomcalzada** [comment]
Thank you for the response, I now understand why they are not overridable. I will follow the replacement approach.
