### ISSUE TITLE
Timespan handling changed - no longer creates "date-span"

### ISSUE THREAD

**Issue by OliverRC** [domaindrivendev/Swashbuckle.AspNetCore#1630]
In moving from 5.0.0-rc2 to 5.3.1 I noticed the following difference:
![image](https://user-images.githubusercontent.com/1888486/79754505-f5d3b400-8317-11ea-9875-c0ba524a40c9.png)

Looking at [JsonSerializerDataContractResolver.cs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs) it seems like there is no handling for Timespan.

Was this specifically removed to no longer handle them as "date-span" anymore?

```
        private static readonly Dictionary<Type, Tuple<DataType, string>> PrimitiveTypesAndFormats = new Dictionary<Type, Tuple<DataType, string>>
        {
            [ typeof(bool) ] = Tuple.Create(DataType.Boolean, (string)null),
            [ typeof(byte) ] = Tuple.Create(DataType.Integer, "int32"),
            [ typeof(sbyte) ] = Tuple.Create(DataType.Integer, "int32"),
            [ typeof(short) ] = Tuple.Create(DataType.Integer, "int32"),
            [ typeof(ushort) ] = Tuple.Create(DataType.Integer, "int32"),
            [ typeof(int) ] = Tuple.Create(DataType.Integer, "int32"),
            [ typeof(uint) ] = Tuple.Create(DataType.Integer, "int32"),
            [ typeof(long) ] = Tuple.Create(DataType.Integer, "int64"),
            [ typeof(ulong) ] = Tuple.Create(DataType.Integer, "int64"),
            [ typeof(float) ] = Tuple.Create(DataType.Number, "float"),
            [ typeof(double) ] = Tuple.Create(DataType.Number, "double"),
            [ typeof(decimal) ] = Tuple.Create(DataType.Number, "double"),
            [ typeof(byte[]) ] = Tuple.Create(DataType.String, "byte"),
            [ typeof(string) ] = Tuple.Create(DataType.String, (string)null),
            [ typeof(char) ] = Tuple.Create(DataType.String, (string)null),
            [ typeof(DateTime) ] = Tuple.Create(DataType.String, "date-time"),
            [ typeof(DateTimeOffset) ] = Tuple.Create(DataType.String, "date-time"),
            [ typeof(Guid) ] = Tuple.Create(DataType.String, "uuid"),
            [ typeof(Uri) ] = Tuple.Create(DataType.String, "uri")
        };
```

Seems to be at odds with previous PR's which had handling for Timespan:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1086
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1451

**Comment by domaindrivendev** [comment]
Swashbuckle supports two different serializers - `System.Text.Json (STJ)` and `Newtonsoft`. As STJ is now the default serializer that ships with ASP.NET Core, it's also the serializer that's honored by default in Swashbuckle.

Furthermore, because STJ serializes instances of `TimeSpan` to JSON objects rather than strings, Swashbuckle reflects that behavior in the generated schema description. If your application is currently serializing instances of `TimeSpan` to strings then you must still be using the Newtonsoft serializer and will therefore need to [configure Swashbuckle to honor that serializer instead of STJ](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#systemtextjson-stj-vs-newtonsoft).

Honoring STJ behavior by default was introduced in SB  `v5.0.0` and is called out as a breaking change in the [release notes for that version](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v5.0.0).

**Comment by OliverRC** [comment]
Our API is using System.Text.Json (STJ) in both instances.

In summary 5.0.0-rc2 treated Timespan's the Newtonsoft way which meant `type = string` and `format = date-span`, in contrast 5.3.1 treats Timespan as an object because this is the way STJ handles things.

Wow, I am surprised at the default serialization by STJ not supporting `Timespan` https://github.com/dotnet/runtime/issues/29932

Seems bizarre that an ISO 8601 standard for duration which Newtonsoft support but STJ does not without writing a custom converter. https://en.wikipedia.org/wiki/ISO_8601#Durations
