### ISSUE TITLE
about  IOperationFilter questions

### ISSUE THREAD

**Issue by ljzms1212** [domaindrivendev/Swashbuckle.AspNetCore#1641]
hi
i use `Swashbuckle.AspNetCore 5.3.3`:

write  this code 
```
operation.Parameters.Add(new OpenApiParameter()
                    {
                        Name = "Authorization",
                        In = ParameterLocation.Header,
                        Schema = new OpenApiSchema { Type = "string" },
                        Required = true
                    });
```
i could not get ‘Authorization’ by `Request.Headers["Authorization"]`.

but  use :

```
operation.Parameters.Add(new OpenApiParameter()
                    {
                        Name = "Authorization111",
                        In = ParameterLocation.Header,
                        Schema = new OpenApiSchema { Type = "string" },
                        Required = true
                    });
```
i can get ‘Authorization111’ by `Request.Headers["Authorization111"]`.

How can I use `Authorization` parameter?

**Comment by domaindrivendev** [comment]
[Swagger/OpenAPI](https://swagger.io/specification/), the API description specification used by Swashbuckle, provides some explicit fields for describing an API's authorization scheme and these should be used for the `Authorization` header instead of adding to the `Parameters` collection. From their docs ...

> Note: Header parameters named Accept, Content-Type and Authorization are not allowed. To describe these headers, use the corresponding OpenAPI keywords:

In your case, you'll need to define your authorization "scheme" (presumably basic auth) in your swagger configuration, and then update your operation to make that schema a "requirement" accordingly for a given operation. Something along the following lines should work:

```csharp
// Startup.cs
services.AddSwaggerGen(c =>
{
    var securitySchemeId = "basicAuth";

    // Define the scheme
    c.AddSecurityDefinition(securitySchemeId, new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.Http,
        Scheme = "basic"
    });

    // Wire-up a filter that applies the scheme to operations as needed
    c.OperationFilter<SecurityRequirementsOperationFilter>(securitySchemeId);
});
```

```csharp
// SecurityRequirementsOperationFilter.cs
internal class SecurityRequirementsOperationFilter : IOperationFilter
{
    private readonly OpenApiSecurityScheme _schemeReference;

    public SecurityRequirementsOperationFilter(string schemeId)
    {
        _schemeReference = new OpenApiSecurityScheme
        {
            Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = schemeId }
        };
    }

    public void Apply(OpenApiOperation operation, OperationFilterContext context)
    {
        if (...)
        {
            operation.Security = new List<OpenApiSecurityRequirement>
            {
                new OpenApiSecurityRequirement
                {
                    [ _schemeReference ] = new string[]{ }
                }
            };
        }
    }
}
```

Admittedly, the docs could do with more work on this topic but the following section describes the approach for wiring up an `Oauth2` scheme and might be help in explaining things a little better:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements

**Comment by ljzms1212** [comment]
My problem has been solved. Thank you very much.
