### ISSUE TITLE
Reduce size of Swashbuckle.AspNetCore.SwaggerUI.dll

### ISSUE THREAD

**Issue by vitalybibikov** [domaindrivendev/Swashbuckle.AspNetCore#1646]
Hi, I'm using SwaggerUI with Azure Functions.
So size is quite critical to reduce cold start time.

Currently, the whole app is about 13mbs, after using R2R latest feature of 3.1 core.
And SwaggerUi is around 1.7mb solely.

I'm suggesting to reduce SwaggerUI.dll size by compressing EmbeddedResources

```
  <ItemGroup>
    <EmbeddedResource Include="index.html" />
    <EmbeddedResource Include="node_modules/swagger-ui-dist/**/*" Exclude="**/*/*.map;**/*/*.json;**/*/*.md" />
  </ItemGroup>

```

For instance, usage of simple zip will reduce size by around 300%.

Example: https://github.com/vitalybibikov/azure-functions-extensions-swashbuckle/tree/dev/src/AzureFunctions.Extensions.Swashbuckle/AzureFunctions.Extensions.Swashbuckle/EmbededResources

**Comment by albertocorrales** [comment]
I have exactly the same problem. We are using AWS lambdas and Swashbuckle.AspNetCore.SwaggerUI.dll is the heaviest dll we have in our artifact

**Comment by martincostello** [comment]
Looks like with the latest build we're up to 3,989KB...

**Comment by martincostello** [comment]
With #2851, the next release will have an assembly with a size of about 2MB.

There's not much more we can do because the largest files are Swagger UI itself.

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/1439341/44f0d0a4-ce57-4fc8-9b43-633b9ad51a4d)


If you are size constrained, you should ship your own documentation page that references Swagger UI from a CDN ([here's an example](https://github.com/martincostello/adventofcode/blob/7deaa7bcd356702ddf1a5ce1cd8fa516b1f912c0/src/AdventOfCode.Site/wwwroot/swagger-ui/index.html)).

**Comment by martincostello** [comment]
Thanks to #3399 from @stratosblue, as of [9.0.2](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v9.0.2), the DLL size is now down to ~700KB.

| **TFM** | **9.0.1 Size** | **9.0.2 Size** | **Ratio** |
|:--------|:---------------|:---------------|:----------|
| net8.0  | 2326016        | 704000         | 0.303     |
| net9.0  | 2333184        | 710656         | 0.304     |
