### ISSUE TITLE
Generic type parameters

### ISSUE THREAD

**Issue by Slacquer** [domaindrivendev/Swashbuckle.AspNetCore#165]
It seems that swashbuckle does not produce any output for xml comments when at least one of the input parameters for an action is a generic type param.  IE:

```
    /// <summary>
    ///     Gets a [TResource] resource by using its Id
    /// </summary>
    /// <remarks>
    ///     No side-effects
    /// </remarks>
    /// <param name="id">The [TResource] resource id</param>
    /// <returns>IActionResult</returns>
    /// <response code="204">The [TResource] resource was not found</response>
    [HttpGet("{id}", Name = "[controller]-GetResourceById")]
    public IActionResult GetResourceById(TId id)
    {
    }
```

![image](https://cloud.githubusercontent.com/assets/20741093/18176879/366ad454-703d-11e6-8cdb-13e98c126da3.png)

Note the TId, however when using the following everything works as expected:

```
    /// <summary>
    ///     Gets a [TResource] resource by using its Id
    /// </summary>
    /// <remarks>
    ///     No side-effects
    /// </remarks>
    /// <param name="id">The [TResource] resource id</param>
    /// <returns>IActionResult</returns>
    /// <response code="204">The [TResource] resource was not found</response>
    [HttpGet("{id}", Name = "[controller]-GetResourceById")]
    public IActionResult GetResourceById(Guid id)
    {
    }
```

![image](https://cloud.githubusercontent.com/assets/20741093/18176905/553f1908-703d-11e6-9b72-1d70e4678550.png)

I am wondering if this is a bug?

**Comment by Slacquer** [comment]
Also note that if the ID is of type OBJECT then it works just fine too.

**Comment by domaindrivendev** [comment]
@Slacquer - can you elaborate a little on your setup? I'm assuming you have some base controller that defines a set of CRUD actions for a generic resource and then a concrete Addresses controller that inherits it. Something along the following lines?

    [Route("addresses")]
    public class AddressesController : GenericResourceController<Addresss>

The behavior you're seeing is not a bug. Swashbuckle does not support the concept of inheriting XML comments from a base controller and this isn't something I plan on adding.

However, I can suggest an alternative that would allow you

**Comment by domaindrivendev** [comment]
So, after a little more investigation, I don't consider this to be a bug.

In addition to the additional complexity required to support it, I don't think it makes sense for Swashbuckle to inherit descriptions from abstract methods. Such descriptions will inevitably be unsuitable for describing a concrete action because there's not enough information to provide a complete picture. For example, it seems pretty odd to display [TResource] in place of the concrete resource name in the swagger-ui sample you've shown above.

If your API implementation depends heavily on a generic base controller, then I would suggest an alternative to XML comments that might produce some more complete documentation. It involves a simple Operation Filter (see readme) that you can wire up to set the operation summary and parameter descriptions, including the specific resource name in each case. I've provided an example Website to demonstrate that you can check out:

https://github.com/domaindrivendev/Ahoy/blob/master/test/WebSites/GenericControllers/Swagger/ApplySummariesOperationFilter.cs
