### ISSUE TITLE
Remove {documentName} from route

### ISSUE THREAD

**Issue by cesarbmx** [domaindrivendev/Swashbuckle.AspNetCore#1663]
I simply want my swagger.json endpoint without `v1` showing in the url.
This `https://localhost:44310/swagger.json` instead of this `https://localhost:44310/v1/swagger.json`

Is it possible?

**Comment by FearNotDaniel** [comment]
I think the authors have good reason not to include this feature, given that [API versioning](https://restfulapi.net/versioning/) is important  to the long-term maintainability of both the API and consuming apps. That's probably why the [configuration helpfile](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#change-the-path-for-swagger-json-endpoints) is explicit about requiring `{documentname}` in the path.

There's a simple workaround, however: if you absolutely need this, e.g. to offer a permalink for the "current version", or just because it looks prettier, you could always add a [rewrite rule](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/url-rewriting?view=aspnetcore-3.1) to your app that would silently return the response from the configured url to users requesting your chosen path.

**Comment by domaindrivendev** [comment]
I would provide the same response as @FearNotDaniel
