### ISSUE TITLE
Convert XML document comment to Markdown

### ISSUE THREAD

**Issue by foriequal0** [domaindrivendev/Swashbuckle.AspNetCore#1670]
Hi! I wrote a converter that converts XML document comments to Markdown.
It was originally written for NSwag, but I want to graft it to here too.

This is the code:
https://github.com/foriequal0/Namotion.Reflection/tree/markdown/src/Namotion.Reflection/Markdown

And this is the tests:
https://github.com/foriequal0/Namotion.Reflection/blob/markdown/src/Namotion.Reflection.Tests/XmlDocsExtensionsMarkdownTests.cs

I want to hear your opinion and contribution guides before grafting it to here

**Comment by domaindrivendev** [comment]
By design, Swashbuckle supports a very small subset of the standard XML Comments tags - specifically `<summary/>, <remarks/>, <param/> and <example/>`. The goal in doing this was to provide a convenient way for API authors to provide multiline, _yet simple_ textual descriptions for API operations, parameters, payloads and responses. I don't believe piggybacking onto XML Comments, which are actually intended for an internal audience (as opposed to exernal) is the best approach but it sure is convenient, and so I've continued to support it, but as I said for _simple_ descriptions only.

The code in that area is already complex and at this point I don't want to increase that complexity any further by trying to support the many other tags used for XML-comment based documentation. As this feature is a good fit for the filter-style extensibility options provided by Swashbuckle (in fact, this is exactly how the current XML comments support is implemented), I think it may be a good idea for someone in the community to create a separate "add-on" project (e.g. `Swashbuckle.RichXmlComments`) that incorporates XML-comments with a much richer level of support for the various tags available. Once created, I'd be more than happy to include it as a community link in the readme.
