### ISSUE TITLE
XML comments <example> not working for string enum's

### ISSUE THREAD

**Issue by buzzers** [domaindrivendev/Swashbuckle.AspNetCore#1698]
I'm use version 5.4.1. XML comments <example> not working for string enum's, e.g.:

```csharp
public class DeviceRegisterRequest
{
    /// <example>iOS</example>
    [Required]
    public DeviceType Type { get; set; }
}
```

then in the generated JSON:

```json
{
    "DeviceRegisterRequest":{
        "required":[
            "type"
        ],
        "type":"object",
        "properties":{
            "type":{
                "$ref":"#/components/schemas/DeviceType"
            }
        },
        "additionalProperties":false
    }
}
```

I don't know if the reason is the same as #1164.

**Comment by domaindrivendev** [comment]
By default, Swashbuckle generates "enum" property schema's as "reference" schemas - i.e. the actual definition is placed in the `#/components/schemas` path and simply referenced from the property definition, as shown above. Depending on how your Swagger.JSON is being consumed, this can have benefits and downsides.

You're seeing one of the downsides - because the actual definition is centralized/shared, it can't include contextual metadata like the example for a given property of that type. However, you can apply either one of the following config settings to get around this:

1. `UseInlineDefinitionsForEnums()`
2. `UseAllOfToExtendReferenceSchemas()`

NOTE: Both of these will alter the Swagger/OpenAPI JSON that's generated by Swashbuckle. If you're only using Swashbuckle for the Swagger UI, then this shouldn't cause any issue and you should see the example text documented accordingly. However, if you have other consumers of the Swagger / OpenAPI JSON (e.g. client code generators etc.), then you'll want to make sure they're still working as expected after the change.

**Comment by buzzers** [comment]
UseInlineDefinitionsForEnums works for me, thanks.
But I'm having another problem, the Dictionary type can't set the examples, 
is there a working solution?

**Comment by domaindrivendev** [comment]
Only simple primitive types are supported at the moment. For complex types you would need to look at custom schema filters (see readme)

**Comment by nicostubi** [comment]
> You're seeing one of the downsides - because the actual definition is centralized/shared, it can't include contextual metadata like the example for a given property of that type. However, you can apply either one of the following config settings to get around this:
> 
> 1. `UseInlineDefinitionsForEnums()`

When calling that method, the example is correct.

However, I lose the advantage of having enums appearing in schemas. 

When removing UseInlineDefinitionsForEnums(), the example of enum (/// <example>example</example>) is not taken into account anymore.

Instead, it is just the first value of the enum that is displayed.

Any way to both keep enums in schema and to customize the example of the enum?
I'm using v.5.6.3
