### ISSUE TITLE
Conflicting method/path combination when providing a Route Name and a Route attribute

### ISSUE THREAD

**Issue by daleclements** [domaindrivendev/Swashbuckle.AspNetCore#1713]
Using Swashbuckle.AspNetCore 5.4.1 in a .Net Core 3.1 API

I have a controller:
```
[Route("api/v1/[controller]")]
[ApiController]
public class CalculationsController : ControllerBase
```

which has an action:
```
[HttpGet]
public ActionResult<IEnumerable<String>> getCalculationsList()
```

and if I have another action:
```
[Route("{calculationId}")]
[HttpGet(Name = nameof(getCalculation))]
public ActionResult<CalculationResource> getCalculation(string calculationId)
```

then I get
```
NotSupportedException: Conflicting method/path combination "GET api/v1/Calculations" for actions - CalculationServiceAPI.Controllers.CalculationsController.getCalculationsList (CalculationServiceAPI),CalculationServiceAPI.Controllers.CalculationsController.getCalculation (CalculationServiceAPI). Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround
```

but clearly they are different routes, right? I'm not trying to differentiate the actions by query parameters or headers or anything like that.

It seems to only be this specific combination of decorators that breaks. The following all work:

Route and Method with no Name works.
```
[Route("{calculationId}")]
[HttpGet]
```
Route inside the method attribute, plus Name works.
```
[HttpGet("{calculationId}", Name = nameof(getCalculation))]
```

**Comment by domaindrivendev** [comment]
This is an ASP.NET Core routing nuance that's independent of Swashbuckle. In fact, the following attribute combination is not doing what you think:

```csharp
[Route("{calculationId}")]
[HttpGet(Name = nameof(getCalculation))]
public ActionResult<CalculationResource> getCalculation(string calculationId)
```

Rather than exposing a single route, this will actually cause ASP.NET Core to expose _two separate_ routes that are both bound to the same `getCalculation` action.

- `GET api/v1/calculations/{calculationId}`
- `GET api/v1/calculations`

To demonstrate this, simply navigate to the second one of these in your browser, and ASP.NET Core (not Swashbuckle) will raise the following exception:

> AmbiguousMatchException: The request matched multiple endpoints. Matches:

This is because your other action `getCalculationsList` is already bound to `GET /api/v1/calculations` and now, with the specific attribute combination on `getCalculation`, you've inadvertantly bound that to the same route as well.

You'd have to get clarification from the ASP.NET Core team, but I suspect the explicit route name causes ASP.NET Core to create separate routes instead of combining the attributes into a single route, and this is why this doesn't happen when the `Name` is omitted.

**Comment by daleclements** [comment]
That's so strange. Thanks for the explanation!
