### ISSUE TITLE
date format not followed in example

### ISSUE THREAD

**Issue by ilengyel** [domaindrivendev/Swashbuckle.AspNetCore#1716]
Swashbuckle version: 5.5.0

specifying data type date still uses date-time format when displaying example.

```csharp
/// <summary>
/// Start date in format YYYY-MM-DD
/// </summary>
/// <example>2020-05-12</example>
[DataType(DataType.Date)]
public DateTime? From { get; set; }
```
produces the following schema
```json
"schema": {
    "type": "string",
    "description": "Start date in format YYYY-MM-DD",
    "format": "date",
    "example": "2020-05-12T00:00:00.0000000"
}
```
expecting the example to be "2020-05-12"

**Comment by ilengyel** [comment]
In Swashbuckle version 5.4.1 it appears that it was incorrectly using the system's locale to format the date string. In my case it was `"12/05/2020 12:00:00 AM"`.

**Comment by wjrogers** [comment]
I noticed the same thing, so I dug into it a bit. I think the root cause is that Swashbuckle outputs the example as an `OpenApiDate`, which eventually [gets serialized as a native JSON date](https://github.com/microsoft/OpenAPI.NET/blob/cb3c26b6f46e3ca17247e18aa6590606ba0a410a/src/Microsoft.OpenApi/Writers/OpenApiWriterBase.cs#L185-L188) in `Microsoft.OpenApi.Writers.OpenApiWriterBase`. I'm working around it with a parameter filter that replaces affected examples:

```csharp
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Example.Filters
{
    /// <summary>
    /// Formats examples for OpenApi "date" format strings as <c>yyyy-MM-dd</c>.
    /// </summary>
    public class DateExampleParameterFilter : IParameterFilter
    {
        public void Apply(OpenApiParameter parameter, ParameterFilterContext context)
        {
            // strongly-typed example values get serialized as JSON in ISO 8601 format, with undesired precision,
            // so replace them with a string
            if (parameter.Schema.Format == "date" &&
                parameter.Schema.Example is OpenApiDate date)
                parameter.Schema.Example = new OpenApiString(date.Value.ToString("yyyy-MM-dd"));
        }
    }
}
```

**Comment by wjrogers** [comment]
I figured out today that you can accomplish the same thing with a schema filter, but you have to make sure you add the filter _after_ calling `EnableAnnotations()` if you are using Swashbuckle.AspNetCore.Annotations to set the format. This has the advantage that it works for model properties, too!

```csharp
using Microsoft.OpenApi.Any;
using Microsoft.OpenApi.Models;
using Swashbuckle.AspNetCore.SwaggerGen;

namespace Example.Filters
{
    /// <summary>
    /// Formats examples for OpenApi "date" format strings as <c>yyyy-MM-dd</c>.
    /// </summary>
    public class DateExampleSchemaFilter : ISchemaFilter
    {
        public void Apply(OpenApiSchema schema, SchemaFilterContext context)
        {
            // strongly-typed example values get serialized as JSON in ISO 8601 format, with undesired precision,
            // so replace them with a string
            if (schema.Format == "date" &&
                schema.Example is OpenApiDate date)
                schema.Example = new OpenApiString(date.Value.ToString("yyyy-MM-dd"));
        }
    }
}
```

**Comment by domaindrivendev** [comment]
If you don't provide an explicit example, e.g. using the approach described by @wjrogers, then the [swagger-ui](https://github.com/swagger-api/swagger-ui) generates it's own example value. If you're not happy with the default value it generates then you should post an issue to that repo instead of SB. If you need to have control over those sample values, use the approach described above.

**Comment by arisliang** [comment]
I tried to add `c.ParameterFilter<DateExampleParameterFilter>();` (or as SchemaFilter) in `AddSwaggerGen` i suppose, but it's not working, it's still showing the date example as 2021-01-01T00:00:00.0000000 when I put 2021-01-01 in the example xml.
