### ISSUE TITLE
[FromForm] attributed model is not showed in swagger.json.components.schemas

### ISSUE THREAD

**Issue by Moskvinr** [domaindrivendev/Swashbuckle.AspNetCore#1724]
I need to read properties from components.schemas, but   **[FromForm]FormExample form** is not recognized and not showed in schema. 
V 5.5.0

**Comment by domaindrivendev** [comment]
Form schema's are defined inline (as opposed to being a reference to shared schema in `components.schemas`) and are therefore never written to components.schema.

**Comment by max-arshinov** [comment]
@domaindrivendev we also noticed that Document Filters are ignored for schemas that are defined inline. Is there a way to modify inline schemas?

**Comment by max-arshinov** [comment]
@domaindrivendev any updates?

**Comment by domaindrivendev** [comment]
Due to the way in which form fields are surfaced by `ApiExplorer` (the API metadata layer that ships with ASP.NET Core), form Schema's need to be treated as a special case in Swashbuckle, and are generated in a slightly different way to to regular payload schemas.

As a result, they are a) always generated inline within the relevent `Operation` definition rather `components.schemas` and b) never passed through the schema filters.

If you need to inspect those schemas, look in the relevent `Operation` definition instead. If you need to modify, use an `IOperationFilter` instead of an `ISchemaFilter`.
