### ISSUE TITLE
IOptions<SwaggerOptions> SerializeAsV2 always false in IOperationFilter

### ISSUE THREAD

**Issue by mattfrear** [domaindrivendev/Swashbuckle.AspNetCore#1729]
I have an IOperationFilter which receives an `IOptions<SwaggerOptions>` injected into the constructor.

This is so I can find out the value of `SerializeAsV2`.

In Swashbuckle.AspNetCore 5.0.0 and 5.1.0 this works fine. But with 5.5.1 (and any version greater than 5.1.0) the SwaggerOptions which gets injected in always has `SerializeAsV2 = false`.

Steps to reproduce (.NET Core 3.0 app, might also happen in .NET Core 2, I haven't tried):
```csharp
            app.UseSwagger(
                c => c.SerializeAsV2 = true
            );
```

In my IOperationFilter:
```csharp
        public ExamplesOperationFilter(IOptions<SwaggerOptions> options)
        {
            var serializeAsV2 = options.Value.SerializeAsV2; // true in 5.0.0 and 5.1.0, false in other versions
```

Related issue: https://github.com/mattfrear/Swashbuckle.AspNetCore.Filters/issues/115

**Comment by brendan-src** [comment]
Hey @mattfrear!

Unless I'm missing something, it looks like `SwaggerOptions` is never configured. So, when options.Value is called, a new one is constructed which defaults to SerializeAsV2 = false.

E.g., Adding this to the `Basic` project results in the expected value showing up.
```csharp
            services.Configure<SwaggerOptions>(c => c.SerializeAsV2 = true);
```

**Comment by mattfrear** [comment]
Hi @brendan-src,

Thanks a million, your workaround works!

I'll leave this issue open though as I think it's a defect, having to repeat the `SerializeAsV2 = true`.

**Comment by domaindrivendev** [comment]
@mattfrear - Swashbuckle offers two alternative methods for configuring the Swagger middleware.

1. Passing a setup action to the `UseSwagger` method
2. Using the `IOptions` infrastructure.

The first case is simpler because everything can be done with a single call. However, it doesn't leverage (in fact it can't) the `IOptions` infrastructure and therefore cannot be used to configure an instance that's _persisted_ in the DI container.

For the usecase where you want to look at options in a filter, you MUST use the second option.

**Comment by mattfrear** [comment]
Thanks for the reply. 

It is odd that it used to work with 5.0.0 and 5.1.0 but not later versions. But that's cool, I have my workaround. No reply needed.
