### ISSUE TITLE
Specifying Name for HttpDelete leads to missed swagger.json

### ISSUE THREAD

**Issue by ygavrishov** [domaindrivendev/Swashbuckle.AspNetCore#1735]
Hi! I need to add the OperationId attribute to swagger.json. That's way I added Name property for all HTTP methods in my ASP.NET Core API projects. It works perfectly for POST and GET methods but for HttpDelete it leads to missed swagger.json. My code:

``` csharp
[HttpDelete(Name = "DeleteMyItem")]
[Route("{itemId}")]
public async Task<IActionResult> RemoveItem(string itemId)
{
	return Ok();
}
```

The result:

> Failed to load API definition.
> Fetch error. undefined /swagger/v1/swagger.json

Please advice.

**Comment by domaindrivendev** [comment]
I believe this is a dup of #1713.

Long story short, when you use the above combination of `HttpDelete` and `Route`  attributes, ASP.NET Core does NOT behave the way you think. Rather than exposing a single route, this will actually cause ASP.NET Core to expose two separate routes that are both bound to the same `RemoveItem` action, and this in turn causes Swashbuckle to error because of a route conflict. To fix the issue, just combine the attributes as follows. For more details, read the related issue:

```csharp
[HttpDelete("{itemId}", Name = "DeleteMyItem")]
public async Task<IActionResult> RemoveItem(string itemId)
{
	return Ok();
}
```

**Comment by ygavrishov** [comment]
@domaindrivendev, thanks, you fully solved my problem!
