### ISSUE TITLE
Is there a way to override parameter generation?

### ISSUE THREAD

**Issue by max-arshinov** [domaindrivendev/Swashbuckle.AspNetCore#1751]
I need to override schema in a way that is very similar to one that is defined in the example https://github.com/domaindrivendev/Swashbuckle.AspNetCore#override-schema-for-specific-types
```
// PhoneNumber.cs
public class PhoneNumber
{
    public string CountryCode { get; set; }

    public string AreaCode { get; set; }

    public string SubscriberId { get; set; }
}

// Startup.cs
services.AddSwaggerGen(c =>
{
    ...
    c.MapType<PhoneNumber>(() => new OpenApiSchema { Type = "string" });
};
```

This works fine for the schema but not for parameters. When I try to use this type as an argument of the controller
`public IActionResult SomeMethod([FromQuery]PhoneNumber number)`
SwaggerUI still shows me the parameter as an object. 

I want to have a definition that is exactly the same with
`public IActionResult SomeMethod([FromQuery]string number)`

Is there a way to override parameter generation logic?

**Comment by domaindrivendev** [comment]
Closing as this is really a dup of #309.

With that said, let me answer with a question: Independently of Swashbuckle - how are you telling ASP.NET Core's model binder how to deserialize a string value from the request into the complex `PhoneNumber` object? I'm assuming you're using a custom model binder?

As it turns out this is _not_ the recommended approach. Instead, [MS recommends](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-5.0#model-binding-review) a custom `TypeConverter` for simple string => type conversions:

>  We recommended you create a type converter if you have a simple string -> SomeType mapping that doesn't require external resources

If you don't go with this recommendation then `ApiExplorer`, ASP.NET Core's built-in API metadata provider that's heavily used by Swashbuckle gets it's head into a spin, and this manifests itself as the exact issue you're seeing.

However, if you do go with the recommended approach then everything works just fine and you don't even need to add the explicit `MapType` in your SB config. Here's what this would look like for you:

```csharp
// PhoneNumberConverter.cs
public  class PhoneNumberConverter : TypeConverter
{
    public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType)
    {
        return (sourceType == typeof(string));
    }

    public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value)
    {
        var inputString = value.ToString();
        return new PhoneNumber
        {
            ...
        };
    }
}

// Startup.cs
public void ConfigureServices(IServiceCollection services)
{
    ...

    // Assign TypeConverter to PhoneNumber so it can be deserialized from a string
    TypeDescriptor.AddAttributes(typeof(PhoneNumber), new TypeConverterAttribute(typeof(PhoneNumberConverter)));
}
```

**Comment by ngocketit** [comment]
This doesn't answer the question. Does it mean there is no way to achieve what the OP is asking with Swashbuckle?
