### ISSUE TITLE
<see> documentation comments are mishandled

### ISSUE THREAD

**Issue by IanKemp** [domaindrivendev/Swashbuckle.AspNetCore#1753]
Using latest version (5.5.1).

* `<see cref="PropertyName" />` in code is written as the fully-qualified `<see cref="P:Fully.Qualified.Namespace.Of.PropertyName" />` in the documentation XML, which is rendered as-is (excluding the leading "P:") into the outputted HTML i.e. "Fully.Qualified.Namespace.Of.PropertyName"
* `<see langword="x" />` is not rendered into outputted HTML at all
* `<see langword="x">x</see>` is rendered, but without the curly braces that are inserted around `<c></c>` elements (i.e. "false" instead of "{false}")

**Comment by domaindrivendev** [comment]
By design, Swashbuckle only supports a very small subset of the standard XML Comments tags - specifically `<summary>`, `<remarks>`, `<param>` and `<example>`. The goal is to provide a simple and convenient way to provide multi-line descriptions for operations, parameters, responses and schemas. The intention has never been to support _all_ of the tags and map to HTML/markdown accordingly, and frankly that's a level of complexity that I'm not willing to take on.

What I might suggest, if someone was willing, would be to create a separate project that extends Swashbuckle using the various filters and offers a much richer integration with the XML Comments tags.
