### ISSUE TITLE
Swagger UI shows empty page - How to fix?

### ISSUE THREAD

**Issue by SetTrend** [domaindrivendev/Swashbuckle.AspNetCore#1756]
_Stranded here after unsuccessfully publishing this issue at [StackOverflow](https://stackoverflow.com/questions/62983271/swashbuckle-aspnet-core-swagger-ui-shows-empty-page-how-to-fix) and [swagger-api/swagger-ui](/swagger-api/swagger-ui/issues/6262):_
<br/>

I added Swashbuckle.AspNet.Core to my repository and initialized everything using defaults.

Although I can see JSON output from `/swagger/v1/swagger.json` opening `/swagger/index.html` just yields an empty page.

Why?

<br/>

[![enter image description here][1]][1]

<br/>
<hr/>

### Here's my code

```c#
public void ConfigureServices(IServiceCollection services)
{
  services
    .AddSwaggerGen()
    .AddControllers()
    ;
}

// This method gets called by the runtime once. Use this method to configure the HTTP request pipeline.
public void Configure(IApplicationBuilder app, IWebHostEnvironment env, Options options)
{
  if (env.IsDevelopment()) app.UseDeveloperExceptionPage();

  app
    .UseHttpsRedirection()
    .UseRouting()
    .UseAuthorization()
    .UseEndpoints(endpoints => endpoints.MapControllers())
    .UseSwagger()
    ;

  if (env.IsDevelopment()) app.UseSwaggerUI();
}
```

  [1]: https://i.stack.imgur.com/AUHZL.png

**Comment by shawty** [comment]
Same problem here

Latest stable version of the NuGet package installed

![image](https://user-images.githubusercontent.com/1876454/88951131-8150cf80-d28d-11ea-821a-529b7b2b8495.png)

Project is a standard ASP.Net core 3.1 app, straight off the template with no changes:

![image](https://user-images.githubusercontent.com/1876454/88951261-a47b7f00-d28d-11ea-89b4-40ef129bd44a.png)

I've done a standard Swagger setup in the startup class, with no changes

![image](https://user-images.githubusercontent.com/1876454/88951324-b9f0a900-d28d-11ea-81d1-6c864a77de1d.png)

The API works fine

![image](https://user-images.githubusercontent.com/1876454/88951379-cd9c0f80-d28d-11ea-8087-6de29c222dad.png)

The swagger doc is generated without any issues

![image](https://user-images.githubusercontent.com/1876454/88951442-e3a9d000-d28d-11ea-87f5-d5d58200e3e3.png)

Trying to access the UI, results in a blank page

![image](https://user-images.githubusercontent.com/1876454/88951480-f4f2dc80-d28d-11ea-8ade-56158d690b26.png)

Delving into the developer console shows us this : 

![image](https://user-images.githubusercontent.com/1876454/88951524-076d1600-d28e-11ea-82ca-0b3513a3cfc6.png)

The code dies while trying to execute a loop enumerating the urls property on configObject

![image](https://user-images.githubusercontent.com/1876454/88951664-384d4b00-d28e-11ea-8625-e217a663a38f.png)

If we break point just before the error, we see that configObject has no such property present on it

![image](https://user-images.githubusercontent.com/1876454/88951777-5915a080-d28e-11ea-8be5-e61a9511c682.png)

**Comment by shawty** [comment]
Update:

If we change our code in Startup.cs so that it reads as follows

![image](https://user-images.githubusercontent.com/1876454/88959811-810b0100-d29a-11ea-8845-01f4e3284471.png)

Note the addition of the new line (Underlined in red)

The UI then changes to show the following

![image](https://user-images.githubusercontent.com/1876454/88959891-9da73900-d29a-11ea-847f-c522d9fdbca8.png)

The dev tools then show the following failure within "swagger-ui" itself

![image](https://user-images.githubusercontent.com/1876454/88959993-c16a7f00-d29a-11ea-99c0-981c75e57a46.png)

My guess here would be because there are no actual URL's in the URL collection of the config object.

**Comment by shawty** [comment]
Update 2:

It appears that the "c.SwaggerEndpoint" call is NOT OPTIONAL and MUST BE SPECIFIED

![image](https://user-images.githubusercontent.com/1876454/88960563-9e8c9a80-d29b-11ea-9309-21d9c821b47b.png)

None of the documentation I've read tells the user this, and so it's quite feasible that like myself and @SetTrend that we would leave this out.

As for the reason I had that call commented out in my screen shots above, I was actually trying to solve A 404 error with "/swagger" not being found when I landed here.

I've since figured out that the cause of my problem was bogus advice from the MS-Docs site which suggests setting "c.RoutePrefix" to String.Empty.

@SetTrend for now you can resolve your problem, simply by specifying your "c.SwaggerEndpoint" call in the same manner I do in the above image.  This add's a single swagger JSON document object to the UI for you to use.

**Comment by SetTrend** [comment]
Excellent research, @shawty!

Thanks for sharing your findings here!

Would you suggest this issue to remain open until things are getting amended or would you suggest to close?

**Comment by shawty** [comment]
I'll leave that descision to you @SetTrend :-)

My gut feeling here, is that it's not actually an issue, more of a case of the documentation needing to specifically say "You MUST do this"

and doc stuff like this is IMHO not an error.

However if it's left open then something which has the potential to be a common source of frustration, esp to new users will at least have a target with solution if it is left open, to help them.

**Comment by SetTrend** [comment]
Hmmm ... I have a feeling that Swashbuckle should function properly right from the beginning. Instead of having everyone enter the same default line over and over again, the setup should set a default route that may be overwritten.

If that's the way the repository owner would want to go with, I'd gladly provide a pull request. I supposed it would be a snap to implement this?

**Comment by shawty** [comment]
@SetTrend I've not looked deep enough into the code to be honest, it only bit me because I was trying to solve a micro-services rest boundary problem on one of my clients projects :-)  but I guess it wouldn't be a huge ache, my best guess without looking at the code would be to copy the default generated URL into the config object in .NET at some appropriate point.

PS: I've answered your Stack Overflow post too :-)

**Comment by SetTrend** [comment]
I now created a [pull-request](../pull/1765) to solve this issue. If you like it, please up-vote 😏
