### ISSUE TITLE
SwaggerSchema ReadOnly doesn't work for object properties

### ISSUE THREAD

**Issue by skaman** [domaindrivendev/Swashbuckle.AspNetCore#1763]
The SwaggerSchema readOnly property doesn't look to work correctly with custom objects.

As example here my entity:
```
public class Brand : BaseEntity
{
    public string Name { get; set; }
        
    [SwaggerSchema(ReadOnly = true)]
    public Guid LogoId { get; set; }
        
    [SwaggerSchema(ReadOnly = true)]
    public virtual Blob Logo { get; set; }
}
```

This is the expected result:
```
"Brand": {
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "nullable": true
        },
        "logoId": {
            "type": "string",
            "format": "uuid",
            "readOnly": true
        },
        "logo": {
            "$ref": "#/components/schemas/Blob",
            "readOnly": true
        }
    },
    "additionalProperties": false
}
```

This is the actual result:
```
"Brand": {
    "type": "object",
    "properties": {
        "name": {
            "type": "string",
            "nullable": true
        },
        "logoId": {
            "type": "string",
            "format": "uuid",
            "readOnly": true
        },
        "logo": {
            "$ref": "#/components/schemas/Blob"
        }
    },
    "additionalProperties": false
}
```

The "readOnly": true is missing in the "logo" field

**Comment by domaindrivendev** [comment]
Your "expected" result is actually incorrect Swagger JSON. This is because the `$ref` keyword SHOULD NOT be paired with other schema members (`nullable`, `readOnly` etc.). See [here](https://swagger.io/docs/specification/using-ref/) for more details on how the `$ref` keyword should be used - the following line being the most relevant here:

> Any members other than $ref in a JSON Reference object are ignored

So, with that said, if you want to add "contextual" metadata such as the `readOnly` flag then you need to "extend" the referenced schema using the `allOf` keyword. In other words, your "expected" JSON for the `logo` property in your example, should in fact look like this:

```
"logo": {
  "allOf": [
    { "$ref": "#/components/schemas/Blob" }
  ],
  "readOnly": true
}
```

Now, to have Swashbuckle generate this type of Swagger JSON, simply apply the `UseAllOfToExtendReferencedSchema` setting.

**Comment by skaman** [comment]
It work great. Really thanks
