### ISSUE TITLE
Need a way to represent `null` inside XML comments <example> tag.

### ISSUE THREAD

**Issue by harmonic7** [domaindrivendev/Swashbuckle.AspNetCore#1768]
I can't seem to find a way to return an example value of `null` for a string property. I've been trying to this in XML comments, obviously this won't work.

```csharp
public class Product
{
    /// <example>null</example>
    public string Name { get; set; }
}
```

I've also tried:
```csharp
public class Product
{
    /// <example><null/></example>
    public string Name { get; set; }
}
```

And:
```csharp
public class Product
{
    /// <example xsi:nil="true"/>
    public string Name { get; set; }
}
```

but none of these end up in getting a `null` value into the example swagger documentation.

**Comment by domaindrivendev** [comment]
With the above merge, the example is now treated as literal JSON. This means null values and even array values can be provided. Here's some examples:

Boolean
```xml
<example>true</example>
```
String
```xml
<example>"foobar"</example>
```
Number
```xml
<example>123</example>
```
Null
```xml
<example>null</example>
```
Array
```xml
<example>[ 1, 2, 3 ]</example>
```

__NOTE:__ This does however mean that string values MUST include the enclosing double quotes to be correctly interpreted and added to the generated Swagger / OpenAPi document. This is a breakiing change and will be communicated with the 6.0.0 release notes.

In lieue of that release, you can test out this functionlity by downloding the latest 6.0.0 preview from Myget.org

**Comment by domaindrivendev** [comment]
Closing in favor of #1866

**Comment by AchoArnold** [comment]
Hey @domaindrivendev  I just tried on version 6.14,  `<example>null</example>` still renders as "null" in the interface.

**Comment by Dunnymeister** [comment]
I'm experiencing the same thing, there appears to be a regression at some point between 6.0.0 and 6.14.

**Comment by Dunnymeister** [comment]
Through a process of elimination I've determined that this broke in 6.0.1. The only notable change was the update to swagger-ui-dist from 3.40.0 to 3.42.0.

**Comment by Dunnymeister** [comment]
I've determined the issue lies with swagger-ui and started occurring when pull request https://github.com/swagger-api/swagger-ui/pull/6872/ was merged in.

The file fs.js was updated to return strings "if they don't need any parsing", short circuiting the JSON parsing of string-typed null values. I'll raise this upstream.

**Comment by Dunnymeister** [comment]
While implementing a solution in a PR I've come to the realisation this only worked because of an edge case in the first place.

Swashbuckle was passing the string "null" to swagger-ui, and it happened to do json parsing on this and it ended up resolving to null. Once they corrected this behaviour the side-effect no longer worked.

I've fixed this in Swashbuckle.AspNetCore.SwaggerGen and will make a PR tomorrow once I've been able to test it.
