### ISSUE TITLE
IFormFile is not treated as a File Upload operation in Swagger UI for Swagger 2.0

### ISSUE THREAD

**Issue by Cloudmersive** [domaindrivendev/Swashbuckle.AspNetCore#1769]
Example Web API function definition:

```
        [HttpPost("mssql/bak/to/csv")]
        public FileStreamResult MssqlBakToCSV([FromBody] IFormFile inputFile, [FromHeader] string tableName)
        {
        }
```

Startup.cs is configured as:

```
            app.UseSwagger(c =>
            {
                c.SerializeAsV2 = true;
                
            });

            app.UseSwaggerUI(c =>
            {
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "Data Integration API V1");
            });
```

Expected: inputFile appears in Swagger UI as a File Upload box

Actual: Appears as a textbox

**Comment by domaindrivendev** [comment]
As of `v5.0.0`, Swashbuckle made the jump to OpenAPI V3. As part of this change, it pulls in the [OpenAPI.NET](https://github.com/microsoft/OpenAPI.NET) library and works exclusively with it's `V3` object model.

Initially, I had no intention of supporting both formats. However it turned out that the OpenAPI.NET library has a useful feature for deserializing it's V3 object model to V2 JSON and/or YAML. So, when you use the `SerializeAsV2` flag, Swashbuckle is simply using that feature under the hood.

This has a couple of implications here:

1) As the file upload functionality works for V3, it seems this is actually a bug with the OpenAPI.NET library's serialize-as-v2 feature. So, if you want it fixed, you'll need to create an issue there.

2) I'll keep this issue open for tracking but don't intend looking into it any further. I suggest you upgrade to V3 of the spec if at all possible. If this isn't possible, then you'll need to stick with the 4.x version of Swashbuckle.

**Comment by Cloudmersive** [comment]
OK issue has been opened on OpenAPI.NET:

https://github.com/microsoft/OpenAPI.NET/issues/509

Nobody actually uses OpenAPI V3 and it is a totally broken standard.  If you look at Swagger-Codegen it has about 10% of the languages supported on V3 as V2 and the tooling is awful.  It may be too early to have made the jump (our opinion).

If we downgrade to v4.x of Swashbuckle for ASP.NET Core will it be natively V2 and thus avoid this issue?

**Comment by darrelmiller** [comment]
Hey @Cloudmersive !   I'd love to hear more about how nobody uses OpenAPI V3 and how it is totally broken.   That would really help us as we are working on finishing OpenAPI V3.1.  In the meanwhile, I'll spend my Saturday evening going and seeing how to make FileUpload work in Swagger UI with OpenAPI V2.  We specifically made changes in V3 to help support different multi-part file formats because V2 didn't handle it well.

**Comment by Lonli-Lokli** [comment]
@Cloudmersive 
You can workaround it with setup SwaggerGenOptions:
            opts.MapType(typeof(IFormFile), () => new OpenApiSchema() { Type = "file", Format = "binary" });

**Comment by domaindrivendev** [comment]
This has been fixed upstream. You can pull in the change by adding an explicit reference to `Microsoft.OpenApi 1.2.3` or above OR upgrading `Swashbuckle to 5.6.3` or above.

**Comment by flowest** [comment]
> Swashbuckle to 5.6.3

The latest version is [5.6.0](https://www.nuget.org/packages/Swashbuckle#versions-body-tab)?
