### ISSUE TITLE
Generic Response types broken in 5.5.1

### ISSUE THREAD

**Issue by madhukar559** [domaindrivendev/Swashbuckle.AspNetCore#1803]
We are in the process of upgrading to .NET 3.1, however for this we had to upgrade swashbuckle to 5.5.1 version.
This has broken our response types.

I have configured my  application to produce 2.0 via the following flag:
`app.UseSwagger(c => c.SerializeAsV2 = true);
`

In the previous version 4.x, that we are using, the definition of a response type was generated as shown below:

`ApiResponse[ObjectOutput]
`

Our controller has the following attribute set:
`[ProducesResponseType(typeof(ApiResponse<ObjectOutput>), 200)]
`

After upgrading to 5.5.1, the output response type is generated as follows:

`ObjectOutputApiResponse
`

This will break functionality for all our customers, Is there a way we can retain the earlier behavior?

**Comment by domaindrivendev** [comment]
The new naming convention for schema's was introduced with the 5.x major version increment because the old convention was invalid (see `$ref values must be RFC3986-compliant percent-encoded URIs`).

If you want to retain the old convention, you will need to wire up a custom strategy with the `CustomSchemaIds` setting. You can base this off the old code taht ws being used to generate this value:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/v4.0.1/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/TypeExtensions.cs#L10

**Comment by madhukar559** [comment]
Thanks for the response, I have managed to generate swagger 2.0 now, however JToken type (from Newtonsoft.json) is being ignored in the generation.

A JToken type is generated with $ref:
  "customValue": { }

If the type JArray, items are generated without $ref 
 "propertyName": {
          "type": "array",
          "items": { }
        }

Is there a way to fix this?

**Comment by domaindrivendev** [comment]
That's unrelated to your original issue - would you mind closing this one and creating a new issue for it as it really helps with overall issue tracking.

**Comment by madhukar559** [comment]
Closing issue as the suggestion worked.
