### ISSUE TITLE
Incorrect interpretation of parameters with nesting in the GET method

### ISSUE THREAD

**Issue by deereeed** [domaindrivendev/Swashbuckle.AspNetCore#1833]
Considering the following example:

```csharp

    [Route("api/sample")]
    public class SampleController : ApiControllerBase
    {
        [HttpGet("get-foo")]
        public DataQueryOptions? Foo([FromQuery] DataQueryOptions? queryOptions)
        {
            return queryOptions;
        }

        public class DataQueryOptions
        {
            /// <summary> Paging settings </summary>
            [DataMember(IsRequired = false, Name = "paging")]
            [FromQuery(Name = "paging")]
            public DataQueryPaging? Paging { get; set; }
        }

        [DataContract]
        public sealed class DataQueryPaging : IDataQueryPaging
        {
            [DataMember(IsRequired = true, Name = "top")]
            [FromQuery(Name = "top")]
            [Required]
            public int Top { get; set; }

            [DataMember(IsRequired = true, Name = "skip")]
            [FromQuery(Name = "skip")]
            [Required]
            public int Skip { get; set; }

            [DataMember(IsRequired = false, Name = "count")]
            [FromQuery(Name = "count")]
            public bool? Count { get; set; }
        }
    }

 ```
SwaggerUI for this Controller:

![image](https://user-images.githubusercontent.com/6865657/93988621-9b8cc280-fd91-11ea-824a-21c050578811.png)

Expected request :
_http://localhost:5000/api/sample/get-foo?paging.top=1&paging.skip=2&paging.count=true_
Actual request:
_http://localhost:5000/api/sample/get-foo?top=1&skip=2&count=true_

So, Swashbuckle ignores nesting in parameters.

`AspNetCore : 3.1`
`Swashbuckle.AspNetCore: 5.5.1`

**Comment by domaindrivendev** [comment]
Hmmm, this is an interesting one and fundamentally I believe it's due to an upstream issue with the `ApiExplorer` component that ships with ASP.NET Core. This component surfaces metadata about all API actions in your application and Swashbuckle uses that metadata to generate Swagger / OpenAPI and ultimately power the UI. In this case, the `ApiParameterDescription.Name` property being surfaced for each parameter is incorrect, and this has the knock-on effect you're observing.

To demonstrate this, try removing all of the `[FromQuery]` attributes except the one on the top-level `queryOptions` parameter. Functionally, they're not actually neccessary and you'll get the exact same API behavior without them. This is because the nested parameters will be automatically bound to the query string by virtue of the top-level binding. When you do this, you should see the nested parameter names displayed correctly in the UI:

- `Paging.Top`
- `Paging.Skip`
- `Paging.Count`

In this case, `ApiParameterDescription.Name` is being surfaced correctly _with_ the nesting information. Of course it's defaulting to title casing, which isn't wrong because model binding is case insensitive, but it may not be how you want to display them in the UI. So, to be explicit about the casing you need to re-apply the `[FromQuery]` attributes to each nested parameter, and this is where the problem starts. Now, despite being no different functionally, the `ApiParameterDescription.Name` values that are surfaced by `ApiExplorer` are incorrect/missing the nesting information.

**Comment by domaindrivendev** [comment]
In terms of a workaround, Swashbuckle does provide a `DescribeAllParametersInCamelCase` setting. The idea being you can apply this globally rather than having all the redundant `[FromQuery]` bindings on nested parameters. Unfortunately, this trips up in this case because of the `.`. With this applied, your parameters would be displayed as follows:

- paging.Top
- paging.Skip
- paging.Count

Almost, but not quite what you're looking for.

It should be a fairly simple fix to account for this case property. I can add that now and you could go with this appoach which would be a lot quicker than waiting for an upstream fix.

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/commit/90a6382eab701ced8ed6bf4a2c60ed760fd232db

**Comment by deereeed** [comment]
@domaindrivendev Thank you for updating the package, your workaround is what I need.
Also, I reported Issue https://github.com/dotnet/aspnetcore/issues/26271 to the ASP.NET Core repo.

**Comment by domaindrivendev** [comment]
Awesome. Thanks for reporting the upstream issue 👍

**Comment by domaindrivendev** [comment]
Looks to be fixed upstream
