### ISSUE TITLE
Exception within method GetHostOrNullFromRequest in SwaggerMiddleware

### ISSUE THREAD

**Issue by mhoeper** [domaindrivendev/Swashbuckle.AspNetCore#1836]
Hi, 

I get the below exception when running Swagger 5.6.0 on our servers. Probably the load balancer set a bad or empty X-Forwarded-Host header. Can you please surround the method with try/catch and in case of exception, return null? Or, another way would be to optionally set the host in startup for swagger. 

`System.UriFormatException at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.GetHostOrNullFromRequest`

**Comment by simluk** [comment]
Hi there,

We also facing same issue and the issue is that our internal proxy adds following headers:
`
X-Forwarded-Host : <proxy-one>, <proxy-two>
X-Forwarded-Server : <server-one>, <server-two>
`
The swashbuckle code on the other hand executes following:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/1a2b824ebff66b68e00cbe6d3027a2d070476186/src/Swashbuckle.AspNetCore.Swagger/SwaggerMiddleware.cs#L72

Takes [0] element but does not split it with comma. I believe this has to be fixed to support comma separated host/server list. Let me know if I should raise PR for this because it is blocking update to new version.

Thanks,
Simonas

**Comment by simluk** [comment]
@domaindrivendev - when can we expect to have v6.0.0 released?

**Comment by mhoeper** [comment]
@simluk I forked the SwaggerMiddleware.cs and just return null in GetHostOrNullFromRequest method instead. Maybe this is a mitigation that works for you, too, until the fix is released.

**Comment by domaindrivendev** [comment]
@simluk. It will likely be a week or two but you can pull down preview packages built from latest master from myget.org in the meantime.

See https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore

**Comment by simluk** [comment]
@domaindrivendev when do you think the v6.0.0 is going to be released? We cannot use nuget sources other than nuget.org, so it would be great to have the fix in there.

**Comment by PavelA85** [comment]
Hi,
any update on this?

**Comment by Melchy** [comment]
Hi,
any update on this?

**Comment by pada57** [comment]
hello
same issue here, any update on when this will be fix ?

**Comment by ggleo08** [comment]
aha , same mistake,
![image](https://user-images.githubusercontent.com/32858631/104573378-c7f58300-568f-11eb-8deb-0609bb0c138f.png)
