### ISSUE TITLE
Default oauth2RedirectUrl problem with query parameter

### ISSUE THREAD

**Issue by walik92** [domaindrivendev/Swashbuckle.AspNetCore#1854]
Swashbuckle.AspNetCore Version: 5.6.3
ASP.NET Core Version: 3.1

I have two versions of API and at the top of page in Swagger I can change definition v1 or v2. When I'm changing to v2, swagger set query param in browser `?urls.primaryName=v2`.
When I click Authorize button, swagger generate redirect_uri `http://localhost:5000/swagger/oauth2-redirect.html?urls.primaryName=v2`, but my authorization server has in configuration redirect_uri `http://localhost:5000/swagger/oauth2-redirect.html` and I get error Invalid redirect_uri.

I found code which generate redirect_uri in index.html 
`if (!configObject.hasOwnProperty("oauth2RedirectUrl"))
            configObject.oauth2RedirectUrl = window.location.href.replace("index.html", "oauth2-redirect.html").split('#')[0];`

I had to customize index.html and a change is very easy and small
`.split('#')->.split('?')`

Is it bug? What do you think?

**Comment by ulrichb** [comment]
Same here. Why is the `oauth2RedirectUrl` overwritten at all? The default value (see https://github.com/swagger-api/swagger-ui/blob/7a0c1ea556a4b393bace21f80a5c65acaed7a49f/src/core/index.js#L39) already uses the current `window.location` and does _not_ pass the query string.

**Comment by ulrichb** [comment]
@domaindrivendev  The relevant commits are
* 893aa299547207fc74455399ec4292bd8aa8902f, and
* aa682fa11e5cea2a6aa27f0c15e11c7cb42c3c8d, and
* 2dbb80765a1c47402dcbe05268d46a4a3a6dab9f

**Comment by GGJason** [comment]
Facing the same problem here.

**Comment by GGJason** [comment]
After deeply thinking, I thought that this is not a bug.
Because the query parameter is basically used to send information to the backend or the application to perform more jobs. So the parameter need to be kept for more actions in some scenario.
Maybe it could be an option can be set in Startup.cs.

**Comment by GGJason** [comment]
I add a parameter and some script to implement the idea I wrote previously. I create a pull request #1911 .

**Comment by ulrichb** [comment]
> After deeply thinking, I thought that this is not a bug.

Hmmm, but the Swagger UI also drops the query + hash part, see https://github.com/swagger-api/swagger-ui/blob/7a0c1ea556a4b393bace21f80a5c65acaed7a49f/src/core/index.js#L39.

In which situation, do you think the query part is necessary for the _OAuth request_? I can only think of being necessary to be part of the _return URL_ if doing a full page redirect (iff swagger UI used this mechanism, what it does not, right?)

**Comment by GGJason** [comment]
Yeap, I accept your point. I will change the default value to true. It is better default value.

**Comment by domaindrivendev** [comment]
> Is it bug? What do you think?

Yes, this is a bug - the current locations query param should not be included in the oauth redirect. So, this needs to fixed rather than introducing a new config option to skip the behavior.

> Why is the oauth2RedirectUrl overwritten at all?

It's overwritten because the swagger-ui default does not include the current path, which could be present in the case of virtual directories or reverse proxy environments.

@GGJason I'm going to close your original PR #1911. Could you please create a new one that simply fixes this bug? You'll need to test it for the following scenarios:

- with and without a virtual directory
- with and without query string params on the current swagger-ui page

Thanks
