### ISSUE TITLE
Memory leak when using NetTopologySuite.Geometries.Point in query parameter

### ISSUE THREAD

**Issue by KarolStosikPowel** [domaindrivendev/Swashbuckle.AspNetCore#1864]
Swashbuckle version: 5.6.3

**Reproduction:**
Add query parameter of type `NetTopologySuite.Geometries.Point` from `NetTopologySuite` nuget (recommenced by MS for handling spatial data in .net).

**Expected:**
Swagger should work normally, some usage of custom filters may be needed to handle this type.

**Actual:**
Immediate usage of few GB's of RAM. Swagger fails to start. Custom `OperationFilter` is not triggered at all, custom `SchemaFilter` filter takes 50 seconds to fire. Adding custom `MapType<Point>(...)` doesn't help. Api itself works correctly.

**Comment by domaindrivendev** [comment]
This is an interesting one and technically NOT an issue with Swashbuckle per se (although it has highlighted a minor chnge that should be made to SB ... more on that later).

The root cause is that ApiExplorer, ASP.NET Core's built-in metadata component, automatically explodes query-bound, complex type parameters into individual API parameters - one for every leaf property in the object graph. It does this because this is exactly how model binding works. For example, if you have a query-bound parameter of the following type:

```csharp
public class QueryParams
{
    public string Foo { get; set; }
    public string Bar { get; set; }
}
``` 

Then your API will accept a query string parameter called "QueryParams.Foo" and another called "QueryParams.Bar".

However, the object graph for `NetTopologySuite.Geometries.Point` turns out to be extremely complex, to the extent that the exploded set of parameters is massive, remarkably taking up GBs of RAM in `ApiExplorer` metadata, and ultimately bringing the Swagger processing to a hault.

Now, I'm assuming you have zero intention of having your API accept such a massive and complex set of query parameters. So, you're likely customizing the model binding process to accept these `Point` parameters as some kind of formatted string. You can do this with a custom model binder or a custom `TypeConverter` but unfortunately `ApiExplorer` only honors the latter approach. That is, if you use a custom model binder, it will still try to explode the object graph rather than treating it as a single query parameter. At this point, I'll hazard a guess that you went with a custom model binder 😉 

To resolve your issue, I would recommend the following. Firstly, I would switch to a `TypeConverter`, which is the recommended approach from the [ASP.NET Core docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1#model-binding-review) when you have a string-to-complex-type conversion. Once you do this, you should be able to successfully apply the `MapType` setting to Swashbuckle. Actually, this setting shouldn't be neccessary because Swashbuckle has enough information to know the type should be described as a string. I'll add this in the next version. For now though, here's an example setup to support query parameters of type `NetTopologySuite.Geometries.Point`:

```csharp
// Startup.cs
public void ConfigureServices(IServiceCollection services)
{
    ...

    // Register TypeConverter for NetTopologySuite.Geometries.Point so ASP.NET Core can accept it as a query parameter
    TypeDescriptor.AddAttributes(typeof(Point), new TypeConverterAttribute(typeof(PointTypeConverter)));

    services.AddSwaggerGen(c =>
    {
        c.MapType<Point>(() => new OpenApiSchema { Type = "string" });
    });
}

// PointTypeConverter.cs
public class PointTypeConverter : TypeConverter
{
    public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType) =>
        sourceType == typeof(string);

    public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value) =>
        // Create the Point instance here from value.ToString()
}
```

**Comment by fededim** [comment]
Ok this is a workaround, but I would have left the issue open in order to track it and as a reminder while we are awaiting the response from aspnetcore on apiexplorer issue.

**Comment by domaindrivendev** [comment]
@fededim I don't think this is a "workaround" - it's the recommended approach from the [ASP.NET Core docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1#model-binding-review) when you have a string-to-complex-type conversion.

**Comment by fededim** [comment]
It is a workaround since the NetTopologySuite.Geometries.Point type is [the one advised by the same Microsoft](https://docs.microsoft.com/en-GB/ef/core/modeling/spatial) to use when dealing with spatial data types in EF core and it shouldn't make the ApiExplorer (another component developed by Microsoft) go into a loop. Moreover using the above method the documentation output of Swagger UI maps the properties with type NetTopologySuite.Geometries.Point into a "string", whereas in my API I expect them to be an object with just 2 properties X and Y (I am using a custom JsonConverter for serialization/deserialization), so there is a mismatch between documentation and actual api.

**Comment by fededim** [comment]
@domaindrivendev just a question: isn't there a way to tell ApiExplorer not to consider certain properties from a complex type ?

**Comment by domaindrivendev** [comment]
@fededim yes. The approach depends on whether the property in question is bound to a request parameter (i.e. `[FromRoute]`, `[FromQuery]`, `[FromHeader]`) or if it belongs to an object that's bound to the request body (i.e. `[FromBody]`). For the former case, ASP.NET Core uses it's "model binding" subsystem to deserialize the values and if you want it to ignore certain properties simply decoreate the property with the `[BindNever]` attribute. For the latter, ASP.NET Core will delegate to the configured serializer (e.g. STJ or Newtonsoft) and therefore to ignore properties in that context, you simply decorate with the corresponding `[JsonIgnore]` attribute. For all of the above, Swashbuckle will follow suit and omit the property in question from the generated docs.

**Comment by bjornharrtell** [comment]
This works well for situations where you want GeoJson serialization and need to support different geometry types:

```csharp
        public class GeometryTypeConverter : TypeConverter
        {
            public override bool CanConvertFrom(ITypeDescriptorContext context, Type sourceType) =>
                sourceType == typeof(string);

            public override object ConvertFrom(ITypeDescriptorContext context, CultureInfo culture, object value) =>
                new GeoJsonReader().Read<Geometry>(value.ToString());
        }
```
