### ISSUE TITLE
DefaultValue(0) not populating in Swagger UI

### ISSUE THREAD

**Issue by CaCTuCaTu4ECKuu** [domaindrivendev/Swashbuckle.AspNetCore#1877]
Property in swagger UI left empty and if I marked field as required I should manually set value.

I kinda see what's happening but when I explicitly define that I want to see that value I believe it should be there.

> [JsonProperty("offset")]
> [DefaultValue(0)]
> public int Offset { get; set; }

**Comment by domaindrivendev** [comment]
I could do with a little more information - perhaps some screenshots to fully understand your issue?

**Comment by CaCTuCaTu4ECKuu** [comment]
I defined default values on properties
<img width="384" alt="0" src="https://user-images.githubusercontent.com/8963134/104668786-6bbb4f00-56e1-11eb-8475-cea7d118947f.png">
But when I try it - field is empty and if it is required I have to define it manually every time.
<img width="372" alt="1" src="https://user-images.githubusercontent.com/8963134/104668789-6c53e580-56e1-11eb-8610-8d8de3e7bed4.png">

**Comment by domaindrivendev** [comment]
Technically, this issue should be posted to the [swagger-ui](https://github.com/swagger-api/swagger-ui) project instead of Swashbuckle. However, I believe one could argue that the behavior you're seeing is correct.

The pre-populated values in the UI text boxes are _client-side_ defaults, whereas the `[DefaultValue]` attribute states the _server-side_ default. There's a subtle difference here that you need to take into account. The server-side default is the value that the server will assume if not explicitly provided by the client whereas the client-side default is merely the value that the client feels is most convenient to pre-populate for the user. For an _optional_ parameter, pre-populating with the server-side default is kind of redundant - you may as well leave it blank as that's the value that the server will assume anyway. I expect this is exactly the rationale for the behavior you're observing.

**Comment by CaCTuCaTu4ECKuu** [comment]
Basically I expected that answer, but sometimes it feels wrong
