### ISSUE TITLE
How to avoid clicking "try it out" button?

### ISSUE THREAD

**Issue by lugospod** [domaindrivendev/Swashbuckle.AspNetCore#1880]
Is it possible to be in "try it out" mode by default for all operations? It is a bit annoying to have to click each time..:)

Tnx!

**Comment by domaindrivendev** [comment]
This is a [swagger-ui](https://github.com/swagger-api/swagger-ui) issue and therefore should be posted to that repo instead of Swashbuckle. I took the liberty of doing a quick search for you and it looks like a) it's not currently possible and b) there is already an issue posted with significant support/likes to add this feature:

See https://github.com/swagger-api/swagger-ui/issues/2805

**Comment by lugospod** [comment]
Thank you for your quick feedback.

**Comment by 0xced** [comment]
For reference, it's possible since version 6.1.5.

```csharp
app.UseSwaggerUI(options => options.EnableTryItOutByDefault());
```

See commit ee334d6b1ac2c057b1595cd27403b9d57129f436.
