### ISSUE TITLE
Swashbuckle is over-zealous on generating schemas

### ISSUE THREAD

**Issue by davija** [domaindrivendev/Swashbuckle.AspNetCore#1889]
I seem to be having an issue in an application I am trying to incorporate Swashbuckle into.  Typically, when I generate the swagger.json file, I would expect it should include just the models that are used by the application.  However, when I try and use anything that has a `ModelStateDictionary`, I end up getting most of the "world".

I am currently using a .NET Core 3.1 Web Application with Swashbuckle 5.6.3 (also downgraded to 5.6.1 but got the same issue).

I am attaching a simple reproduction project.  If you attempt to generate the swagger.json and look at it, you will notice not just a few classes, but amount of internal classes (Assembly, MethodBase, ConstructorInfo, etc.).  It appears this all stems from the fact that `MethodBase` is getting included from `Exception` (property TargetSite).

I also tried seeing if I could filter things out via an `ISchemaFilter`, but `ModelStateDictionary` and `Exception` never seem to show up and have schemas created for them without being able to be acted upon by filters.

[ReproTest.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/5483066/ReproTest.zip)

**Comment by domaindrivendev** [comment]
`ModelStateDictionary` is a low-level framework type and shouldn't be used as a DTO in your method signatures. I would encourage you to read [this section in the ASP.NET Core docs](https://docs.microsoft.com/en-us/aspnet/core/web-api/?view=aspnetcore-3.1#automatic-http-400-responses), as it describes some best practices for returning error information in a .NET Core WebAPI.

Long story short though, if you want to return error responses, you should either use the `[ApiController]` attribute to do it automatically OR construct your method as follows if you're still doing it manually:

```csharp
public IActionResult GenerateTheWorld()
{
    if (!ModelState.IsValid)
        return BadResult(ModelState);
    else
        // happy path
}
```

**Comment by davija** [comment]
Yes, that is true about `ModelStateDictionary`.  I only used this one as an example because it was easy to reproduce.

However, my point is that we shouldn't have "magic" types that all of a sudden include the world without going through the filters. I tried using schema filters and `ModelStateDictionary` and `Exception` never turned up.

**Comment by davija** [comment]
Additionally, if we need to use a model from a third-party that we have no control over the source, we should be able to handle things like this by using a filter to remove properties that we don't need.

**Comment by domaindrivendev** [comment]
Actually, there is nothing "magic" going on here. Swashbuckle is in fact describing the _actual_ API behavior accurately. To help explain, consider the following action signature: 

```csharp
[HttpGet]
public ModelStateDictionary GenerateTheWorld([FromQuery, Required]string foo);
{
    return ModelState;
}
```

Now, independently of Swashbuckle, try calling the endpoint with an invalid URL (i.e. without the _required_ query parameter) so that the ModelState is populated with an entry. Note that the JSON response is a complex JSON structure that's reflective of the complicated "world" schema that Swashbuckle is generating, and includes the `exception` property, which is null in this case but may not be depending on how the validation is being performed.

The point here is that ASP.NET Core delegates to a JSON "Serializer" to convert response and body instances instances to/from JSON. If the type is a complex object graph, then that's going to result in some pretty complicated JSON. Swashbuckle isn't opinionated about the types you may or not decide to serialize as part of your API - it merely describes the _actual_ behavior pretty darn accurately. So, if you want Swashbuckle to do the right thing, then you need your API itself to do the right thing first, and Swashbuckle will simply follow suit.

The same principal applies for third-party models - if they includes fields that are to be ignored, then you need to start by figuring out how do you get the "Serializer" itself to ignore them - otherwise your API, independently of Swashbuckle, is going to expose them.

**Comment by domaindrivendev** [comment]
This is a fundamental principal of Swashbuckle that a lot of people seem to get tripped up on - "the code is the truth". If you're seeing Swagger descriptions that don't look correct, start by checking if the API itself is behaving according to those descriptions. It's impossible to be perfect, but SB does a really good job of describing _actual_ API behavior, and 99% of the time if you're seeing odd descriptions it's because your API behavior isn't what you think it is either.
