### ISSUE TITLE
Removing required properties using IDocumentFilter

### ISSUE THREAD

**Issue by adnan-kamili** [domaindrivendev/Swashbuckle.AspNetCore#1959]
Hi,

I have [Required] attribute set on the request model properties in my code. But the fields are required only during POST and not PATCH.  We ignore the validation incase of PATCH requests.

Now, in order to remove the required attribute from the UI for the PATCH request bodies, we tried the following:

    public class SwaggerDocumentFilter : IDocumentFilter
    {
        public void Apply(OpenApiDocument openApiDoc, DocumentFilterContext context)
        {
            var paths = openApiDoc.Paths;
             foreach (var path in paths)
            {
                foreach (var operation in path.Value.Operations)
                {
                    if (operation.Key == OperationType.Patch)
                    {
                        foreach (var content in operation.Value.RequestBody.Content)
                        {
                               content.Value.Schema.Required = new HashSet<string>();
                        }
                    }
                }
            }
        }

But this doesn't work. Doing something similar in ISchemaFilter works but we can't access the HTTP method in the ISchemaFilter

            schema.Required = new HashSet<string>();

**Comment by domaindrivendev** [comment]
If your `POST` and `PATCH` operations both accept the same model type, then it's not really possible to do what you want ...

For a given complex type in your API, Swashbuckle will generate a corresponding schema definition in the `components.schemas` section of the Swagger/OpenAPI document and will _reference_ that "shared" definition from the various operations in your API that use it. So, the schema instances that you're modifying above are actually a special type of schema that represent references rather than definitions and as such, their only applicable property is the `Reference` property (represented as `$ref` in the resulting Swagger JSON). Modifying any other properties has no effect.

Furthermore, if you were to locate the actual "definition" schema via `openApiDoc.Components` and make the adjustment there instead , that won't work either because it's a _shared_ definition and will therefore apply to both operations.

There is one possibility that might work for you, and that's leveraging the `allOf` keyword as described [here](https://github.com/OAI/OpenAPI-Specification/issues/1590). I have some ideas around this and will try post an example filter implementation in the next day or so.

**Comment by adnan-kamili** [comment]
Thanks for the update.

**Comment by domaindrivendev** [comment]
Assuming that the required field validation on models is only applicable for POST operations, then the following should work:

```csharp
public class PostOperationsSchemaFilter : IDocumentFilter
{
    public void Apply(OpenApiDocument swaggerDoc, DocumentFilterContext context)
    {
        var postSchemaIds = new SortedSet<string>();

        // Step 1: Iterate POST operations and "extend" their schema references using allOf so that the operation-specific
        // schema also has the required field metadata. Also capture the shared schema ID for use in step 2 below.
        foreach (var pathItem in swaggerDoc.Paths)
        {
            foreach (var operationItem in pathItem.Value.Operations)
            {
                if (operationItem.Key != OperationType.Post) continue;

                foreach (var mediaType in operationItem.Value.RequestBody.Content.Values)
                {
                    var schemaId = mediaType.Schema.Reference.Id;
                    var schemaDefinition = swaggerDoc.Components.Schemas[schemaId];

                    mediaType.Schema = new OpenApiSchema
                    {
                        AllOf = new List<OpenApiSchema>
                        {
                            new OpenApiSchema { Reference = new OpenApiReference { Type = ReferenceType.Schema, Id = schemaId }},
                            new OpenApiSchema { Required = new SortedSet<string>(schemaDefinition.Required) }
                        }
                    };

                    postSchemaIds.Add(schemaId);
                }
            }
        }

        // Step 2: Now that the operation-specific schema's for POST operations have required field metadata inline,
        // remove that metadata from the shared definitions so that it's now only applicable to POST operations.
        foreach (var schemaId in postSchemaIds)
        {
            swaggerDoc.Components.Schemas[schemaId].Required.Clear();
        }
    }
}
```

**Comment by adnan-kamili** [comment]
Thanks a lot. It worked :)
