### ISSUE TITLE
Swagger UI AuthorizeFilter null in AuthorizeFilter

### ISSUE THREAD

**Issue by bhtri** [domaindrivendev/Swashbuckle.AspNetCore#1978]
## Describe
I have a Swagger UI setup for my API and refer [here](https://stackoverflow.com/a/57620929/6284714) to add an Authorization parameter for controller methods with the `[Authorize]` attribute from `Microsoft.AspNetCore.Authorization`

I want to add a field in the parameter so that I can enter the token (generated by Jwt Bearer authentication) but the problem is that no methods are getting the authorization parameter added on the UI

 I debugged and found that the problem is that the filterPipeline derived from the FilterDescriptors doesn't contain the AuthorizeFilter. 

## My code
```
AuthorizationHeaderParameter.cs
public class AuthorizationHeaderParameterOperationFilter: IOperationFilter
    {
        public void Apply(OpenApiOperation operation, OperationFilterContext context)
        {
            var filterPipeline = context.ApiDescription.ActionDescriptor.FilterDescriptors;
            var isAuthorized = filterPipeline.Select(filterInfo => filterInfo.Filter).Any(filter => filter is AuthorizeFilter);
            var allowAnonymous = filterPipeline.Select(filterInfo => filterInfo.Filter).Any(filter => filter is IAllowAnonymousFilter);

            if (isAuthorized && !allowAnonymous)
            {
                if (operation.Parameters == null)
                    operation.Parameters = new List<OpenApiParameter>();

                operation.Parameters.Add(new OpenApiParameter 
                {
                    Name = "Authorization",
                    In = ParameterLocation.Header,
                    Description = "access token",
                    Required = true,
                    Schema = new OpenApiSchema
                    {
                        Type = "String",
                        Default = new OpenApiString("Bearer ")
                    }
                });
            }
        }
    }

Controller.cs
[Authorize]
[HttpPost("test")]
public IActionResult test(LoginTkRequest request)
{
    return Ok(new { 
        mess = "ok"
    });
}

.csproj
<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.1</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="3.1.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="5.5.0" />
  </ItemGroup>
</Project>


```
Am I missing any steps or am misunderstanding the problem somewhere?
Any help would be greatly appreciated. Thank you.

**Comment by domaindrivendev** [comment]
In OpenAPI (formerly the Swagger spec), you specify Bearer token security through the `securitySchemes` and `security` keywords rather than defining a header parameter with the name "Authorization". In fact, the spec clearly states that the latter approach will simply be ignored, hence why your approach is not working.

> If in is "header" and the name field is "Accept", "Content-Type" or "Authorization", the parameter definition SHALL be ignored.

To get this working correctly, read the [Open API docs here](https://swagger.io/docs/specification/authentication/bearer-authentication/) to firstly understand how to describe the scheme in the OpenAPI format. Then take a look a [this section of the Swashbuckle docs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements) to achieve this with Swashbuckle.
