### ISSUE TITLE
v6.0.0 broke forwarding headers

### ISSUE THREAD

**Issue by mantasaudickas** [domaindrivendev/Swashbuckle.AspNetCore#1995]
We are running behind reverse proxy which is changing path. 
Seems like version v6.0.0 changed **again** how it handles X-Forwarded-Path.

We use forwarding headers middleware:
`            app.UseForwardedHeaders(new ForwardedHeadersOptions
            {
                ForwardedHeaders = ForwardedHeaders.All,
                RequireHeaderSymmetry = false
            });
`

Please see screenshot how response differs with version 5.6.3 (correct one) and version 6.0.0:
![image](https://user-images.githubusercontent.com/1263609/107117606-190a2880-6884-11eb-979e-6d3b0a3c9e86.png)

Are we doing something wrong or its a regression bug?

**Comment by domaindrivendev** [comment]
The approach from `5.6.3` was fundamentally flawed and although it may have been working for you, it was also causing a lot of issues for others (see #1953 for a summary). Ensuring applications work correctly behind a proxy (e.g. for link generation, redirects etc.) is an _application-level_ concern as opposed to just Swashbuckle, and so should be addressed independently, as described in the [Forwarded Header docs](https://docs.microsoft.com/en-us/aspnet/core/host-and-deploy/proxy-load-balancer?view=aspnetcore-5.0), rather than within Swashbuckle code.

So, I've removed this responsibility from Swashbuckle as described in the [6.0.0 release notes](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/releases/tag/v6.0.0) in favor of guidance to use the Forwarded Headers Middleware to solve the problem. Please read through the following section of the SB readme, in particular the part for  proxies that change the request path, there should be enough info there to solve your issue:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore#working-with-reverse-proxies-and-load-balancers
