### ISSUE TITLE
Multiple UseSwaggerUI support removed?

### ISSUE THREAD

**Issue by effyteva** [domaindrivendev/Swashbuckle.AspNetCore#1996]
Hi,

We're trying to migrate to the new 6.0.2 release,
We're currently using UseSwaggerUI twice, while each UI renders different API methods (one is used for the most common methods, and the other for all methods regardless of their usage).
The methods are excluded using the DocInclusionPredicate, based on the DocumentName.

After migrating to the new 6.0.2 release, only the second UseSwaggerUI call is actually working, and the first one seems to be completely ignored.
Is that intended behavior or a bug? Is there any other way to achieve multiple endpoints with different methods?

Thank you,
Effy

**Comment by domaindrivendev** [comment]
Hi @effyteva. In the latest version, if you're configuring the `Swagger` or `SwaggerUI` middleware with the overload that accepts a setup action (e.g. `Action<SwaggerUIOptions>`) then you're implicitly using the _singleton instance_ of options from you're app's DI container (see the [ASP.NET Core Options pattern](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/configuration/options?view=aspnetcore-5.0) for more info on this).

So, for your usecase you'll need to use the overload that accepts a specific instance of options instead of the setup action:

```csharp
app.UseSwaggerUI(new SwaggerUIOptions
{
    RoutePrefix = "foo-docs",
    ConfigObject = new ConfigObject
    {
        Urls = new[] { new UrlDescriptor { Url = "/swagger/foo/swagger.json", Name = "Foo Docs"} }
    }
});

app.UseSwaggerUI(new SwaggerUIOptions
{
    RoutePrefix = "bar-docs",
    ConfigObject = new ConfigObject
    {
        Urls = new[] { new UrlDescriptor { Url = "/swagger/bar/swagger.json", Name = "Bar Docs"} }
    }
});
```

**Comment by effyteva** [comment]
Thank you @domaindrivendev 
I appreciate your quick response, this worked perfect, and we've managed to upgrade to the newest release once again.

Effy

**Comment by halloersmal** [comment]
That helped me out! Thank you so much for the ConfigObject usage Example! I worked for days to have two different Swagger UIs for different endpoints!
