### ISSUE TITLE
Non Nullable Reference Types support seems lacking or broken

### ISSUE THREAD

**Issue by esbenbach** [domaindrivendev/Swashbuckle.AspNetCore#1997]
**Version** : 6.0.2

I figured I would try using NonNullableReferenceTypes

Given the classes:
```CSharp
    public class Parameters
    {
        public int RequiredInt { get; set; }

        public int? OptionalInt { get; set; }

        public DateTime RequiredDate { get; set; }

        public DateTime? OptionalDate { get; set; }

        public InnerParameters RequiredRef { get; set; } = new InnerParameters();

        public InnerParameters? OptionalRef { get; set; }
    }

    public class InnerParameters
    {
        public string RequiredString { get; set; } = "Initialized";
    }
```

And a controller method:
```CSharp
[HttpPost()]
public IAsyncResult DoThings([FromBody]Parameters input) { return this.Ok(); }
```

I get the following output:
```JSON
    "schemas": {
        "InnerParameters": {
            "type": "object",
            "properties": {
                "requiredString": {
                    "type": "string"
                }
            },
            "additionalProperties": false
        },
        "Parameters": {
            "type": "object",
            "properties": {
                "requiredInt": {
                    "type": "integer",
                    "format": "int32"
                },
                "optionalInt": {
                    "type": "integer",
                    "format": "int32"
                },
                "requiredDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "optionalDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "requiredRef": {
                    "$ref": "#/components/schemas/InnerParameters"
                },
                "optionalRef": {
                    "$ref": "#/components/schemas/InnerParameters"
                }
            },
            "additionalProperties": false
        }
    }
```

If i turn off `<nullable>enable</nullable>` from my `csproj` file. It starts treating Nullable<int> etc correctly.
But as long as its toggled on, nothing i do with configuration of `UseNonNullableReferenceTypes` does any thing.

Also, `UseNonNullableReferenceTypes` I would expect my `optionalref` to be marked with `"nullable": true` in the json file.

Am I missing something or is this basically broken?

**Comment by domaindrivendev** [comment]
Yep this looks to be broken alright - looking into it ...

**Comment by domaindrivendev** [comment]
Firstly, let me just state this is def beta functionality at the moment, hence why it's opt-in and not documented. 

Regarding `optionalRef`, it _cannot_ be marked with `"nullable": true` because it's a _reference_ to a schema as opposed to an actual schema. If you want to add additional metadata (like `nullable`) to reference schemas, then you'll need to enable the `UseAllOfToExtendReferenceSchemas` setting.

That should resolve your question around the `optionalRef` property. However, the `optionalInt` property is an _inline_ schema definition and therefore _should_ be marked with `"nullable": true"`. This looks to be a genuine bug whereby value types were not being handled correctly within a nullable context. I just pushed ec60046f57aaea0d4d6a4af4de26c29214502277 which should fix this. Could you please pull down the latest `6.0.3` preview build from [myget.org](https://myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore) and try it out?

**Comment by esbenbach** [comment]
I am aware its a beta feature :)
I would however expect that `<nullable>enable</nullable> `  should leave my Nullable<int> as it was without the nullable context.

With the preview 6.0.3 version i get the desired behaviour. Awesome.
