### ISSUE TITLE
Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Conflicting method/path combination

### ISSUE THREAD

**Issue by antjbailey** [domaindrivendev/Swashbuckle.AspNetCore#2035]
Hi,

I have the following API controller with 2 GET actions

```
[Route("api/[controller]")]
[ApiController]
public class InvestorsController : ControllerBase
{
    [HttpGet("{id:guid}", Name = nameof(GetCrmInvestor))]
    public async Task<ActionResult<Dto.Crm.InvestorDto>> GetCrmInvestor(Guid id)
    {
    }

    [HttpGet("{id:int}", Name = nameof(GetCrowdInvestor))]
    public async Task<ActionResult<InvestorDto>> GetCrowdInvestor(int id)
    {
    }
}

```
I can **successfully** call both of these endpoints using Postman - 1 with an int, 1 with a guid - however, Swagger throws an exception:

`Swashbuckle.AspNetCore.SwaggerGen.SwaggerGeneratorException: Conflicting method/path combination "GET api/Investors/{id}" for actions - {full path to method}.GetCrmInvestor, {full path to method}.GetCrowdInvestor. Actions require a unique method/path combination for Swagger/OpenAPI 3.0. Use ConflictingActionsResolver as a workaround`

This API is written in ASP.NET Core 5 (net5.0). Using Nuget package Swashbuckle.AspNetCore Version 6.0.7

This seems different to #1713 as I have provided a route name.

Am I doing something wrong?

**Comment by domaindrivendev** [comment]
Swashbuckle is built on top of the [OpenAPI Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.1.md). That is, it generates an OpenAPI document that describes your API and then uses that document to power the [swagger-ui](https://github.com/swagger-api/swagger-ui).

In OpenAPI, each operation is uniquely identified by a combination a "path template" and a HTTP method. In this context, a "path template" is a relative path with curly braces (if applicable|) to mark a section of a URL path as replaceable using path parameter names. Similar to a "route template", which is a concept internal to ASP.NET Core, but curly braces would only include parameter names, and not route constraint syntax.

With this in mind, your two operations would have the same "path template" (`/investors/{id}`) and the same HTTP method, and so the generated OpenAPI document would not be valid, hence the exception. To workaround this, you need to have something in the "path template" to distinguish them from eachother, and in this case it seems the parameter name is your best option because it wouldn't change the API behavior in any way.

```csharp
[Route("api/[controller]")]
[ApiController]
public class InvestorsController : ControllerBase
{
    [HttpGet("{guidId:guid}", Name = nameof(GetCrmInvestor))]
    public async Task<ActionResult<Dto.Crm.InvestorDto>> GetCrmInvestor(Guid guidId)
    {
    }

    [HttpGet("{intId:int}", Name = nameof(GetCrowdInvestor))]
    public async Task<ActionResult<InvestorDto>> GetCrowdInvestor(int intId)
    {
    }
}
```

**Comment by antjbailey** [comment]
@domaindrivendev Thank you for your quick response. Your suggestion to rename the path parameters has resolved this issue.

Many thanks

**Comment by denis-ivanov** [comment]
@abdollahkahne, I have the same problem.

**Comment by dheerajawale-svg** [comment]
https://stackoverflow.com/questions/73598068/adding-new-method-to-controller-makes-swagger-give-500-error
