### ISSUE TITLE
Default value for enums not considered

### ISSUE THREAD

**Issue by mconca-kube** [domaindrivendev/Swashbuckle.AspNetCore#2075]
Using .Net 5 and Swagger 6.1.1
I'm trying to have default values working on Enums without success.

```
[HttpGet]
public void Test(System.IO.FileAccess access = System.IO.FileAccess.Read)
{

}
```

![immagine](https://user-images.githubusercontent.com/61966672/113035293-607da880-9193-11eb-9670-bbded4c76af8.png)

Am I missing something?

**Comment by domaindrivendev** [comment]
Dup of #1164 

Long story short, it's due to some nuances with the OpenAPI/JsonSchema specification, specifically how it handles _referenced_ schema defintions. However, you can workaround it by applying _either one_ of the following settings - `UseInlineDefinitionsForEnums()` or `UseAllOfToExtendReferenceSchemas()`.
