### ISSUE TITLE
Wrong JsonPatchDocument type reference when migrate from Newtonsoft.Json to System.Text.Json in V6

### ISSUE THREAD

**Issue by knoxi** [domaindrivendev/Swashbuckle.AspNetCore#2094]
Thanks for the fix in issue #2029, this worked fine in my current solution.

Now I'm working on the migration from `Newtonsoft.Json` to `System.Text.Json` based on the following Microsoft Docs:
* [How to migrate from Newtonsoft.Json to System.Text.Json](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-migrate-from-newtonsoft-how-to?pivots=dotnet-5-0#jsondocument-and-jsonelement-compared-to-jtoken-like-jobject-jarray)
* [JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-5.0)

Changing the Startup as mentioned in the [documentation for JsonPatch in ASP.NET Core web API](https://docs.microsoft.com/en-us/aspnet/core/web-api/jsonpatch?view=aspnetcore-5.0#json-patch-addnewtonsoftjson-and-systemtextjson), I have now the same issue again as in #2029.

Old startup: 
```
services
    .AddControllers()
    .AddJsonOptions(x =>
    {
        x.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
        x.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
        x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(namingPolicy: JsonNamingPolicy.CamelCase, allowIntegerValues: false));
        x.JsonSerializerOptions.WriteIndented = true;
        x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve;
    })
    .AddNewtonsoftJson(options =>
    {
        options.SerializerSettings.ReferenceLoopHandling = ReferenceLoopHandling.Ignore;
        options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
        options.SerializerSettings.Converters.Add(new StringEnumConverter() { AllowIntegerValues = false, NamingStrategy = new CamelCaseNamingStrategy() });
        options.SerializerSettings.Formatting = Formatting.Indented;
    });
```

New Startup:
```
services
    .AddControllers(options =>
    {
        options.InputFormatters.Insert(0, GetJsonPatchInputFormatter());
    })
    .AddJsonOptions(x =>
    {
        x.JsonSerializerOptions.PropertyNameCaseInsensitive = true;
        x.JsonSerializerOptions.PropertyNamingPolicy = JsonNamingPolicy.CamelCase;
        x.JsonSerializerOptions.Converters.Add(new JsonStringEnumConverter(namingPolicy: JsonNamingPolicy.CamelCase, allowIntegerValues: false));
        x.JsonSerializerOptions.WriteIndented = true;
        x.JsonSerializerOptions.ReferenceHandler = ReferenceHandler.Preserve;
    });
...
private static NewtonsoftJsonPatchInputFormatter GetJsonPatchInputFormatter()
{
    var builder = new ServiceCollection()
        .AddLogging()
        .AddMvc()
        .AddNewtonsoftJson()
        .Services.BuildServiceProvider();

    return builder
        .GetRequiredService<IOptions<MvcOptions>>()
        .Value
        .InputFormatters
        .OfType<NewtonsoftJsonPatchInputFormatter>()
        .First();
}
```

I have added an updated sample.
[sample.zip](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/files/6325828/sample.zip)

**Comment by domaindrivendev** [comment]
The setup you've shown now uses a mix of both serializers - Newtonsoft for patch requests and STJ for everything else. Independently of Swashbuckle, surely this will make it difficult to maintain consistency in how certain types are serialized? For example, if you had en enum type that's used in both PATCH and POST requests, you'll need to configure a string enum converter for both Newtonsoft and STJ.

Then, when you bring Swashbuckle into play I can see further complications arising because it doesn't currently support multiple serializers. So, all in all, I wouldn't recommend the approach you're taking. I get the value of fully migrating to STJ, but I'm not convinced this half-way approach is worth the potential headaches. 

With all that said, I _think_ you can workaround this particular issue with the following line of code in your `ConfigureServices` method, which is automatically added when you add Newtonsoft normally via `AddNewtonsoftJson`. Beware though, you're getting into major weeds here:

```csharp
services.TryAddEnumerable(
    ServiceDescriptor.Transient<IApiDescriptionProvider, JsonPatchOperationsArrayProvider>());
```

**Comment by knoxi** [comment]
Thanks for your feedback, I see your point. To be honest, I haven't even thought of the point about the serializers on PATCH.

What possibilities do you see to migrate completely to STJ including PATCH without being dependent on Newtonsoft, since Microsoft does not offer a patch type?
