### ISSUE TITLE
SwaggerUI js and css files include a link to sourceMap without bundling them

### ISSUE THREAD

**Issue by pranavkm** [domaindrivendev/Swashbuckle.AspNetCore#2106]
Version: 5.6.3

Some of the css and js files bundled in Swashbuckle.AspNetCore.SwaggerUI.dll include references to source map files, but these aren't available to be downloaded. This results in an unnecessary 404 and a warning logged in the DevTools:

![image](https://user-images.githubusercontent.com/70501796/115856958-b4f90880-a45f-11eb-9272-fb31fc248362.png)

**Comment by bradygaster** [comment]
@domaindrivendev - is this something that could be mitigated? Some customers have noticed it and, whilst not blocking, it does make for a sub-optimal experience for new Web API and minimal API developers who File -> New -> Run -> See error. Is it possible this could be resolved in an upcoming release soon?

**Comment by domaindrivendev** [comment]
@bradygaster - looks like there was a bit of whackamole around this.

It looks like it was originally identified and fixed by this PR:
#779

Then, a couple of months later someone raised the issue that including the `.map` files significantly increased the size of the SwaggerUI.dll (from ~2MB to ~11MB). So, oblivious to the original fix, it looks like I went ahead and reverted with the following commit:
#922

So, I guess the question now is how best to proceed. Do we live with the size increase or the 404 console warnings? Or, is there some way to remove the links from the source files?
