### ISSUE TITLE
Problem generating correct swagger.json

### ISSUE THREAD

**Issue by RobThree** [domaindrivendev/Swashbuckle.AspNetCore#2216]
Hi!

I'm experiencing something I _think_ is a bug. It's a bit complicated and hard to explain but I'll try my best. I have provided a repo to reproduce the issue [here](https://github.com/RobThree/SwashbuckleIssueDemo).

In a project our objects have an Id of type `ObjectId`; the why of it is irrelevant for the question; it is how it is. [I can use this ObjectId in a route](https://github.com/RobThree/SwashbuckleIssueDemo/blob/c48669ecb9f5013b282f83956d10cd90d3c5409b/SwashbuckleTest/Controllers/TestController.cs#L36) (e.g. `/foo/bar/{objectid}` and it [works fine when posted as a property of an object](https://github.com/RobThree/SwashbuckleIssueDemo/blob/c48669ecb9f5013b282f83956d10cd90d3c5409b/SwashbuckleTest/Controllers/TestController.cs#L41) (e.g. `Customer.Id`). However, I can't get it to work correctly as a querystring argument (e.g. `/foo?id=123`). That is: the swagger json doesn't seem to line up correctly and so the Swagger UI doesn't generate the correct request.

The following reproduces my issue(s):

1. [The ObjectId isn't even picked up unless I use `[FromQuery]` attribute](https://github.com/RobThree/SwashbuckleIssueDemo/blob/c48669ecb9f5013b282f83956d10cd90d3c5409b/SwashbuckleTest/Controllers/TestController.cs#L20) (expected: 2 arguments, `id` and `name`, only `name` is picked up)
2. [When I use a `[FromQuery]` attribute](https://github.com/RobThree/SwashbuckleIssueDemo/blob/c48669ecb9f5013b282f83956d10cd90d3c5409b/SwashbuckleTest/Controllers/TestController.cs#L25) the argumentname is picked up as [`IsNew`](https://github.com/RobThree/SwashbuckleIssueDemo/blob/c48669ecb9f5013b282f83956d10cd90d3c5409b/SwashbuckleTest/Infrastructure/ObjectId/ObjectId.cs#L13) which happens to be the first property on `ObjectId` (expected: `id`)
3. [When I use a `[FromQuery]` attribute with an explicit name (e.g. `[FromQuery(Name = "id")]`) the name is ignored](https://github.com/RobThree/SwashbuckleIssueDemo/blob/c48669ecb9f5013b282f83956d10cd90d3c5409b/SwashbuckleTest/Controllers/TestController.cs#L30)

Whenever I change the url, changing `IsNew` to `id` (e.g. `https://localhost:44373/Test/testgetquerystring2?IsNew=123&name=abc` => `https://localhost:44373/Test/testgetquerystring2?id=123&name=abc` for the second case for example) it works as expected.

When I [change `ObjectId` to `string`](https://github.com/RobThree/SwashbuckleIssueDemo/commit/232d91d548778c246287b9903f19d5375704dedc) it works fine, same when I [change to `long`](https://github.com/RobThree/SwashbuckleIssueDemo/commit/97a0add61e2283d53e97e16434b9104c41e5679e) and even [changing to `Guid`](https://github.com/RobThree/SwashbuckleIssueDemo/commit/db79b55f126dedc99a7aa48bd8866fcd8bfd45b2) (which more closely resembles an `ObjectId` since it's also a struct) works just fine.

So my question is: am I doing something wrong or missing something? What is the difference between `ObjectId` (not working) and `string` or `long` (working) and even `Guid` (working, also a struct like `ObjectId`). Or is this maybe a bug?

P.S. Sorry for the title; I'm having a hard time describing this issue in a single line...

**Comment by RobThree** [comment]
🤔hmmm, when I [change the `IsNew` property to an `IsNew()` method](https://github.com/RobThree/SwashbuckleIssueDemo/commit/0fdc23e112ff2e9a5cbe6a33f0227b3c0ffd3785#diff-4645ae55dc9d856c5a0afcec744da8649e5dcb334f73a0b5426bca8f0b3da391) then 2 and 3 (both using the `[FromQuery]` attributes) seem to work correctly, 1 still doesn't pick the argument up and only shows the `name` argument.

**Comment by domaindrivendev** [comment]
Technically this is a dup of #1864 - or at least the route cause is the same. Swashbuckle relies heavily on the metadata that's surfaced by `ApiExplorer`, part of ASP.NET Core. And unfortunately, that component does not honor custom model binders. That is, it doesn't know you want the ObjectId instance to be represented as a single query parameter. Instead, it describes it as multiple query parameters - one for each property of the class because this is the default model binding behavior for complex types.

I guess you could say this is a bug but I can also understand why they don't because it's challenging to determine serialization behavior that's defined by runtime code as opposed to static constructs like attributes, classes, method signatures etc. Furthermore, they recommend a `TypeConverter` as opposed to a custom model binder for a simple `string` -> `SomeType` mapping as per the [model binding docs](https://docs.microsoft.com/en-us/aspnet/core/mvc/advanced/custom-model-binding?view=aspnetcore-2.1#model-binding-review-1):

> We recommended you create a type converter if you have a simple string -> SomeType mapping that doesn't require external resources.

This is a very simple change (see #1864 for an example) and if you're in a position to do it, then this will solve your problem as `ApiExplorer` _does_ honor Type Converters. If not, your options are a bit more limited and you're probably looking at hooking into the Swagger generator and modifying the Operation parameters with an `IOperationFilter` (see readme).
