### ISSUE TITLE
Add extension method for Bearer authentication

### ISSUE THREAD

**Issue by vanillajonathan** [domaindrivendev/Swashbuckle.AspNetCore#2234]
This is how I add [Bearer authentication](https://swagger.io/docs/specification/authentication/bearer-authentication/):
```cs
services.AddSwaggerGen(c =>
{
    c.AddSecurityDefinition("bearerAuth", new OpenApiSecurityScheme
    {
        Type = SecuritySchemeType.Http,
        Scheme = "bearer",
        BearerFormat = "JWT",
        Description = "JWT Authorization header using the Bearer scheme."
    });
    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "bearerAuth" }
            },
            new string[] {}
        }
    });
});
```

That is way too much boilerplate code. Please provide a extension method so I can set it up with less code, I would like to do something like this:
```cs
services.AddSwaggerGen(c =>
{
    c.AddBearerAuthentication();
});
```

**Comment by domaindrivendev** [comment]
I'm sure this won't be a popular answer but I'd prefer not go down the road of introducing "convenience" functions to simplify writing Swagger/Open API as that's not a core concern of Swashbuckle. First and foremost, Swashbuckle's goal is to automatically generate Swagger/Open API documents based on your APIs _actual_ implementation - "code first", "code is truth" and all that. And, in the cases where this auto-generated description is not sufficient, the secondary goal is to expose a Swagger/Open API object model so that the document can be tweaked as needed.

Unfortunately, the Swagger/Open API's semantics for defining security schemes is heavy on the boilerplate, so I fully understand the value in this PR. I just don't want Swashbuckle to take on the third concern of "making it easier to write Swagger/Open API". If you'd like, you could create a separate add-on project, which I'd be happy to reference from the readme, that adds this "convenience" method and others?

**Comment by vanillajonathan** [comment]
😭
