### ISSUE TITLE
FromHeader not working for standard header Date

### ISSUE THREAD

**Issue by mvegeta50** [domaindrivendev/Swashbuckle.AspNetCore#2329]
Hello,

For Swashbuckle.AspNetCore.Swagger version 6.2.3

Swagger does not accept the standard header Date from parameters "FromHeader("Date") Datetime date" and neither from IOptionsFilter in the Ui, the problem could be related to UI and/or swagger, thats why I post it here.
The Ui gets response that the header date is required, even if it is filled in. 

If I test from Postman, then there is no issue.

**Comment by domaindrivendev** [comment]
Not enough information here please provide specific repro details - ideally, by creating a simple app (i.e. start from blank project) that repros the issue and post to github so I can pull down and troubleshoot.

**Comment by hejiheji001** [comment]
Same issue here, and I also tested adding header in the following way.

In Program.cs I added Swagger as follows
`
services.AddSwaggerGen(options => {
options.OperationFilter<AuthenticationRequirementsOperationFilter>();
});
`

And this is what inside `AuthenticationRequirementsOperationFilter` class
`
operation.Parameters.Add(new OpenApiParameter {
            Name = HeaderNames.Date,
            In = ParameterLocation.Header,
            Required = true
        });
`

The SwaggerUI will generate the curl command for me as follows
`
curl -X 'GET' \
  'https://localhost:44365/api/v1/endpoint' \
  -H 'accept: application/json' \
  -H 'Date: 2023-04-24T09:18:44.570Z'
`

The problem is, when I try to send the request via SwaggerUI, the date header is ignored.

But if I use postman to do the same request, the date header is correctly sent and can be captured by my program.
