### ISSUE TITLE
enum values not correctly emitted

### ISSUE THREAD

**Issue by Perpendere** [domaindrivendev/Swashbuckle.AspNetCore#2337]
Swashbuckle 5.2.1 was the last version to correctly export enum values.
C# enum:
```
    public enum SeatType
    {
        NoSeat = 0,  // bitfields
        SeatTypeFirst_Seat = 0,
        SeatTypeFirst_Student = 1,
        LeftHanded = 1,
        RightHanded = 2,
        Ambidextrous = 3,
        NoPreference = 3,
        Handicap = 4,
        LastSeatType = 4,
    }
```

version 5.2.1 exported:
```
export enum SeatType {
    NoSeat = 0,
    SeatTypeFirst_Seat = 0,
    SeatTypeFirst_Student = 1,
    LeftHanded = 1,
    RightHanded = 2,
    Ambidextrous = 3,
    NoPreference = 3,
    Handicap = 4,
    LastSeatType = 4,
}
```

current version exported:
```
export enum SeatType {
    NoSeat = 0,
    SeatTypeFirst_Seat = 1,
    SeatTypeFirst_Student = 2,
    LeftHanded = 3,
    RightHanded = 4,
}
```

Please fix in next release.   Thank you.

**Comment by tbolon** [comment]
I suspect it's caused by this [`.Distinct()`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs#L285) usage

**Comment by Perpendere** [comment]
I'm encountering a conflict between a version that works with Luxon ver 13.12.0 and the non-Distinct() Swashbuckle version 5.2.1
Seems like I'll have to build my own custom Swashbuckle locally sans .Distinct() until a fix is released.
When will a fix be released?

**Comment by domaindrivendev** [comment]
@Perpendere the reason is because it's a requirement of the JSON Schema specification, which is what's being used to describe types, including enum types, in an OpenAPI / Swagger document. See [here](https://json-schema.org/draft/2020-12/json-schema-validation.html#rfc.section.6.1.2) and the following line specifically:

> The value of this keyword MUST be an array. This array SHOULD have at least one element. Elements in the array SHOULD be unique.

With that said though, it looks like a bug has crept in here whereby the dedup is being done on the original C# enum values as but should instead be done on the externally exposed values after serialization/deserialization (I assume you understand why the latter MUST be unique).
