### ISSUE TITLE
Order actions on UI by http method

### ISSUE THREAD

**Issue by maelmahdy86** [domaindrivendev/Swashbuckle.AspNetCore#2345]
I need to order actions under each group/controller by http method so all GET actions comes first then POST then PUT and finally DELETE
I need to do this regardless the action path/route
I've searched the issue list and found issue #401 for the same topic but it was closed without and recommendations.
Is there any recommendation how to do it?

**Comment by ShaunWhite2018** [comment]
Hey maelmahdy86!

Yeah, this isn't a straight forward thing to do in Swagger as of yet... Even though the ability to order actions by whatever means we wish seems well desired!

Anyway, you could try this Vanilla JavaScript hack for now:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/401#issuecomment-1030934353

It's based on Swagger's ability to inject custom JavaScript files into the pipeline, so that developers can customize the behaviour of Swagger.

The hack seems to be working well (for Swashbuckle.AspNetCore.SwaggerUI version 6.2.3 at least!) and you can easily rearrange the order by simply rearranging the **SwaggerHttpMethods** array.

Hope this helps!
