### ISSUE TITLE
Read descriptions from configurable or custom xml tags

### ISSUE THREAD

**Issue by lonix1** [domaindrivendev/Swashbuckle.AspNetCore#2348]
The XML comments feature is really nice in that it avoids the need to have all those attributes.

The problem is that `<summary>` (etc.) tags traditionally contains internal company docs. We discovered that we were publishing all kinds of confidential stuff via swagger to some clients.

So right now it's either the attributes or the xml.

It would be nice to be able to specify which tags to consider. Swashbuckle seems to extract text from `<summary>`, `<remarks>`, `<param>` and `<response>`. If this were configurable, for example, I'd disable "remarks" so we could put confidential stuff in there.

Or even better, since there's already a custom "response" tag, it would be nice to have custom `<swagger>` or `<openapi>` or `<swagger-summary>` or whatever tags. That would be less surprising to c# devs who are accustomed to xml doc comments.

**Comment by martincostello** [comment]
Personally, in this scenario I would do one of two things:

1. Add "private" comments as // style comments inside the method body, not in the /// comments which are designed for public consumption. For example, if you used docfx to generate API documentation for a library you would have the same issue otherwise.
2. Use the attributes to be explicit about "code comments" vs "public documentation for Swagger"

I don't think adding complexity with yet more custom tags and/or filtering here is a solution we'd pursue given that the crux of your use case is _"I want to put private comments in a place designed for public consumption"_.
