### ISSUE TITLE
Upgrade to .NET Core 1.1

### ISSUE THREAD

**Issue by theezak** [domaindrivendev/Swashbuckle.AspNetCore#239]
Support for Microsoft AspNet Core 1.1.0

**Comment by tillig** [comment]
Is there something that _doesn't_ work in ASP.NET Core 1.1? #232 has some tips from folks who had troubles but it turns out deleting `bin` and `obj` folders fixed them up.

**Comment by theezak** [comment]
I was more thinking about integration with https://github.com/Microsoft/aspnet-api-versioning . Probably should have titled this issue differently. I duck taped the aspnet api versioning and Ahoy (for example to pick up the default version from api versioning in Ahoy). Wondering if there is a plan for a more structural integration.

**Comment by micdenny** [comment]
I have a problem using EntityFramework tools (both dotnet and powerhsell) after upgraded to netcore `1.1.0` using Swashbuckle `6.0.0-beta902`, I get this error:

> An error occurred while calling method 'ConfigureServices' on startup class 'Startup'. Consider using IDbContextFactory to override the initialization of the DbContext at design-time. Error: Could not load file or assembly 'Microsoft.Extensions.DependencyInjection.Abstractions, Version=1.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

It's strange because at runtime everything seems to work fine, but the startup fail to work when called from dotnet tools, so *the actual workaround is to create a `IDbContextFactory`* but in that way you have to figure out a custom configuration.

This is how it looks like on visual studio references:

![image](https://cloud.githubusercontent.com/assets/1633595/20887556/616bd050-bafb-11e6-8896-3f7622d24548.png)
