### ISSUE TITLE
array of objects property in multipart/form-data (FormForm)

### ISSUE THREAD

**Issue by namighajiyev** [domaindrivendev/Swashbuckle.AspNetCore#2399]
Hi,

I am posting an object with property that is an array of objects. When  I execute method I get an empty array/ienumerable for **"NestedList"** property even though I have added two items in the UI.

```
public class NestedRequest {
    public int MyProperty { get; set; }
}
public class SampleRequest
{
  public IEnumerable<NestedRequest> NestedList { get; set; }= null!;
}

  [HttpPost()]
  public async override Task<ActionResult> HandleAsync([FromForm] SampleRequest request, CancellationToken cancellationToken = default)
  {
    return await Task.FromResult(new OkResult());
  }
```
![sample-endpoint](https://user-images.githubusercontent.com/9103265/162892724-5907e7ab-65e8-4161-a291-923c6424b3b4.PNG)

**Comment by gabrieldrozd** [comment]
@namighajiyev 
Managed to find a solution?

I'm struggling with this at the moment and don't know how to resolve this issue :/

**Comment by jpnant** [comment]
Since you are using `multipart/form-data` each element in your request needs to be a unique element in your "form".
So a possible workaround is to use an index for each element in your collection, then the name for each of its properties.
In your case something like : 

![Screenshot 2024-01-17 170341](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/18204062/0eb52634-32dd-4319-b92d-0f47ecf7d67f)

**Comment by jpnant** [comment]
Same here, the `IFormFileCollection` is not properly showing up on swagger. Anyways, I came up to get it works using `IEnumerable<IFormFile>` :
![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/18204062/0bce09af-2c0e-4c22-b053-2f42b7f7cbea)
In my case I also have a `[Consumes("multipart/form-data")] `over the endpoint, and it's a `[HttpPost]`, not a `[HttpPut]`.
Hope It helps !
