### ISSUE TITLE
Issue with authorizations after upgrade to v6.3.2

### ISSUE THREAD

**Issue by marcominerva** [domaindrivendev/Swashbuckle.AspNetCore#2459]
Using Swashbucke.AspNetCore v6.3.1, I have configured authorizations so that I have an **Authorize** button that, once clicked, shows up the following option (I'm using Azure AD authentication):

![image](https://user-images.githubusercontent.com/3522534/179201338-ff466189-abe0-4a6f-a2b9-3a8aeb98758e.png)

After upgrading to v6.3.2, with no changes in my code, a new authorization option now appears at bottom (**Bearer (http, Bearer)**):

![image](https://user-images.githubusercontent.com/3522534/179201865-c0315871-8ff4-40f6-b2af-b491a1a68942.png)

Is there an issue with the last version?
Kindest regards.

**Comment by agilenut** [comment]
I'm having the same issue... and this is just a patch release

**Comment by captainsafia** [comment]
> is there an issue that we can track these changes against (assuming that they get reverted)?

We can probably use this issue to track changes in this behavior. You might also be interested in taking a look at https://github.com/dotnet/aspnetcore/issues/39761 which captures some work we're hoping to do to make authentication configuration in ASP.NET apps more introspectable so its easier to automatically generate the `OpenApiSecurityScheme` definitions given a particular application.

There are some patterns in ASP.NET authentication that make this challenging, including one that played a role in this bug here. The scheme name is used as the unique identifier for authentication strategies registered within an app, but the scheme name doesn't necessarily reflect the scheme strategy. For example, I can use the `Bearer` scheme name for both an in-dev JWT-bearer based strategy and an Azure AD-auth strategy as seen here. Amongst other things, this means the information you get from `IAuthenticationSchemeProvider` might not be helpful enough for modifications you want to make in filters, etc.

**Comment by domaindrivendev** [comment]
@richtea - A lot of these features are being driven by the ASP.NET Core team. Going forward, I've asked them to create an issue in _this_ repo before designing and submitting PRs. This way, I hope it will raise visibility and give more opportunity for myself and others to provide earlier feedback into the design.

Re your suggestion, I've applied it to #2460. Feel free to take a look and provide any further feedback you might have, keeping in mind that I'd like to get that out sooner rather than later. In the meantime, I will de-list the current "breaking" patch on nuget.

**Comment by pinkfloydx33** [comment]
We have a lot of infrastructure around building our API spec the way we want it (**lots** of filters!). One thing we control is how security schemes are presented/generated. We generate different requirements when running behind our api gateway (which transforms headers) vs locally vs self-hosted, etc. Our applications are able to deduce the environment/setup and know what specification to generate and also how to properly handle the differences (custom authorization headers, for ex.)

I just spent the last two hours trying to figure out why my app was crashing after the update in one of the scenarios. After stepping through each filter and inspecting my security schemes multiple times, they were always filled in the way I wanted but then **reverted** to what I'm guessing is this infered usage.

Technically all my scenarios were broken (had I tried the swagger UI) but only one was throwing errors. I'm glad it did because it surfaced a null-ref bug and ultimately drew me to the changelog that dependabot included in its PR. 

This is however totally unacceptable! If I spend the cycles to customize the swagger generated document, **nothing** should automatically be overriding it. And such a change on a patch release is even worse.

1. Is there an ETA on the opt-in/patch?
2. Can I opt-out currently?
3. Even with opt-in inference, I don't believe it should be *clearing* any schemes that were manually added. Inference should be an add-on, not a wipe-out
4. How to prevent upstream "optimizations" from wiping out our carefully crafted specification automatically in the future? We are intentionally **not** using minimal APIs; they shouldn't be overriding the behavior of my app.

**Comment by richtea** [comment]
> Feel free to take a look and provide any further feedback you might have, keeping in mind that I'd like to get that out sooner rather than later.

@domaindrivendev that looks great, it addresses the key principle behind my concerns, which is to ensure that filters can get a bite at whatever the framework has provided. I'm keen on the idea of automatic discovery, but there are always likely to be corner cases that will require 'manual' intervention!

**Comment by domaindrivendev** [comment]
@marcominerva @agilenut @richtea I've merged [the PR that makes this opt-in and ensure filters execute at the right time](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2460), and have published a `6.4.0` preview package to myget.org. Before I publish to nuget.org, could one or two of you pull down the latest preview package and ensure it doesn't break your existing auth stuff.

https://myget.org/feed/domaindrivendev/package/nuget/swashbuckle.aspnetcore

**Comment by marcominerva** [comment]
@domaindrivendev I have just installed `v6.4.0-preview` in the project in which I have seen the issue and now it works as expected. Thank you very much!

**Comment by agilenut** [comment]
@domaindrivendev, I've also tested `v6.4.0-preview` in my project and it is working as expected.

**Comment by domaindrivendev** [comment]
OK will go ahead and publish - thx for the help in ironing this one out 👍

**Comment by richtea** [comment]
Apologies, I missed this yesterday, but I can confirm that version 6.4.0 works for me, many thanks :thumbsup:
