### ISSUE TITLE
JSON $schema in swagger.json

### ISSUE THREAD

**Issue by agilenut** [domaindrivendev/Swashbuckle.AspNetCore#2479]
Is it possible to have Swashbuckle output a swagger.json file with the $schema property so that editors correctly validate the JSON schema?

By default, Visual Studio seems to try to validate against [the 2.0 schema](https://json.schemastore.org/swagger-2.0.json) which creates a lot of validation errors. 

I assume it should reference: [the 3.0 schema](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.0/schema.json). However, when using that, I get several errors stating "$ref is required" and "object should not contain additional properties".

If I use [the 3.1 schema](https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/schemas/v3.1/schema.json), then I only get 1 error regarding the value of the "openapi" version number. 

It would be great if the swagger.json file automatically included the correct $schema reference and it would validate.

**Comment by martincostello** [comment]
Assuming this isn't frowned upon in OpenAPI documents this seems reasonable so a JSON editor can do schema validation of the schema (whoa, meta) without having to understand it's an OpenAPI document first.

However, without me checking the code, there's a good chance this would need to be implemented in Microsoft.OpenAPI, rather than in Swashbuckle.
