### ISSUE TITLE
Inheritance hierarchy not flattened by default

### ISSUE THREAD

**Issue by Yakimych** [domaindrivendev/Swashbuckle.AspNetCore#2514]
According to the docs:
> By default, Swashbuckle flattens inheritance hierarchies. That is, for derived models, the inherited properties are combined and listed alongside the declared properties.

However, when using the Shape-Rectange-Circle hierarchy (as in the [tests](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/test/WebSites/Basic/Controllers/PolymorphicTypesController.cs)), the schema generated with `Swashbuckle.AspNetCore.Swagger v6.4.0` still includes the base (parent) fields via allOf.

**Expected**: `name` and `typeName` to end up under `Circle` -> properties.
**Actual**: `allOf` that references `Shape` is under `Circle`, despite **not** calling `c.UseAllOfForInheritance()` in the code.

```
openapi: 3.0.1
info:
  title: 'WebApplication1, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
  version: '1.0'
paths:
  /Shapes:
    get:
      tags:
        - Shapes
      operationId: GetShape
      responses:
        '200':
          description: Success
          content:
            text/plain:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Rectangle'
                  - $ref: '#/components/schemas/Circle'
            application/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Rectangle'
                  - $ref: '#/components/schemas/Circle'
            text/json:
              schema:
                oneOf:
                  - $ref: '#/components/schemas/Rectangle'
                  - $ref: '#/components/schemas/Circle'
components:
  schemas:
    Circle:
      type: object
      allOf:
        - $ref: '#/components/schemas/Shape'
      properties:
        radius:
          type: integer
          format: int32
      additionalProperties: false
    Rectangle:
      type: object
      allOf:
        - $ref: '#/components/schemas/Shape'
      properties:
        height:
          type: integer
          format: int32
        width:
          type: integer
          format: int32
      additionalProperties: false
    Shape:
      required:
        - typeName
      type: object
      properties:
        typeName:
          type: string
        name:
          type: string
          nullable: true
      additionalProperties: false
      discriminator:
        propertyName: typeName
        mapping:
          Rectangle: '#/components/schemas/Rectangle'
          Circle: '#/components/schemas/Circle'
```

Here is an (almost) minimal repro with .NET 6 (Program.cs):
```
using Microsoft.AspNetCore.Mvc;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddSwaggerGen(c =>
{
    c.UseOneOfForPolymorphism();

    c.SelectDiscriminatorNameUsing((baseType) => "typeName");
    c.SelectDiscriminatorValueUsing((subType) => subType.Name);
});

var app = builder.Build();

app.UseSwagger();
app.UseSwaggerUI();

app.UseHttpsRedirection();
app.UseAuthorization();
app.MapControllers();

app.Run();

[ApiController]
[Route("[controller]")]
public class ShapesController : ControllerBase
{
    [HttpGet(Name = "GetShape")]
    public Shape GetShape() => new Rectangle {Height = 10, Width = 5};


    public abstract class Shape
    {
        public string Name { get; set; }
    }

    public class Rectangle : Shape
    {
        public int Height { get; set; }

        public int Width { get; set; }
    }

    public class Circle : Shape
    {
        public int Radius { get; set; }
    }
}
```

And here is the `WebApplication1.csproj` file:
```
<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <TargetFramework>net6.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="Newtonsoft.Json" Version="12.0.2" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
        <PackageReference Include="Swashbuckle.AspNetCore.Swagger" Version="6.4.0" />
    </ItemGroup>
</Project>
```

**Comment by danielcrabtree** [comment]
I can confirm this bug occurs on v6.5.0 as well.

The issue lies in `Swashbuckle.AspNetCore/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/SchemaGenerator.cs`.

Wherein if `UseOneOfForPolymorphism` OR `UseAllOfForInheritance` is set, then the other is treated as though it were enabled as well due to line 353: `if (_generatorOptions.|| _generatorOptions.UseOneOfForPolymorphism)`.

In the current design, `UseOneOfForPolymorphism` relies on the fact that `UseAllOfForInheritance` is enabled, as it adds the discriminator properties into the `BaseType` and assumes these will be inherited via `AllOf`.

The fix is to use the current design for when both `UseOneOfForPolymorphism` AND `UseAllOfForInheritance` are enabled and to implement a new design for when only `UseOneOfForPolymorphism` is enabled.

This new design would need to add the discriminator properties to all the `SubTypes` rather than to just the `BaseTypes`. It may also need changes to ensure the Mapping goes to each `SubType` as well.

**Comment by danielcrabtree** [comment]
I have submitted a Pull Request #2683 that fixes this bug.

**Comment by martincostello** [comment]
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2683#issuecomment-2053570703

**Comment by cremor** [comment]
Not stale, @leth is working on it in #2940

**Comment by leth** [comment]
I've rebased @danielcrabtree's code in PR #2940, but unfortunately I'm stuck now.
I don't understand the different scenarios and what works well with consuming tools in order to make a good call on how to resolve the failing unit tests well.

I think I need someone who has a better understanding of the overall picture to carry this on.
