### ISSUE TITLE
Newtonsoft UnixDateTimeConverter is not respected

### ISSUE THREAD

**Issue by lus** [domaindrivendev/Swashbuckle.AspNetCore#2608]
I set up SwaggerGen with Newtonsoft support like this:

```cs
builder.Services.AddSwaggerGen(options =>
{
    string filename = $"{Assembly.GetExecutingAssembly().GetName().Name}.xml";
    options.IncludeXmlComments(Path.Combine(AppContext.BaseDirectory, filename));
});
builder.Services.AddSwaggerGenNewtonsoftSupport();
```

Newtonsoft is configured like this:

```cs
builder.Services.AddControllers().AddNewtonsoftJson(options =>
{
    options.SerializerSettings.Converters.Add(new StringEnumConverter(typeof(CamelCaseNamingStrategy)));
    options.SerializerSettings.Converters.Add(new UnixDateTimeConverter());
    options.SerializerSettings.ContractResolver = new DefaultContractResolver
    {
        NamingStrategy = new SnakeCaseNamingStrategy(),
    };
});
```

In the example response I see that both the `SnakeCaseNamingStrategy` and my custom `StringEnumConverter` are correctly applied, but the `UnixDateTimeConverter` seems to be ignored as `DateTime`s still get represented as strings.
Am I missing something or is this a bug?

I am using `Swashbuckle.AspNetCore` and `Swashbuckle.AspNetCore.Newtonsoft` version `6.5.0`.

**Comment by lus** [comment]
I managed to find a temporary workaround for my issue.
I created the following schema filter that converts all `date-time` values to `int64` ones:

```cs
public class DateTimeFilter : ISchemaFilter
{

    public void Apply(OpenApiSchema schema, SchemaFilterContext context)
    {
        foreach (KeyValuePair<string, OpenApiSchema> property in schema.Properties)
        {
            if (property.Value.Format != "date-time")
            {
                continue;
            }

            property.Value.Type = "integer";
            property.Value.Format = "int64";
            property.Value.Example = new OpenApiLong(1676290252);
        }
    }

}
```

I don't think this is a good permanent solution though, so I hope to find a more elegant way for that soon.

**Comment by jgarciadelanoceda** [comment]
I have been studying this issue and the issue is right.
I have solved right now supporting this converter, but not sure about introducing this into the library

**Comment by martincostello** [comment]
I think I agree. System.Text.Json doesn't have first-class support for such functionality either, [suggesting a custom converter](https://learn.microsoft.com/dotnet/standard/datetime/system-text-json-support#use-unix-epoch-date-format), so we couldn't have parity.

Enums are already special-cased, but that's because they're a lot more ubiquitous(?). Also naming is a bit of a different customisation proposition, as IIRC, there's APIs to effectively query the serializer to get the name for a property, where as getting the format of how a value of a property serialized is much more difficult as you also need a value of that type to test against.

Supporting various custom converters, even if they're built in, could be a bit of a slippery slope ([Newtonsoft.Json appears to have 16](https://github.com/JamesNK/Newtonsoft.Json/tree/master/Src/Newtonsoft.Json/Converters)), so where do we draw the line? If this can be resolved by using a schema filter by the user to get the correct behaviour, then I think that's enough.
