### ISSUE TITLE
Open Api Specification contains non APIController routes when using the Asp.Versioning.Mvc package

### ISSUE THREAD

**Issue by mstypsan** [domaindrivendev/Swashbuckle.AspNetCore#2681]
This is an issue related with the `Asp.Versioning.Mvc` package. The older `Microsoft.AspNetCore.Mvc.Versioning` (version 5.0.0) package is filtering out Controllers without the `ApiController` attribute. Which means that the Open Api Specification will not contain the non-API controllers. This is not the case if we update to the latest and renamed version of the `Asp.Versioning.Mvc` package (version 6.0.0 and above). For a given version (ex. v1) if we have 2 Controllers one marked as `ApiController` and the other without this attribute, then the open api specification will contain the routes of both Controllers. 
The `Swashbuckle.AspNetCore` version is 6.5.0

With Controllers
```
[ApiVersion("1.0")]
[Route("[controller]")]
public class FirstController
{
    [HttpGet]
    public IEnumerable<string> GetProducts()
    {
        return new[]
        {
            "one"
        };
    }
}
```
and 
```
[ApiVersion("1.0")]
[ApiController]
[Route("[controller]")]
public class SecondController
{
    [HttpGet]
    public IEnumerable<string> GetItems()
    {
        return new[]
        {
            "first", "second"
        };
    }
}
```
if update to latest version of the `Asp.Versioning.Mvc` package and register its services as `services.AddApiVersioning().AddMvc().AddApiExplorer();`

we will notice that both controllers are included in the Open Api Specification. 
It seems that this should not be the case because it doesn't work like that if we use the older `Microsoft.AspNetCore.Mvc.Versioning` package.

**Comment by martincostello** [comment]
@commonsensesoftware this one looks like it's in your wheelhouse.

**Comment by commonsensesoftware** [comment]
@mstypsan,

Succinctly, this is not an issue with Swashbuckle.

The API Explorer extensions for API Versioning do not exactly care about `[ApiController]`. In ASP.NET Core, a controller is a controller. In the early days, it was a lot more ambiguous to disambiguate between an API controller and a UI controller. In ASP.NET 2.1/2.2, _API Behaviors_ were added, which includes the `[ApiController]`. This lead to the possibility of more sensible _conventions_ for API Versioning. The design was enhanced to support the services `IApiControllerFilter`, which filters the controllers that should be considered, and `IApiControllerSpecification`, which determines whether a particular controller is an API controller. The default filter is just a collection of specifications. There is built-in specification that matches whether a controller has _API Behaviors_ applied (a la `[ApiController]`) and one that matches OData routing. It's even possible to go back to _no filter_, which would version all controllers. Versioning UI controllers seems a bit odd though.

It's been a couple of years now, but there was bug uncovered in the API Explorer extensions that was filtering out unversioned controllers. It's a bit of a strange use case, but ultimately the API Explorer extensions shouldn't be filtering out results it doesn't understand. Any such results are now retained. I suspect that has led to the discovery of a schroedinbug in your code.

As defined above, `FirstController` is **not** an API controller. Adding `[ApiVersion]` is just metadata and that doesn't include it in anything. Also keep in mind that `[ApiController]` can be applied at the controller level or for the whole assembly (e.g. `[assembly: ApiController]`). If you see `FirstController` only appear in `1.0`, then you have it applied at the assembly level. If you see it appear in every version and OpenAPI document, then that is the expected behavior because even tough it has `[ApiVersion("1.0")]`, the controller is not actually an API controller and it doesn't pass the default filter's set of specifications. I'm not sure of the intent of `[ApiVersion]` on `FirstController` if it's not supposed to be an API controller. If you want this controller excluded from the OpenAPI document and Swashbuckle, you should apply `[ApiExplorerSettings(IgnoreApi = true)]` to `FirstController`.

**Comment by mstypsan** [comment]
@commonsensesoftware thank you for the detailed clarification. I guess the confusion was because we would see different behaviour for the OpenAPI document depending on whether the Controller has the `ApiController` attribute or not.
