### ISSUE TITLE
What if a few responses can be produced for one code?

### ISSUE THREAD

**Issue by xperiandri** [domaindrivendev/Swashbuckle.AspNetCore#269]
``` C#
[AllowAnonymous]
[HttpPost("[action]")]
[Consumes("application/x-www-form-urlencoded")]
[ProducesResponseType(typeof(void), (int)HttpStatusCode.Created)]
[ProducesResponseType(typeof(IdentityError[]), (int)HttpStatusCode.BadRequest)]
[ProducesResponseType(typeof(ModelStateDictionary), (int)HttpStatusCode.BadRequest)]
public async Task<IActionResult> Register(
```
This displays only a single entry for bad request in Swagger UI

**Comment by erendrake** [comment]
I am curious to see what kind of swagger document you would expect to come out when you do this. could you give us an example?

**Comment by tillig** [comment]
I'm also curious since it [doesn't look like the Swagger spec supports such a thing](http://swagger.io/specification/#responsesObject).

**Comment by xperiandri** [comment]
It is not a problem technically 
``` JSON
{
  "304": [
    {
    "description": "error1",
    "schema": {
      "$ref": "#/definitions/IdentityError[]"
    },
    {
    "description": "error2",
    "schema": {
      "$ref": "#/definitions/ModelStateDictionary"
    }
  ]
  },
```

**Comment by tillig** [comment]
I don't think Swagger allows the value associated with a response code to be an array.

**Comment by sandorfr** [comment]
In addition, if it were allowed, I don't see how one would implement a typed client reliably.
From where I stand and what I guess from your types:
* error1 should be a 403 or a 401 depending on the cause (forbidden / unauthorized)
* error2 should be a 400

(In addition there is something weird with your last sample, ` 304`  stands for `Not Modified` which is a success code for a conditional get. )

**Comment by xperiandri** [comment]
I know, but what should I use to state that operation completed successfully but nothing was modified?

**Comment by xperiandri** [comment]
> error1 should be a 403 or a 401 depending on the cause (forbidden / unauthorized)

Method does registration. Identity error states that there is some registration condition not satisfied. There is nothing about inability to perform a request because of authorization or authentication.

**Comment by tillig** [comment]
I think we're getting a little of the beaten path. How to express something in a RESTful fashion is a great thing to ask on StackOverflow - it may not even be .NET specific.

This issue asked how to express multiple responses with a single status code, which I don't think is supported by Swagger and is also probably not great contact design. Can the issue be closed?

**Comment by sandorfr** [comment]
@tillig from where I stand this can be closed. And it is also not .net or swashbuckle specific.

@xperiandri regarding 304, it is really tied to modified-since / etag mechanisms. I think (personal opinion here) that when defining REST contracts we should stick to the [RFC](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html) as browser or consumers might have automatic behavior (such as caching). I think telling nothing is modified would be the responsibility of an ETag or Date header

On the creation matter, either it's a data validation issue and it should be a badrequest or it is an already existing user (I would use `409` `Conflict`). Other errors are probably unexpected and might deserve a 500.

Beside the statuscode point, I generally found that having inconsistent errors paylod was highly inconvenient. I also think that exposing message from a random exception or indentity errors might expose sensitive informations. So what I usually do is what follows use a single flexible enough Error Contract in every situation.

example : json
```
{
  "status": {
    "code": 401,
    "requestId": "Smj.jOmjfXwo6jUC9pwL1V",
    "explanation": {
      "message": "You cannot be anonymous.",
      "type": "ShouldProvideIdentity"
    }
  }
}
```

**Comment by domaindrivendev** [comment]
Not a SB issue
