### ISSUE TITLE
registration of SwaggerUIOptions

### ISSUE THREAD

**Issue by AndrewTriesToCode** [domaindrivendev/Swashbuckle.AspNetCore#2692]
Where is the `SwaggerUIOptions` option configuration registered? In the snippet below it clearly is registered as `GetRequiredService` returns it but in searching the repo I can't find anywhere where the options are rendered.
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/src/Swashbuckle.AspNetCore.SwaggerUI/SwaggerUIBuilderExtensions.cs#L33

Thanks!

**Comment by AndrewTriesToCode** [comment]
Hi, thanks. 

Yeah I know I wouldn’t inject the options directly. What I’m saying is that looking at the source code I can’t find where they even configure these options as a type that can be injected via the Options pattern. The action passed into the middleware is used in the middleware but not used to register an ‘IConfigureNamesOptions’ implementation as far as I can tell.

**Comment by vdekercd** [comment]
It is not registered because it is not necessary.

It is injected only into the `SwaggerUIMiddleware` middleware, which is registered in the `UseSwaggerUI` method in which this option can be passed.  

However, you can save it yourself if necessary, as is done in [this example](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/8f363f7359cb1cb8fa5de5195ec6d97aefaa16b3/test/WebSites/ConfigFromFile/Startup.cs#L33C32-L33C48).
