### ISSUE TITLE
documentation added minlength = 1 for required properties

### ISSUE THREAD

**Issue by corleymanz** [domaindrivendev/Swashbuckle.AspNetCore#2732]
When upgrading from from 6.3.0 to 6.5.0 the documentation suddenly has a minlength = 1
Is this a bug or a feature? And if it is a feature, can i turn this off so minlength is not generated for required properties

I hav a .net 7 project with newtonsoft.json as serialiser

model
```
[Required]
public string test {get; set;}
```

generates documentation like
```
"test" : {
"minlength" : 1
"type" : "string"
}
```

i expected the documentation like (version 6.3.0)
```
"test" : {
"type" : "string"
}
```

**Comment by Havunen** [comment]
I believe this is feature, what is the reason to turn it off? If the string is required it cannot be null and so some string must be there

**Comment by marnilss** [comment]
> I believe this is feature, what is the reason to turn it off? If the string is required it cannot be null and so some string must be there

Even an empty string ( "" ) constitutes a string, so it fulfills the Required check. This was the old behavior.
But it will now fail the MinLength check. So it is a difference in behavior. 
BUT it actually makes sense, since the ASP.NET Core model binding implementation of the Required-attribute evaluates empty string as violations and will block them. 
So I think it is now better aligned with how ASP.NET works.
