### ISSUE TITLE
index.html flagged in pen test

### ISSUE THREAD

**Issue by ajberry** [domaindrivendev/Swashbuckle.AspNetCore#2755]
Hi, 

We have had a web service pen tested recently and the swagger index.html was flagged as not providing the relevant hsts headers. 

The endpoints all provide them, and we have used the following snippet to add them: 

```
services.AddHsts(options =>
                    {
                        options.IncludeSubDomains = true;
                        options.MaxAge = TimeSpan.FromDays(securityConfiguration.MaxAge);
                    })
                    .AddHttpsRedirection(options =>
                    {
                        options.RedirectStatusCode = (int)HttpStatusCode.TemporaryRedirect;
                        options.HttpsPort = securityConfiguration.HttpsPort;
                    });
```

But this doesn't add it in for the index.html page. 

We have also tried to use 

```
app = appBuilder.Build();
serviceProvider = app.Services;
apiVersionDescriptionProvider = serviceProvider.GetRequiredService<IApiVersionDescriptionProvider>();
app.SetupSwagger(apiVersionDescriptionProvider, "./Assets/custom-ui.css");
app.SetupSecurity();
await app.RunAsync();
```

But again, this doesn't apply it to the index.html page. Obviously I know the index.html page can't actually do anything at all, but it would be nice to be able to set this flag to appear on the index.html page itself as we need to clear the medium risk on the pen test.

I did see the other issue logged a few years back, but there didn't seem to be a resolution to the issue, and the suggested fix seemed to only refer to endpoints. (https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/1737)

**Comment by Havunen** [comment]
You just need to add HstsMiddleware before swagger UI and that's it.

in your Program.cs do:
```cs
app.UseHsts();

// swagger ui
```

then it will add the header, check the source code it is very simple: https://github.com/dotnet/aspnetcore/blob/main/src/Middleware/HttpsPolicy/src/HstsMiddleware.cs#L76

**Comment by martincostello** [comment]
As noted above, this will likely be caused by ordering of middlewares and static files being placed before the HSTS middleware.

I'd be skeptical of HSTS headers being missing from a Swagger UI page being an _actual_ practical security issue compared to the blanket binary approach taken by most security scanning software. I would go down the route of getting an exemption for the endpoint flagging this problem.

I'm going to close this, but if you can't resolve this with reordering your middlewares, feel free to raise a new issue.
