### ISSUE TITLE
Why is this project so inactive from past year?

### ISSUE THREAD

**Issue by nithinbandaru1** [domaindrivendev/Swashbuckle.AspNetCore#2759]
I do not see any new commits on this repo for almost a year now.

Probably you guys should ask for new maintainers to come in ofcource if current maintainer is willing to take new maintainers.

I see some PRs that are ready to be merged but not sure why they are not being merged yet.

**Comment by soroshsabz** [comment]
ITNOA

@domaindrivendev Did you have any note about this issue?

Did you can add some collaborators?

**Comment by soroshsabz** [comment]
for example you can add https://github.com/mattfrear as collaborator

**Comment by ramondeklein** [comment]
@nithinbandaru1 It's pretty clear that this repo is very active, but it seems it's not maintained anymore for the past year. I'm concerned about it too, but submitting an issue with all capitals won't motivate any maintainer. That's why I downvoted it.

The reason why I think Microsoft should step in, is because they actively promote this package in the [Learn ASP.NET Core documentation](https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle). That's one of the reasons why we started using it. We were not alone, because this module is in the top 25 list of most used .NET Core packages. If we knew it was a one-man project (at least the maintainer), then we might have choosen something else.

Being a developer of a highly popular project is probably hard. It requires a lot of dedication, with hardly any benefits. That's also one of the reasons why the developer's of [Identity Server](https://github.com/IdentityServer/IdentityServer4) have gone commercial. There are not a lot of companies that sponsor open-source projects.

**Comment by nithinbandaru1** [comment]
Sure, Internet has a different story about this repo.

- <https://www.reddit.com/r/dotnet/comments/188nfpp/should_we_be_concerned_about_swashbuckle/>
- <https://learn.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-7.0&viewFallbackFrom=aspnetcore-2.2&tabs=visual-studio>
- <https://github.com/dotnet/aspnetcore/issues/4854>
- <https://github.com/dotnet/AspNetCore.Docs/issues?q=is%3Aissue+is%3Aopen+NSwag>

**Comment by mlapaglia** [comment]
"Swashbuckle is not supported in .NET 8 and later. For a supported alternative, see [ASP.NET Core web API documentation with Swagger / OpenAPI](https://learn.microsoft.com/en-us/aspnet/core/tutorials/web-api-help-pages-using-swagger?view=aspnetcore-7.0)." could be why?

**Comment by schnerring** [comment]
Sorry for adding to the notification noise. I know Reddit or Twitter are better platforms for ranting:

@nithinbandaru1 If the "internet already has a different story", re-iterating the same point with an uppercase-titled issue has zero value. Everybody can see the concerned comments, as well as everybody can see that the maintainer is inactive. You're not stressing any point, you just stress the maintainers.

Ever had a growing pile of paperwork you had to get through? As the pile grows, do you feel more motivated to churn through it?

Equally annoying are pure "+1 comments". All it does is add to the constant stream of notifications maintainers have to get through. As an open-source contributor, one of my key burn-out factors are notifications, and having to constantly filter them and find the stuff that's relevant. If you wanna +1 an issue, please 👍 the issue, because one can actually sort issues by that metric, and it doesn't cause notifications. IMHO, and unless the contribution guidelines of a repo tell you otherwise, it's good etiquette to only comment on an issue, if the comment helps resolving the issue.

Have you had a look at NSwag repo? It has a bazillion open issues. A ton of them could be closed, because they're low effort and don't have any value. [But what can you do if you constantly drown in hundreds of notifications?](https://github.com/RicoSuter/NSwag/issues/2404#issuecomment-700698714) Just ignore them and not do any triage.

**Comment by nithinbandaru1** [comment]
@schnerring

Well, I really don't mind your opinions. All I care is about the status of this repo.

I think the maintainer is not going to be stressed with this 🤔🤔.  If in-case he comes across this issue, he will announce for maintainers if he wants this lovely project to be alive or leave it to die. Both are good for community to have an answer, Because of this issue maintainer is not going to merge all PRs by taking stress on him.

Reaction for comments gives notifications. Interesting I did not get any of such. Something new 😁. Let me check.]

NSwag repo is of multiple tools set, obviously it will have many issues compared to this repo. But in terms of swagger generation it almost similar.

Well, I don't need your suggestion to fork and become maintainer, if I had intentions to become maintainer I would have already asked. What I said is making an announcement like the maintainer did in his other repo will probably make this repo active again if someone comes in to take it up. I think that's how opensource can be alive, it's impossible for 1 person to keep it going. NSwag also have to do it at some point.

To be clear: I **never** have any **intentions** to **insist, insult, stress** maintainer to work on this repo. All I said is there is one last action that maintainer can take as he is too busy with other things in life. By the way I will have 0 benefits of this repo being alive in my life.

**Comment by Havunen** [comment]
I created a fork of this repository, because I couldn't wait for the maintainer of this repo. 
The fork is called DotSwashbuckle https://github.com/Havunen/DotSwashbuckle it only supports .NET 8 for now.

Change the csproj nuget reference 
```patch
-<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
+<PackageReference Include="DotSwashbuckle.AspNetCore" Version="1.0.2" />
```

Install the dotnet tool
```
dotnet tool uninstall --global Swashbuckle.AspNetCore.Cli
dotnet tool install --global --version 1.0.2 DotSwashbuckle.AspNetCore.Cli
```

1.0.2 is the first working version.

I am planning to maintain that repository at least until this repository picks up with the development, so if you are interested using it you can post issues or open PRs there.

**Comment by martincostello** [comment]
FWIW, [NSwag](https://github.com/RicoSuter/NSwag) is actively maintained and supports the typical OpenAPI use cases.

If you haven't made a significant investment in Swashbuckle-specific features, migrating to NSwag isn't a massive change on a _per-repository_ basis ([example](https://github.com/martincostello/dotnet-minimal-api-integration-testing/pull/989)). Of course if you've used it in hundreds of repositories that's a different matter.

I've migrated all of the apps I personally maintain to NSwag as it at least has active development.

**Comment by domaindrivendev** [comment]
I appreciate [this comment](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2759#issuecomment-1900088302) by @ramondeklein more than anyone could imagine. The journey I've take with Swashbuckle has been amazing but has also left me somewhat disillusioned with open-source, particularly from the perspective of maintainers/authors.

Not saying it's apparent in this thread but the "entitlement" I've witnessed over the years from users of this software has at times left me gobsmacked. Furthermore, I can't escape the sense that the biggest benefactors of OS tends to be companies driving profit. Sure it helps fellow devs and that's great but ultimately that just helps the companies those fellow devs work for. And, while there's some lip-service from _some_ of those companies around sponsorship etc., in reality I've never seen it amount to anything more than a drop in the ocean vs the personal hours and value created - at least not in my experience.

Anyway, with all that said, I'm afraid I cannot justify giving any more of my time to this project. I'm chatting with one or two potential owners to transition it to - one in particular I feel would be an awesome fit. So hopefully will have an update on that soon. And, if that falls through, I'll renew the call for maintainers from the community and try be more responsive to get that squared away quickly so hopefully the project can start to thrive again.

**Comment by soroshsabz** [comment]
new version of [https://www.nuget.org/packages/dotswashbuckle.aspnetcore/]([DotSwashbuckle) was released with merge many of PRs in this repo.

Thanks, and Congratulation to @Havunen

**Comment by soroshsabz** [comment]
@domaindrivendev very thanks for all of your works in many years :)

Surely you yourself know well, but from my point of view @Havunen and @mattfrear are very good options for collaborator of this repo

**Comment by mareek** [comment]
> Anyway, with all that said, I'm afraid I cannot justify giving any more of my time to this project. 

Thanks for your answer @domaindrivendev.
Can you update the README.md file to notice that this project is on hold while you're searching for a new maintainer ?
This would be helpful to people who expect some pull request fixing a bug will be merged in the near future

Thanks in advance.

**Comment by VictorioBerra** [comment]
Just want some clarification @Havunen should we be using https://github.com/Havunen/DotSwashbuckle or are you taking over this repo and we can stay on https://github.com/domaindrivendev/Swashbuckle.AspNetCore ?

**Comment by Havunen** [comment]
I don't have any access to this repository, appveyor or nuget.org, so I will continue developing my fork

**Comment by Herve-M** [comment]
> FWIW, [NSwag](https://github.com/RicoSuter/NSwag) is actively maintained and supports the typical OpenAPI use cases.
> 
> If you haven't made a significant investment in Swashbuckle-specific features, migrating to NSwag isn't a massive change on a _per-repository_ basis ([example](https://github.com/martincostello/dotnet-minimal-api-integration-testing/pull/989)). Of course if you've used it in hundreds of repositories that's a different matter.
> 
> I've migrated all of the apps I personally maintain to NSwag as it at least has active development.

NSwag is nice but documentation is 50/50 contrary to Swashbuckle :/

**Comment by domaindrivendev** [comment]
> I don't have any access to this repository, appveyor or nuget.org, so I will continue developing my fork

@Havunen fyi I messaged you on LinkedIn to discuss the possibility of contributing to this repo instead of forking. Let me know if you're interested?

**Comment by soroshsabz** [comment]
@Havunen Did you can see @domaindrivendev message?

thanks

**Comment by jonashendrickx** [comment]
I would be willing to step up as a maintainer if there is absolutely nobody else. I absolutely love the work that has been done here, and there's nothing like it that comes even remotely close.

**Comment by harvzor** [comment]
For those of you considering NSwag, I've done a high level comparison of the two projects: https://github.com/harvzor/swashbuckle-vs-nswag/

However, I'm looking forward to development on the forks of this project

**Comment by harvzor** [comment]
Also it looks like Microsoft plans on implementing their own Swagger implementation for dotnet 9: https://github.com/dotnet/aspnetcore/issues/54599

**Comment by jonashendrickx** [comment]
They seem to have started the work. Seeing a couple open pull requests.

**Comment by domaindrivendev** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/discussions/2778
