### ISSUE TITLE
DateOnly not rendering correctly in Swagger

### ISSUE THREAD

**Issue by mattjohnsonpint** [domaindrivendev/Swashbuckle.AspNetCore#2771]
I _think_ this may be a regression of #2319, but in investigating [this stackoverflow question](https://stackoverflow.com/q/77834867/634824), I found that `DateOnly` fields are still not showing correctly in the Swagger UI in ASP.NET 8 latest.

To reproduce:
- Download and install .NET 8  SDK 8.0.2 (SDK 8.0.201)
- `dotnet new webapi`
- `dotnet run`
- Browse to Swagger endpoint, i.e. `http://localhost:5261/swagger`

Notice `DateOnly` and  `DayOfWeek` have been broken out into properties as if custom types, rather than being a `date`.

<img width="424" alt="image" src="https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/1396388/e07ac0f0-f974-4fac-a363-8e92e2e9a446">

Apply the workaround:

```csharp
builder.Services.AddSwaggerGen(options => {
    options.MapType<DateOnly>(() => new OpenApiSchema { 
        Type = "string",
        Format = "date" });
});
```

Then it works:
<img width="406" alt="image" src="https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/1396388/b2c95aa5-7a51-4383-9541-b638a13c463f">

This shouldn't be necessary though, right?

**Comment by RandomBuffer** [comment]
Also experiancing this with Controllers, when I tried upgrading to **Swashbuckle.AspNetCore** 6.5.0 to fix **DateOnly** serialisation fixed in https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2319 but the **Swagger.json** broke with missing elements so I had to revert back to **Swashbuckle.AspNetCore** 6.4.0.

**Test**
1. Create a new Controller API project using the default template.
2. Upgrade to **Swashbuckle.AspNetCore** 6.5.0.
3. Enable **IncludeXmlComments** and wire it up.
4. Run project and notice **WeatherForecast** no longer shows up in the SwaggerUI schema section.

**dotnet --version**
`8.0.200`

**Comment by martincostello** [comment]
We should probably make a copy of WeatherForecast and add it to our integration tests, as it seems to come up often as the repro for issues 😄

**Comment by martincostello** [comment]
Looks like this will be resolved by #2799.

![image](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/assets/1439341/173a6eb7-631e-4823-9f4c-334b7b1220f1)

**Comment by martincostello** [comment]
#2799 and #2804 should fix this issue.

**Comment by johanvaneck** [comment]
It would be nice to have a default value that works out of the box, similar to System.DateTime 🙂

**Comment by cremor** [comment]
@johanvaneck Swashbuckle could in theory set an example value for all DateOnly fields. But it doesn't do it for DateTime fields either, that default value is created by Swagger UI. Therefore I think you should create an issue for that (or vote on an existing one) in the https://github.com/swagger-api/swagger-ui repository.
