### ISSUE TITLE
Missing response content element in swagger.json file when using IResult as return type

### ISSUE THREAD

**Issue by CzBuCHi** [domaindrivendev/Swashbuckle.AspNetCore#2818]
i have this controller:
```cs
[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase {

    [HttpPost("First")]
    [Consumes(MediaTypeNames.Application.Json, "application/example")]
    [Produces(MediaTypeNames.Application.Json, "application/example")]
    public int First([FromBody] string roleName) {
        return roleName.Length;
    }

    [HttpPost("Second")]
    [Consumes(MediaTypeNames.Application.Json, "application/example")]
    [Produces(MediaTypeNames.Application.Json, "application/example")]
    public IResult Second([FromBody] string roleName) {
         return Results.Ok(roleName.Length);
    }

}
```
which will generate this in swagger.json file:
```json
"paths": {
    "/WeatherForecast/First": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": { "schema": { "type": "string" } },
            "application/example": { "schema": { "type": "string" } }
          }
        },
        "responses": {
          "200": {
            "description": "Success",
            "content": {
              "application/json": { "schema": { "type": "integer", "format": "int32" } },
              "application/example": { "schema": { "type": "integer", "format": "int32" } }
            }
          }
        }
      }
    },
    "/WeatherForecast/Second": {
      "post": {
        "requestBody": {
          "content": {
            "application/json": { "schema": { "type": "string" } },
            "application/example": { "schema": { "type": "string" } }
          }
        },
        "responses": {
          "200": { 
              "description": "Success"
              // missing content element here
          }
        }
      }
    }
  }
```

as you can see in json there is missing 'content' element on response for method 'Second' ...

PS: goal is to have endpoint, that can handle json or binary request/response (json via swagger, binary from client)
PSS: Alternativequestion: how to set http status code in 'First' method? (so i can use it  instead of 'Second')

**Comment by martincostello** [comment]
See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/2481#issuecomment-2065822617 for a similar answer, but with Minimal APIs rather than controllers. By using an interface, you remove the ability for Swashbuckle to infer any information about what is returned because it can only analyse the static definition of the endpoints using reflection, it cannot analyse what happens at runtime or with code analysis to determine the actual result.

Consider either returning the actual type (your first option), or try using a more specific return type, such as `ActionResult<int>`.

If those don't meet your needs, you'll need to change your attributes to annotate the types that are returned, such as with [`[SwaggerResponse]`](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.Annotations/SwaggerResponseAttribute.cs), for example:

```csharp
[ApiController]
[Route("[controller]")]
public class WeatherForecastController : ControllerBase {
    [HttpPost("Second")]
    [Consumes(MediaTypeNames.Application.Json, "application/example")]
    [Produces(MediaTypeNames.Application.Json, "application/example")]
    [SwaggerResponse(200, "My endpoint", typeof(int), new[] { "application/example" })]
    public IResult Second([FromBody] string roleName) {
         return Results.Ok(roleName.Length);
    }
}
```

> PSS: Alternative question: how to set http status code in 'First' method?

You'll have to set it manually using `HttpContext` unless you use methods such as `Json()`.

```csharp
return Results.Json(roleName.Length, statusCode: 200);
```

**Comment by CzBuCHi** [comment]
after adding SwaggerResponse attribute swagger.json is correct, so im closing this .... but server is returning json even when i select "application/example" in media type combo  (request has -H 'accept: application/example') ... any ideas?
