### ISSUE TITLE
Different StringEnumConverter-Behavior between STJ / Newtonsoft

### ISSUE THREAD

**Issue by angelaki** [domaindrivendev/Swashbuckle.AspNetCore#2820]
Switching my project from Newtonsoft to STJ, I noticed the following different behavior between the two scheme generators:

Adding the `JsonStringEnumConverter` makes Swashbuckle aware of enums being serialized as string - so far, so good. But the STJ schema builder doesn't seam to be aware of `IDictionary<[Enum], int>`.

For Newtonsoft the following scheme was generated:

```
...
"properties": {
  "EnumValue1": {
	"type": "integer",
	"format": "int32"
  },
  "EnumValue2": {
	"type": "integer",
	"format": "int32"
  },
  "EnumValue3": {
	"type": "integer",
	"format": "int32"
  }
},
"additionalProperties": false,
...
```

Now I only get 

```
"additionalProperties": {
  "type": "integer",
  "format": "int32"
},
```

So it's still being recognized as an object containing integer properties. Better than nothing. But the old scheme was way more explicit.

**Comment by martincostello** [comment]
This might be related to https://github.com/dotnet/runtime/issues/47765 and this comment:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/a17b464184d4043c559e74e2c0d8596d7685cf63/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/JsonSerializerDataContractResolver.cs#L60-L67

It's possible this is fixed by #2799, otherwise we might have to see if there's any changes needed to if the assertion in that comment is no longer true.

**Comment by martincostello** [comment]
You may have to opt-in to this behaviour with [`JsonSerializerOptions.DictionaryKeyPolicy`](https://learn.microsoft.com/dotnet/standard/serialization/system-text-json/customize-properties#use-a-naming-policy-for-dictionary-keys).

**Comment by angelaki** [comment]
I could sure support here with a PR :) Can you give me a hint where to start?

**Comment by martincostello** [comment]
I'm not sure where specifically without starting to debug it myself.
