### ISSUE TITLE
[Feature request]: SwaggerIgnoreAttribute for FromForm requests

### ISSUE THREAD

**Issue by jgarciadelanoceda** [domaindrivendev/Swashbuckle.AspNetCore#2919]
### Is your feature request related to a specific problem? Or an existing feature?

I have seen that you added this PR:
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/2610

This PR adds the possibility of not loading certain properties in Swagger. With a previous version of the library I added a SchemaFilter and a OperationFilter to do this.

I needed to add a SchemaFilter for removing the property for a simple Json scenario, whereas for removing the property for a FromForm request I had to add the OperationFilter

### Describe the solution you'd like

I will like to use the Built in attribute for the FromForm swagger property ignoring, and I like the solution to work also with the Microsoft.AspNetCore.Mvc.FromFormAttribute.

If you find this addition interesting I am happy to contribute to this project

**Comment by martincostello** [comment]
Could you illustrate it with a simple code snippet here in this issue comparing how it looks now with what you're envisioning it would become?

From looking at what I can see, it looks more like a bug and the existing attributes you've added to the two DTO properties should already be hidden by `[SwaggerIgnore]`?

**Comment by jgarciadelanoceda** [comment]
@martincostello Do you see this as a bug? Yo start implementing the solution

**Comment by martincostello** [comment]
If you're trying to use `[SwaggerIgnore]` on a property of an object and it's not working, then I would consider it a bug. If you're trying to use it in another manner, or you're considering adding further new public API for your use case, then that's a feature.

If you're considering adding new public API to Swashbuckle, please propose something so we can agree on a design before you spend any time on implementation. Otherwise, feel free to raise a PR to make this work at your convenience.
