### ISSUE TITLE
[Bug]: Breaking: Writes default values for exclusiveMaximum/exclusiveMinimum to openapi.json

### ISSUE THREAD

**Issue by bkoelman** [domaindrivendev/Swashbuckle.AspNetCore#2959]
### Describe the bug

@jgarciadelanoceda Thanks for implementing #2958! I gave it a try today on our codebase using the MyGet feed.

Unfortunately, I'm getting test failures on `openapi.json` files that don't use `[Range]`. This is because `exclusiveMinimum` and `exclusiveMaximum` are being written even when set to `false`, or not set at all. In those cases, they should be omitted from the output `openapi.json`, because the default is already `false` in OpenAPI (and also in .NET).

### Expected behavior

No `"exclusiveMaximum": false, "exclusiveMinimum": false` when not using `[Range]` or the Exclusive* properties on `[Range]` are set to `false`.

### Actual behavior

The fragment `"exclusiveMaximum": false, "exclusiveMinimum": false` is written to output `openapi.json`, causing our assertions on the file contents to fail.

### Swashbuckle.AspNetCore version

latest master (2db53de)

### .NET Version

.NET 8

**Comment by jgarciadelanoceda** [comment]
Sorry but I do not see why if the values are set to false putting them in the Swagger is wrong. Could you elaborate a little more?
Because if it has a maximum and the maximum is not exclusive it should have the same behaviour that's having right now.
I will look at the other issue that is if you do not set the range at all, but it seems strange to me because the range parameters are only set when there's an attribute range

**Comment by bkoelman** [comment]
It's working great now, thanks!
