### ISSUE TITLE
Missing Authorization Header in Swagger UI After Upgrading Swashbuckle.AspNetCore from 6.5.0 to 6.6.1

### ISSUE THREAD

**Issue by PAVITHRA2999** [domaindrivendev/Swashbuckle.AspNetCore#3024]
# Issue
When upgrading from Swashbuckle.AspNetCore version 6.5.0 to 6.6.1, the Authorization header field disappears from Swagger UI. This issue affects the visibility of the authorization functionality within the UI, which is essential for testing and interacting with secured endpoints.
## Expected behaviour
The Authorization header field should continue to appear and function in Swagger UI after the upgrade to version 6.6.1 or latest version. 

## Actual behaviour
After updating to version 6.6.1, the Authorization header field is no longer visible in Swagger UI. This absence prevents users from easily interacting with endpoints that require authentication, impacting usability and testing efficiency.

## Steps to Reproduce

1. Install Swashbuckle.AspNetCore 6.5.0: Confirm that Swagger UI displays the Authorization header field.
2. Upgrade to Swashbuckle.AspNetCore 6.6.1: Update the NuGet package.
3. Rebuild and Run: Open Swagger UI and observe that the Authorization header field is absent.

## Additional Notes
[SampleOAuth.zip](https://github.com/user-attachments/files/16597558/SampleOAuth.zip)

**Comment by martincostello** [comment]
This was an intentional change to resolve #2767.

As per [the OpenAPI 3.0 specification](https://swagger.io/docs/specification/describing-parameters/#header-parameters), the `Authorization` header should not be described in the parameters:

> Header parameters named `Accept`, `Content-Type` and `Authorization` are not allowed.

Instead you should define a security scheme:

1. [OpenAPI Guide: Authentication and Authorization](https://swagger.io/docs/specification/authentication/)
2. [Swashbuckle.AspNetCore: Add Security Definitions and Requirements](https://github.com/domaindrivendev/Swashbuckle.AspNetCore?tab=readme-ov-file#add-security-definitions-and-requirements)

**Comment by martincostello** [comment]
> Is there a best practice to either hide this endpoint or add comments/documentation to clarify its purpose?

That's up to you based on your use case. If your users don't need to use/see it, then you can exclude it with the `[ApiExplorerSettings(IgnoreApi = true)]` attribute.

**Comment by PAVITHRA2999** [comment]
Thanks a lot!
