### ISSUE TITLE
[Bug]: Wrong exception thrown by MemberInfoExtensions.IsDictionaryValueNonNullable

### ISSUE THREAD

**Issue by mywyb2** [domaindrivendev/Swashbuckle.AspNetCore#3070]
### Describe the bug

Starting from version 6.7.2, `MemberInfoExtensions.IsDictionaryValueNonNullable` contains a bug that throws an exception when the declaring type of a class property that is assignable to `Dictionary{TKey,TValue}` has a number of generic type arguments that is not 2. This is easily possible when the declaring type extends `Dictionary{TKey,TValue}`, e.g.

`public class MyDictionary: Dictionary<string, string>`

Instead of picking the generic type arguments of the declaring type, you need to look at the type arguments of the `IDictionary`-interface of the declaring type.

### Expected behavior

That no exception is thrown, just like in versions <= 6.7.1.

### Actual behavior

An exception is thrown on initialization, causing Swagger to fail to load API definition.

### Swashbuckle.AspNetCore version

6.7.2

### .NET Version

8

**Comment by martincostello** [comment]
For anyone who'd like to pick this up, the affected line of code is here:

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/09a12829c60d2c124e96c21e14472b1bc5dcab17/src/Swashbuckle.AspNetCore.SwaggerGen/SchemaGenerator/MemberInfoExtensions.cs#L108-L111

Instead, we need to recurse down through the type hierarchy until we get to the dictionary class, and then extract the type arguments from there. Otherwise there's no guarantee the first two type parameters will be the key and value, for example:

```csharp
public class MyObtuseDictionary<TWhatever, TValue, TKey> : Dictionary<TKey, TValue>;
```

In this case, the key is generic argument `[2]`, and the value is `[1]`.

**Comment by mywyb2** [comment]
The code that wrongly throws the exception is actually the block starting line 88.

**Comment by martincostello** [comment]
Thanks for clarifying.

Both pieces of code are wrong with respect to your scenario (deriving from a dictionary with more than 2 type parameters), it just depends on which TFM your app uses as to which variant is executed. One throws, the other returns the wrong result.

**Comment by s-kip** [comment]
I have the same problem with my custom dictionary implementation:

````
public class MyDictionary<T> : Dictionary<string, T>
````

Is there any kind of workaround or fix planned?
