### ISSUE TITLE
[Bug]: Issue with @default Tag in Latest Nestia Version and Swagger Generation

### ISSUE THREAD

**Issue by ohjiwan-oj** [domaindrivendev/Swashbuckle.AspNetCore#3106]
### Describe the bug

In previous versions, the `@default tag was successfully converted to the default value in Swagger. However, it seems that in the latest version, this conversion is no longer working.

```
export interface ICreateUserRequestDto {
  /**
   * User's email address
   * 
   * @pattern [a-zA-Z0-9@.]+$
   * @maxLength 320
   * @default user@example.com
   * 
   */
  email: string;

  /**
   * Social network service type
   * 
   * @default KAKA
   */
  snsType: SnsType;

  /**
   * Social network service ID
   *
   * @default 1234567890
   */
  snsId: string;
}

```

After writing the code as above and generating the swagger.json file using the nestia swagger command, the default fields are no longer appearing in the latest version.

```
"ICreateUserRequestDto": {
    "type": "object",
    "properties": {
      "email": {
        "type": "string",
        "maxLength": 320,
        "pattern": "[a-zA-Z0-9@.]+$",
        "default": "user@example.com",
        "description": "User's email address"
      },
```

I spent over five hours trying to find the cause in the code. When I reverted to the previous working version, 5.3.0, the default fields like "default": "user@example.com" were correctly generated.

Has the `@default tag functionality been removed in the new version, or is this a bug?

### Expected behavior

I expected the `@default tag to be converted in the Swagger documentation, with the expected default values included for each field

```
"ICreateUserRequestDto": {
    "type": "object",
    "properties": {
      "email": {
        "type": "string",
        "maxLength": 320,
        "pattern": "[a-zA-Z0-9@.]+$",
        "description": "User's email address"
      },
      "snsType": {
        "type": "string",
        "enum": [
          "APPLE",
          "GOOGLE",
          "KAKAO"
        ],
        "description": "Social network service type"
      },
      "snsId": {
        "type": "string",
        "description": "Social network service ID"
      }
    },
    "nullable": false,
    "required": [
      "email",
      "snsType",
      "snsId"
    ],
    "description": "User creation request DTO"
  }

```

### Actual behavior

The `@default tag is not being converted in the Swagger documentation, and the default values are not included for any of the fields.

**Comment by martincostello** [comment]
This hasn't been explicitly removed, and to be honest I didn't know it existed. I've also never heard of nestia.

> previous working version, 5.3.0

That's a _really_ old version (over 4 years ago), and is also a major release away, so changes made before I joined the project as a maintainer in May this year (e.g. version 6.0.0 released in 2021) could have intentionally changed something that stopped it working.

We've also updated swagger-ui by two major versions since then (see [here](https://github.com/domaindrivendev/Swashbuckle.AspNetCore?tab=readme-ov-file#compatibility)).

As it stands, this looks like either old functionality that's been removed, or it's entirely external to Swashbuckle.AspNetCore.
