### ISSUE TITLE
Swagger UI hangs when a file is returned as the response

### ISSUE THREAD

**Issue by jayalakshmis** [domaindrivendev/Swashbuckle.AspNetCore#352]
Version of swagger used

    "Swashbuckle.AspNetCore": "1.0.0-rc1",
    "Swashbuckle.AspNetCore.SwaggerGen": "1.0.0-rc1",
    "Swashbuckle.AspNetCore.SwaggerUi": "1.0.0-rc1"

Endpoint looks like 
  
        [HttpGet]
        public async Task<IActionResult> Get(string type, string id)
        {
            // other logic
            return File(ImageBytes, "image/gif");
        } 

**Issue**
The swagger ui simply hangs .  

The issue was not encountered when using the following version
     
     "Swashbuckle": "6.0.0-beta901",
     "Swashbuckle.SwaggerGen": "6.0.0-beta901",
     "Swashbuckle.SwaggerUi": "6.0.0-beta901",

**Comment by RehanSaeed** [comment]
I'm getting this too. 

Also, out of interest what Produces attributes would you set to give Swashbuckle the right hints as to the output of the controller action? I'm trying:

```
[Produces("image/jpeg")]
[ProducesResponseType(StatusCodes.Status200OK)]
[ProducesResponseType(typeof(void), StatusCodes.Status404NotFound)]
```

**Comment by RehanSaeed** [comment]
Looks like dodgey JavaScript code loading the binary file. [Here](https://stackoverflow.com/questions/27120757/failed-to-execute-createobjecturl-on-url) is a potential solution.

![untitled](https://cloud.githubusercontent.com/assets/2270364/24508757/5ef01f5a-155c-11e7-92d9-c1d26ee3740b.png)

**Comment by RehanSaeed** [comment]
I think I've worked it out. https://github.com/swagger-api/swagger-ui/issues/2530 suggests this is because Swagger UI thinks it's getting JSON. We are not setting the correct thing in the produces array in the swagger JSON.

As it turns out the [Produces("image/jpeg")] attribute is not working in Swashbuckle. https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/292 fixes this issue but nobody has looked at it yet.

**Comment by jayalakshmis** [comment]
@RehanSaeed Thanks a ton for your update. Yes you are right, it does not work for the [Produces("image/jpeg")] attribute. And to answer your question, I did not decorate my endpoint with any specifics of related to Produces attribute

**Comment by boban984** [comment]
Any progress on this issue?

**Comment by domaindrivendev** [comment]
@jayalakshmis - there's been a lot of changes since this issue, including a major upgrade to the UI. If you have the time, can you let me know if this issue persists with the latest version?

**Comment by Drag13** [comment]
Swashbuckle.AspNetCore 3.0.0.
Microsoft.AspNetCore.App 2.1.1
Microsoft.NETCore.App 2.1.0

Method signature: 
`public async Task<FileResult> GetFile([FromBody] Data data)`

Still hanging UI.

**Comment by domaindrivendev** [comment]
Closing as it's a very old issue and so much has changed. If you're still experiencing this issue with the latest version of SB (`v5.2.1` at time of writing), then please create a new issue. I would also ask that you create a minimal project that repro's the issue and post it up to github so that I can pull it down and repro for myself. Thanks
