### ISSUE TITLE
logout - system does not redirect to logout page

### ISSUE THREAD

**Issue by tungphuong** [domaindrivendev/Swashbuckle.AspNetCore#436]
Hello, I am using asp.net Core, Identity server 4 and swagger. Everything is fine, but I am facing with one issue when logout. Could you please let me know how can we configure to redirect to my login page when client logout? 

Currently, it seems built-in logout of SwaggerUi, not work. Token still be sent to server after logout.

Thanks

**Comment by domaindrivendev** [comment]
If this is still an issue - please post an exact set of repro steps (with the latest version - v2.5.0). If you want me to take the time to investigate, please put the time into a detailed description - thanks

**Comment by cleftheris** [comment]
It seems that this is still an issue using swashbackle aspnetcore 3.0

The issue seems to be that the swagger-ui "sigle page app" only clears the browser stored access_token without redirecting to the IdentityServer to do a proper logout and get rid of the cookie (). 
As a result when the user tries to re-login he immediately makes a roundtrip to the IdentityServer login page where he is still logged in and back. No way to logout and switch user. 

The logout experience should take the user to the identity server logout page to do a proper cleanup before getting back to the swagger ui SPA and clean the stored token.

**Comment by domaindrivendev** [comment]
Issues/feature requests related to the UI should be posted to the [swagger-ui project](https://github.com/swagger-api/swagger-ui) instead of Swashbuckle.

With that said, I believe the behavior you're describing is correct if not a little unintuitive. In the context of the swagger-ui - "Login/Logout" simply means "provide/don't provide the auth token with API requests". Whether or not you're logged-in at the "Identity Server" is a completely separate concern that the swagger-ui has no control over. Even if it wanted to clear _that_ cookie as well, it wouldn't be able to in most cases because the identity server could be on a different domain.

**Comment by cleftheris** [comment]
Thanks for your quick response!

There is a spec for javascript clients to do proper signout (front channel signout) in a similar manner they trigger signin. It is under the openid connect specification and can be found here https://openid.net/specs/openid-connect-frontchannel-1_0.html

The identity server documentation also states a standard way to do this for openid connect identity providers http://docs.identityserver.io/en/latest/topics/signout.html 

Does this make sense? Also using the well known configuration endpoint `/.well-known/openid-configuration` one could check to see if the feature is supported 
```json
{ 
    "frontchannel_logout_supported": true,
}
```

**Comment by cleftheris** [comment]
@domaindrivendev This is now crystal clear for me! 

I will wait for the swagger-ui team to make the improvements. 

Thanks for your time.

**Comment by takato1314** [comment]
There was a workaround suggested [here](https://github.com/swagger-api/swagger-ui/issues/6443#issuecomment-773789294) that requires users to provide a custom `index.html` page which will add a handler for redirect the user to the logout page. Is this possible to be somehow implemented here?
