### ISSUE TITLE
Pair of ApiKeys

### ISSUE THREAD

**Issue by pherbel** [domaindrivendev/Swashbuckle.AspNetCore#452]
I would like to use header value pair to authenticate the client and the documentation say it could be possible.
https://swagger.io/docs/specification/authentication/api-keys/

It seems to me I can't achive this with the .Net Api. Maybe I'm wrong and I miss something.

**Comment by domaindrivendev** [comment]
Swashbuckle.AspNetCore 5.0.0 (currently available as a beta package) supports the Swagger/OpenAPI spec 3.0, which in turn supports pairs of ApiKeys.

Here's some example code for defining and requiring this with Swashbuckle.AspNetCore 5.0.0-beta. This example specifies that both keys must be submitted together to authenticate (i.e. logical AND).

```csharp
services.AddSwaggerGen(c =>
{
    …

    c.AddSecurityDefinition("apiKey", new OpenApiSecurityScheme { Type = SecuritySchemeType.ApiKey, In = ParameterLocation.Header, Name = "X-API-KEY" });
    c.AddSecurityDefinition("appId", new OpenApiSecurityScheme { Type = SecuritySchemeType.ApiKey, In = ParameterLocation.Header, Name = "X-APP-ID" });

    c.AddSecurityRequirement(new OpenApiSecurityRequirement
    {
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "apiKey" }
            },
            new string[] {}
        },
        {
            new OpenApiSecurityScheme
            {
                Reference = new OpenApiReference { Type = ReferenceType.SecurityScheme, Id = "appId" }
            },
            new string[] {}
        }
    });
});

**Comment by codingarmadillo** [comment]
I tried this code using Swashbuckle.AspNetCore 5.4.1, but it gives me two independent keys (i.e. logical OR) in the API (screenshot attached). 

![swagger_auth](https://user-images.githubusercontent.com/407343/83438424-571f9480-a439-11ea-9d41-cf6865f42028.png)

**Comment by ais** [comment]
The keys are still listed separately on `Swashbuckle.AspNetCore-5.6.3` using the code above.

**Comment by domaindrivendev** [comment]
On further reflection, this issue/question is UI specific and therefore should be submitted to the [swagger-ui](https://github.com/swagger-api/swagger-ui) instead of Swashbuckle. Furthermore, it's more of a UX issue than an actual bug. In it's current implementation, the UI simply lists the available schemes, and leaves it up to the user to combine them as needed. For example, in your screenshot above, you can enter the key values and click the "Authorize" button for one _or both_ schemes. If you do both, then both keys will be added to the request with the "Try it out" functionality.
