### ISSUE TITLE
Upgrade to .netstandard 2.0, asp.net core 2.0  

### ISSUE THREAD

**Issue by ghd258** [domaindrivendev/Swashbuckle.AspNetCore#464]
Upgrade to .netstandard 2.0, asp.net core 2.0

**Comment by tillig** [comment]
Is there a reason to do this? By raising the minimum it would become incompatible with earlier versions, forcing all consumers to update all projects to also target netstandard 2.0.

**Comment by domaindrivendev** [comment]
Agreed. For apps it's great to keep your dependencies up-to-date. But for libraries where you want to minimize the barrier for use, I would always advocate lower min versions. SB shouldn't dictate the version of asp.net core in people's applications.

**Comment by JanEggers** [comment]
@domaindrivendev  it would be good if there is a 2.0 compliant version. right now i get a 500 when opening swagger ui because the static file nuget  referenced by swashbuckle still has version 1.0 and is not compatible with 2.0. (missing constructor) i was able to workaround it by explicitly adding staticfiles nuget in version 2.0 to my project. i would prefere a version of swashbuckle that has version 2.x and targets asp.net core 2.0 that way you could still provide bugfixes for 1.1.x but new features are on 2.x

**Comment by JustinJohnWilliams** [comment]
Any news on this? I see it was re-opened. I'm also having to revert to static files to upgrade to .netcore 2.0

**Comment by tillig** [comment]
@JustinJohnWilliams It's not reopened. There is an open pull request somewhat associated with the issue that has not been committed to or accepted. The current official solution to ASP.NET Core 2.0 support is to add your reference to Microsoft.AspNetCore.StaticFiles 2.0.0 and call it a day.

**Comment by JustinJohnWilliams** [comment]
@tillig Thanks! I didn't see the project: https://github.com/domaindrivendev/Swashbuckle.AspNetCore at first. this appears to take care of everything during my upgrade. Awesome job to all of you. Fantastic work!
