### ISSUE TITLE
Swagger UI page does not show when using Swashbuckle.AspNetCore for .net core web api stateless service in Azure Service Fabric

### ISSUE THREAD

**Issue by rudeGit** [domaindrivendev/Swashbuckle.AspNetCore#483]
OS: Windows 10 (Version 1703; OS Build 16281.1000)
Visual Studio Version: 15.3.3 (VS 2017)
Swashbuckle.AspNetCore Nuget Version: 1.0.0
Service Fabric Version: 5.7.198.9494
Service Fabric Version SDK: 2.7.198.9494

1) Create a service fabric application and choose 'Stateless ASP.NET Core' service template
2) Select  'Web API' ASP.NET Code 2.0.
3) This creates a service fab app project along with 'Web1' web api project.
4) Notice that Web1 project's target environment is set to .net framework 4.7 (_even though we selected asp.net core 2.0_).
5) Run the app and a browser is launched with 'localhost:port/api/values' and the response (["value1", "value2"]) is shown. Good so far.
6) Next add a nuget package Swashbuckle.AspNetCore Nuget Version: 1.0.0
7) In ConfigureServices method of Startup.cs file, change the code to: 
```
            services.AddMvc();
            services.AddSwaggerGen(options =>
            {
                options.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
            });
```
8) In Configure method of Startup.cs file, change the code to:
```
            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }

            app.UseMvc();
            app.UseSwagger();
            app.UseSwaggerUI(options =>
            {
                options.SwaggerEndpoint("/swagger/v1/swagger.json", "My API");
            });
```

9) Run the code. The endpoint (localhost:port/api/values) works as expected.
10) The endpoint (http://localhost:port/swagger/v1/swagger.json) works as expected.
11) The endpoint (http://localhost:port/swagger) causes 500 internal server error.
12) The endpoint (http://localhost:port/swagger/ui) causes 404 resource not found error.

**Comment by rudeGit** [comment]
I found that I needed to install nuget package **Microsoft.AspNetCore.StaticFiles 2.0.0** (which will replace **1.0.0**). Once I did that, the swagger page came up.

**Comment by ddimitrov90** [comment]
i just had the same issue, installing static files 2.0.0 fixed the problem
thanks @rudeGit

**Comment by collinbarrett** [comment]
I am having a similar issue, though not with Service Fabric. When I publish locally to a folder or to my Ubuntu prod. server, none of the Swagger UI static files are landing in a wwwroot folder like I'd expect. I tried adding the StaticFiles nuget package as suggested, with still no luck. Any other ideas on this? My source: https://github.com/collinbarrett/FilterLists/tree/master/src/FilterLists.Api

**Comment by Himansh-Tiwari** [comment]
Strange, I do have Swashbuckle.AspNetCore installed but Swagger UI was not working.
Installing "Swashbuckle.AspNetCore.SwaggerUI" separately fixed the issue.

**Comment by iparimal** [comment]
I've fixed this using NSwag.
I’ve removed “Swashbuckle.AspNetCore” and using “NSwag.AspNetCore” now. It works without any issue.

**Comment by bhosalemahesh899** [comment]
I had the same problem, Delete vs folder and it is working again. I am sure this is the perfect solution.

**Comment by CyAScott** [comment]
I tracked down the real issue to the **Microsoft.AspNetCore.StaticFiles** nuget [here](https://github.com/aspnet/AspNetCore/blob/master/src/Middleware/StaticFiles/src/StaticFileContext.cs#L333). When sending static files it only sends a partial response for part of file. Below is the http response headers from the sever:

```
HEAD /swagger/swagger-ui-bundle.js

HTTP/1.1 200 OK
Content-Length: 939878
Content-Range: bytes 19796-939877/939878
Content-Type: application/javascript
Last-Modified: Wed, 07 Nov 2018 15:25:06 GMT
Accept-Ranges: bytes
ETag: "1d476ae0fa32266"
Server: Kestrel
Date: Wed, 12 Dec 2018 13:49:11 GMT

{262,544 bytes of the JS file}
```
This is an invalid http response so the browser assumes the TCP connection was dropped mid way through the response. However, since the request was partially downloaded, additional requests to fetch the file will continue to download the remaining parts of the file. At some point all of the file will be downloaded and cached. At that point additional requests to fetch the file will get a 304 response and nothing will actually be downloaded.

What the server should do it set the content-length header to match the actual length of the body instead of the length of the file. This will signal to the browser it will need to make additional http requests to fetch the remaining parts of the file.

**Comment by cfrv99** [comment]
Check your all of action http method.
