### ISSUE TITLE
When using response XML docs, 200 always generated

### ISSUE THREAD

**Issue by DavidPx** [domaindrivendev/Swashbuckle.AspNetCore#561]
I'm using 1.0.0 of Swashbuckle.AspNetCore.

Our API methods return one of 202, 400, or 409.  Never 200.   The return type of the methods is `IActionResult`.  

When I used the `<response/>` elements to describe the three codes the swagger output has **four** codes, 200, 202, 400, and 409.  When I only use `SwaggerResponseAttribute` the swagger output correctly only has 202, 400, and 409.

**Comment by domaindrivendev** [comment]
This is by design. The `<response>` tag has two purposes:

1. To add a textual description for the happy path response code - 200 by default unless otherwise specified via `ProducesResponseType`
2. To add more response codes in addition to the happy path one

Because there might be cases where an operation conditionally returns different 2xx response codes, the `<response>` tags don't automatically replace one 2xx status code with another. Instead, you need to explicitly indicate that the happy path code is 202 instead of 200 via the `ProducesResponseType` attribute:

```csharp
/// <response code="202">Accepted for processing</response>
/// <response code="400">Validation error</response>
[HttpPost]
[ProducesResponseType(202)]
public IActionResult Create(Payment payment)
{
    ...
}
```
