### ISSUE TITLE
Nullable Boolean Decorated with RequiredAttribute Is Created as Boolean

### ISSUE THREAD

**Issue by elmo61** [domaindrivendev/Swashbuckle.AspNetCore#592]
I have the following code 

```
[Required]
public Nullable<bool> PropertyName { get; set; }
```
The problem with this is that "Required" is then put into the swagger document, and so `PropertyName` is then generated as a non nullable property. But this is not correct. 

I expect that this field can be set as "null" because The its a question to the user that they must answer "Yes" or "No" to, If they don't answer the question, Then the use of `[Required]` will cause validation back from the API.

But because its getting generated as a boolean not a Nullable<bool> (or bool?) then it can never be null and defaults to as if they have answered the question.

I believe that the swagger document should only have properties listed as required if they are of non nullable types. and shouldn't be using the Required parameter.

This is what swagger json document I have currently
```
Subscription:{  
   required:[  
      "propertyName"
   ],
   type:"object",
   properties:{  
      id:{  
         format:"int32",
         type:"integer"
      },
      propertyName:{  
         type:"boolean"
      },
      
   }
},

```

**Comment by domaindrivendev** [comment]
A few things to note ...

Firstly, [Swagger 2.0](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#data-types) does not support nullable data types. Therefore, SB cannot generate a type of nullable or bool?

Secondly, I disagree with your logic that suggests the property in your example above should NOT be described as required. If a null value is passed, then the request is going to fail due to server-side validation, and the client will have to resend with a non-null value to have the request successfully processed. In the context of API documentation, that is exactly the purpose of the `required` field. To tell the client what MUST be provided for the request to be successfully processed.

Finally, there is still a lot of confusion around how SB infers if a field is `required` for a request or not. It's been very difficult to get this to a point that everyone is agreed on. Furthermore, ASP.NET Core now includes additional attributes at the binding layer (`BindRequired`, `BindNever`) that also need to be taken into account. To gain some alignment and optimize for the most common cases, I've rolled all issues related to required vs not required into #599 so I can capture discussion and feedback in one place before deciding on next steps wrt implementation.
