### ISSUE TITLE
Generate Swagger file from dnx console app

### ISSUE THREAD

**Issue by dgee2** [domaindrivendev/Swashbuckle.AspNetCore#62]
Hi,

Is it possible to generate a swagger file from a dnx console app? I'm looking into the possibility of adding a second command to our asp.net app to generate the file so that we can then generate a client for the api as part of our build process.

Thanks

**Comment by Igmat** [comment]
As far as I understand, current structure doesn't allow this feature be easily implemented, but it could make this project much more useful, because now in order to generate clients from swagger we have to manually copy file after run or use cmd scripts. And both those options are dirty hacks.

Is it possible? If yes, is it planned?

P.S.
@domaindrivendev thanks for great tool:)

**Comment by domaindrivendev** [comment]
Yes - this feature is definitely planned, hopefully in the next beta release (no due date :( but working on it)

**Comment by domaindrivendev** [comment]
As dnx is redundant, I'm going to close this one and track the feature to build from CLI in #541
