### ISSUE TITLE
Easy way to control the logo title and link

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle.AspNetCore#622]
We just upgraded to the latest version and was using InjectOnCompleteJavaScript to control the logo and logo link but I'm not even seeing a clear cut way or any examples on how to do this easily.  Would it be possible to build this very common scenario into swashbuckle?

https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v2.0.0#apply-swagger-ui-parameters

**Comment by domaindrivendev** [comment]
As mentioned in the contributing guidelines and issue template, this is really a question for the Swagger-ui project and should be posted to that repo instead of SB.

Off the top of my head, the new version ships with a new system for customizing components. SB supports this by allowing a custom version of index.html to be used. This is described in the SB readme.

**Comment by domaindrivendev** [comment]
Granted though, it is a very common use case. So, if we can figure out the right v3 way to do it, we can add an example to the docs

**Comment by domaindrivendev** [comment]
@niemyjski - so, I figured out how to use the swagger-ui plugin system to customize the Topbar, added to the CustomUIIndex sample app, and updated the docs.

Here's the commit da753de95cc11260b11ea86655ec9d85a6cc3187

**Comment by niemyjski** [comment]
Awesome!!! Thank you

**Comment by niemyjski** [comment]
I tried to bring in your example as an embedded resource but the only thing that gets rendered is the h1 div for the top bar. I'll try and pull this repo and take a look if I get some time, if you have any ideas let me know. I didn't see any errors in the console.
