### ISSUE TITLE
Produces attribute not appearing in swagger output

### ISSUE THREAD

**Issue by chrizy** [domaindrivendev/Swashbuckle.AspNetCore#63]
using 6.0.0-rc1-final

When a Produces attribute is added ether to the class or method,
 [Produces("application/json")]

the swagger.json "produces" element is always empty, 

"produces":[]

Thanks.

**Comment by chrizy** [comment]
Confusing but Produces need to be the return data type,

**Comment by senj** [comment]
I can set the return data type, but then my own return type won't get listed.
If I set [Produces("application/vnd.my.v1+json")] it doesn't work.

**Comment by alexidsa** [comment]
I'm working on fixing it in this PR: https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/292

**Comment by RehanSaeed** [comment]
Can this issue please be reopened, it was never addressed.

**Comment by domaindrivendev** [comment]
Looks to be working in the latest version of SB for ASP.NET Core - Swashbuckle.AspNetCore.1.1.0 ...

**Code**
```csharp
[Route("/products")]
[Produces("application/json", "application/vnd.my.v1+json")]
public class ProductsController
{
    ...
}
```

**Generated Swagger**
```json
produces: [
  "application/json",
  "application/vnd.my.v1+json",
]
```

**Comment by ljfraney** [comment]
I upgraded to 1.1.0 and I have an action that returns an image, but I'm still getting the empty `"produces": []` array.
```
[Route("api/v1/[controller]")]
public class ProductController : Controller
{
    [HttpGet("Picture/{productId:int}", Name = "Picture")]
    [Produces("image/jpeg")]
    public async Task<IActionResult> Picture(int productId)
    {
        var picture = await GetPicture(productId);
        return File(picture, "image/jpeg");
    }
}
```
I get the following JavaScript error in swagger-ui.min.js: 

> Uncaught TypeError: Failed to execute 'createObjectURL' on 'URL': No function was found that matched the signature provided.

**Comment by clawrenceks** [comment]
@domaindrivendev Something is definitely not quite right here. I can never get the produces attribute to populate the produces section. 

More importantly however, having written my own IOperationFilter to do the population of the produces array for me, I can now see entries in produces in the swagger.json, but my swagger UI never shows me the "Response Content Type" dropdown box.

What is controlling the appearance of this dropdown box? Is there any specific information I can provide to help with debugging? I am using asp.net core 2.0.5 and swashbuckle.aspnetcore 1.1.0

**Comment by clawrenceks** [comment]
@domaindrivendev @ljfraney I managed to get a bit further with my scenario. In summary:

If my action has a correctly configured [ProducesResponseType()] attribute, I will see the Response Content Type in Swagger UI. If the action does note have this attribute, I never see the Response Content Type drop down, even when the produces array has values in swagger.json

**Comment by ljfraney** [comment]
@clawrenceks I've written a fix for this, and I'm finishing up my unit test. But at the moment I'm hesitant to submit a PR when I have two sources (including @domaindrivendev above) who have shown me that it is working for them. The problem appears to be in line 148 of [SwaggerGenerator.cs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SwaggerGenerator.cs). The produces property is being populated with the result of the SupportedResponseMediaTypes() method of Microsoft.AspNetCore.Mvc.ApiExplorer.ApiDescription. When the [Produces(string)] attribute is used with ActionResult/IActionResult, ApiExplorer is evaluating it in SupportedResponseMediaTypes(). Since I have evidence that it is working for some and not others, I thought it might be a difference between .Net Core versions. But, I've tried with 1.0, 1.1, and 2.0 with the same result. I want to do a little more research before I submit the code I've written. And then, it will be up to @domaindrivendev to say whether this is a problem with ApiExplorer that SwashBuckle should or should't try to work around.

**Comment by clawrenceks** [comment]
@ljfraney Great to hear that you have a fix, in my case using Produces with an IAction result certainly rings true.

A couple of question however, as I mentioned above, as soon as I started using ProducesResponseType and addition to Produces on the IAction Result, I got the results I expected. Would this be the case with the issue that you have seen?

Also - How about the SwaggerUI not showing the Response Content Type when I created my own IOperationFilter that did populate produces in the swagger.json - as per the example above, the operations added using my own IOperationFilter were also not shown until I also added the ProducesResponseType attribute to my IActionResult

I thought the information above might be useful in further validating your fix, or perhaps they identify a separate issue.

If I can be of help with testing, just let me know.

**Comment by ljfraney** [comment]
@clawrenceks If you are using an overload for ProducesResponseType() that takes a Type parameter, it will work. In my testing, using ProducesResponseType(200) had no effect.

I'm new to Swashbuckle/Swagger, and I'm not that familiar with IOperationFilter yet.

**Comment by clawrenceks** [comment]
@ljfraney I can confirm that what you have described above is what I see - ProducesReponseType with only a status code did not make the response content type dropdown appear in Swagger UI - it only appeared when I included a Type.

**Comment by ljfraney** [comment]
@clawrenceks I added my proposed solution in PR #583 .

**Comment by dataspun** [comment]
I believe this may be related to my swagger-ui issue [#4205](https://github.com/swagger-api/swagger-ui/issues/4205)

**Comment by ljfraney** [comment]
@dataspun If you have time, pull down the code from PR #583  (https://github.com/ljfraney/Swashbuckle.AspNetCore, `produces-attribute` branch) and see if it fixes your issue. I'd be interested. Still waiting for feedback from @domaindrivendev.

**Comment by ljfraney** [comment]
@dataspun If you are returning `application/json`, you should be able to get Swashbuckle to properly populate Swagger's `produces: []` array by using the [ProducesResponseTypeAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.producesresponsetypeattribute?view=aspnetcore-2.0) attribute instead of the [ProducesAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.producesattribute?view=aspnetcore-2.0). The difference is that you must provide a C# type when you use ProducesResponseType, which you would typically have when you are returning JSON. The code in PR #583 might make your code work as you expected, but I would still suggest using ProducesResponseType instead. The issue that I am trying to solve with PR #583 is that there is no way to properly populate the produces array when you are returning a content type that isn't represented by a class, and therefor can't be represented with JSON or XML (i.e. image/png, text/csv, etc.).

**Comment by dataspun** [comment]
@ljfraney Yes indeed using [ProducesResponseTypeAttribute](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.producesresponsetypeattribute?view=aspnetcore-2.0) works as you suggested, thank you.

To be thorough, the error `server can't produce application/json` is generated in the browser console even in the following cases:

- Using `[Produces("application/json")]` on controller or method
- Using `[ProducesResponseType(200)]` on controller or method, where the Type parameter isn't passed 

The only way to avoid the error is:

- Using `[ProducesResponseType(typeof(Object), 200)]` on controller or method

I'm not certain whether this is by design or not.  Either way, it appears specific to Swashbuckle.AspNetCore so I will close my swagger-ui issue [#4205](https://github.com/swagger-api/swagger-ui/issues/4205) and reference this one instead.

**Comment by dataspun** [comment]
@ljfraney Have you experimented with [FileResult](https://msdn.microsoft.com/en-us/library/system.web.mvc.fileresult(v=vs.118).aspx) for your ResponseType class?  There are several subtypes that may be of use to you.

**Comment by ljfraney** [comment]
@dataspun I assume you mean this [FileResult](https://docs.microsoft.com/en-us/dotnet/api/microsoft.aspnetcore.mvc.fileresult?view=aspnetcore-2.0) (.Net Core version). I can return an instance of FileContentResult or FileStreamResult, and I can provide a contentType in the constructor, but it doesn't affect the generated Swagger `produces` array.

**Comment by dataspun** [comment]
My bad yes the .Net Core version.

Apart from your PR and depending on your requirements, you could also return a JSON result with Base64 encoded string and mime type.

**Comment by rliberoff** [comment]
Hi, 

I have the very same project. Working with ASP.NET Core and Swashbuckle.AspNetCore 1.2.0, the following code does not generate the appropriate "produces", and the "Response Content Type" always shows "application/json" instead of the configured values.

Example of the code:

```
[HttpPost]
[Produces(@"application/pdf")]
[ProducesResponseType(typeof(FileResult), 200)]
[ProducesResponseType(typeof(void), 400)]
[ProducesResponseType(typeof(void), 401)]
[Route(@"api/[controller]/Report")]
public async Task<IActionResult> GenerateReport([FromBody]Request request)
{
	Stream stream = await GenerateReportAsync(request).ConfigureAwait(false);
	return this.File(stream, @"application/pdf", @"report.pdf");
}
```

Thank you.

**Comment by kmjungersen** [comment]
@rliberoff I know this is a super old thread, but thanks for your response.  I had a similar issue and was able to get past it using this portion of your comment:

```csharp
[Produces(@"application/pdf")]
[ProducesResponseType(typeof(FileResult), 200)]
public async Task<IActionResult> GenerateReport()
{
    // ...
}
```
