### ISSUE TITLE
Multiple Routes per Action function

### ISSUE THREAD

**Issue by VikingExplorer** [domaindrivendev/Swashbuckle.AspNetCore#640]
I've got multiple routes per method.  The UI is showing each route separately, which swagger-ui is saying is not their issue. (https://github.com/swagger-api/swagger-ui/issues/4297)

Is there a way to control that?

Also, is there a way to control what description get's associated with each Route?

swagger": "2.0"

If you're going to iterate through multiple routes, there should be some way to control which document they go into.

Context
For example:

```
    [Route("User")]
    [Route("ユーザー")]
    [ApiExplorerSettings(GroupName = "User")]
```
Obviously, the multiple routes on the same action have exactly the same behavior. So, what is the point of SwashBuckle iterating through them, creating a different entry for each one?

Perhaps the iteration of routes should be listed inside an entry for an Action, with the name of the action being the first Route?

As you can see, we're using routes to localize the API. In this case, there would be some value to being able to create Japanese API documentation.

Perhaps, there should be a way to associate Routes with a certain document? For example:

`    [ApiExplorerSettings(RouteGroup = "User:User.EN", RouteGroup="ユーザー:User.JA")]`

**Comment by domaindrivendev** [comment]
It's worth noting that SB has a couple of external dependencies that constrain what can and can't be done by this library alone.

Most notably, it generates JSON descriptions of APIs based on the [Swagger 2.0 Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md), and it uses that JSON to power compatible UI tools - such as [swagger-ui](https://github.com/swagger-api/swagger-ui) and [ReDoc](https://github.com/Rebilly/ReDoc).

So, the restructuring you've described above isn't possible because it's not supported by the spec or it's ecosystem. If you have an issue with this, you should take it up in those projects.

__HOWEVER...__ it is possible to split the descriptions into multiple Swagger documents, one for each locale, using the `DocInclusionPredicate` option described toward the end of [this section](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#generate-multiple-swagger-documents) in the readme.

This allows you to decide if a description should be included in a given document by inspecting some of the available metadata. In your case, you could use the `Order` property on routes to indicate which document it should be included in. I got this working locally. Here's the relevant snippets:

```csharp

// ValuesController.cs
[Route("api/values", Order = 1)] // 1 corresponds to English version
[Route("api/valeurs", Order = 2)] // 2 corresponds to French version etc. 
public class ValuesController : Controller
{
    [HttpGet]
    public IEnumerable<string> Get()
    {
        ...
    }

    [HttpGet("{id}")]
    public string Get(int id)
    {
        ...
    }
}

// Startup.ConfigureServices
services.AddSwaggerGen(c =>
{
    // Define a document for each language - note the {version}-{Order} convention for docName
    c.SwaggerDoc("v1-1", new Info { Title = "My App", Version = "v1" });
    c.SwaggerDoc("v1-2", new Info { Title = "Mon Application", Version = "v1" });

    // Update the selection process for a given docName (as specified above)
    c.DocInclusionPredicate((docName, apiDescription) =>
    {
        var routeInfo = apiDescription.ActionDescriptor.AttributeRouteInfo;
        return docName.EndsWith($"-{routeInfo.Order}"); // include the doc if route has corresponding Order
    });
});

// Startup.Configure
app.UseSwaggerUI(c =>
{
    // Include both documents in the UI drop-down
    c.SwaggerEndpoint("v1-1/swagger.json", "V1 Docs");
    c.SwaggerEndpoint("v1-2/swagger.json", "V1 Docs (French)");
});
```

Works well! But, the challenge is going to be ensuring people annotate routes correctly in your controllers. Anyway, I'm going to close as it's a working solution and SB can't do much else given the constraints I mentioned above

**Comment by VikingExplorer** [comment]
Sir, that is the most awesome answer I've heard in a long while.  Very, very cool.  Looking for a tip bucket...

**Comment by domaindrivendev** [comment]
A tip bucket ... now there’s an idea :) Glad we could leverage the built-in extensibility to meet your needs

**Comment by VikingExplorer** [comment]
One more question. It appears this would work for the route values. However, a bit stuck on xml doc text.  On build, this text is assembled into an xml doc.  I thought I could make a copy of this document & translate. Then specify which xml doc goes with which "group"?

```
services.AddSwaggerGen(c =>
{
        c.SwaggerDoc("API-1", new Info { Title = "SouthRiver REST API - English", Version = "v2018" });
                
        c.IncludeXmlComments(Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "SrtWebCore.xml"));
});
services.AddSwaggerGen(c =>
{
         c.SwaggerDoc("API-2", new Info { Title = "SouthRiver REST API - French", Version = "v2018" });
                
         c.IncludeXmlComments(Path.Combine(PlatformServices.Default.Application.ApplicationBasePath, "SrtWebCore.FR.xml"));
});
```

However, it didn't seem to work.  Thoughts?

**Comment by VikingExplorer** [comment]
@domaindrivendev what are your thoughts on my question?
