### ISSUE TITLE
OAuthAdditionalQueryStringParams not working

### ISSUE THREAD

**Issue by Advitalitum** [domaindrivendev/Swashbuckle.AspNetCore#665]
I have this options:
```csharp
c.AddSecurityDefinition("Bearer", new OAuth2Scheme()
{
	AuthorizationUrl = "/auth/token",
	TokenUrl = "/auth/token",
	Flow = "password",
	Description = "DESC",
	Type = "oauth2"
});

c.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
{
    { "Bearer", new string[] { } }
});
```
```csharp
app.UseSwaggerUI(c =>
{
    c.OAuthAdditionalQueryStringParams(new {foo = "bar"});
});
```
When i try to auth additional query string params not sending:

![image](https://user-images.githubusercontent.com/30781212/37819862-03012f6a-2e90-11e8-9052-dd6bbb6c23dd.png)

Although the parameters existing in js code:

![image](https://user-images.githubusercontent.com/30781212/37819914-213bcf30-2e90-11e8-919a-af3722122378.png)

**Comment by hung-doan** [comment]
I got the same problem

````C#
services.AddSwaggerGen(options =>
{
	...
	
	// Support Token-based authentication in swagger ui
	options.AddSecurityDefinition("Bearer", new ApiKeyScheme
	{
		Description = "JWT Authorization header using the Bearer scheme. Example: \"Authorization: Bearer {token}\"",
		Name = "Authorization",
		In = "header",
		Type = "apiKey"
	});

	options.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>> {
		{ "Bearer", new string[] { } }
	});
});
````

But there is no `Authorization` header in my http requests

**Comment by domaindrivendev** [comment]
This looks to be an issue with the swagger-ui and therefore, as per the [contributing guidelines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/CONTRIBUTING.md#feature-requests) should be posted to that repo instead of this one.

I took a quick look and can see that it's possibly an issue with the following line. The additional parameters appear to be added to the wrong variable:

https://github.com/swagger-api/swagger-ui/blob/50153487ba2f3546cd07617c362033a3341ef7c1/src/core/plugins/auth/actions.js#L148

Please open the issue there and reference this one
