### ISSUE TITLE
Does the generator supports also example generation?

### ISSUE THREAD

**Issue by risogolo** [domaindrivendev/Swashbuckle.AspNetCore#685]
I have properties "annotated" as `/// <example>something</example>` and xml with description is generated, instead of string "something" there is generated "string", and when there is a number like "1", it produces some default number, not sure weather this is expected behavior. I'd like to be able to put my own example which will get generated

**Comment by domaindrivendev** [comment]
This is just a general question and therefore, as per the [contributing guidelines](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/CONTRIBUTING.md), should be posted to stackoverflow instead of this issue tracker. There's a ton of information out there on providing examples. Here's a resource I'd recommend looking at:

https://mattfrear.com/2015/04/21/generating-swagger-example-responses-with-swashbuckle/
