### ISSUE TITLE
SwashBuckle 2.40 breaks functionality for Required attribute

### ISSUE THREAD

**Issue by kodaren** [domaindrivendev/Swashbuckle.AspNetCore#690]
Using NuGet package for SwashBuckle 2.40.
Using AutoRest latest (2.0.4262) for generating a rest client for csharp.

Properties in .net core 2.0 class has been decorated with the Require attribute. For instance a property with "int" type. When generating with swagger file from latest SwashBuckle 2.40 this attribute is ignored and thus a nullable property is generated.  The expected behavior is to preserve the "int" as non-nullable in the client. This works fine in version 2.30.

Best regards,

Jimmy

**Comment by domaindrivendev** [comment]
It's unfortunate that this has broken existing consumers as part of a minor version increment, and there's a valid argument that it _should_ have been a major increment, but the new behavior is by design. See #599 for the full discussion.

In summary, Swashbuckle bases it's description off the "actual" behavior it can infer from code. So, for setting the `required` attribute on parameters, it honors the behavior of ASP.NET Core's built-in request validation (i.e. `ModelState.IsValid`). You'll notice that the `RequiredAttribute` has no effect on this built-in validation when the property has a non-null default value. So, to get the desired validation behavior, you need to make value types (i.e. int) nullable, and once you do that, Swashbuckle will follow suit by indicating that the corresponding parameter is in fact required in the request.

**Comment by kodaren** [comment]
Yes, and Microsoft AutoRest is a very small consumer :-;

Validations are looking fine. However the behaviour now in v2.40 with the Required attribute is opposite before for the constructors and properties:
* That is if I create a property as "int?" (int<nullable>) then the generated csharp client property is not a nullable property! The Validator() function is also empty in this case.
* If the property is "int" then the generated property will have a nullable constructor and properties. The Validator() function looks correct in this case.

Is this really the expected behaviour? 
Could this be an AutoRest issue now that they need to address?
