### ISSUE TITLE
Swashbuckle.AspNetCore.SwaggerUI referencing Microsoft.AspNetCore.StaticFiles 1.0.4

### ISSUE THREAD

**Issue by brazilianldsjaguar** [domaindrivendev/Swashbuckle.AspNetCore#708]
After running into the same problem as https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/489 and https://github.com/domaindrivendev/Swashbuckle.AspNetCore/issues/438, I did a bit more research. Turns out,

`Swashbuckle.AspNetCore.SwaggerUI` nuget package references `Microsoft.AspNetCore.StaticFiles`, as it should, but it references `v1.0.4`. This is why the manual-add of `2.0.2` (or whatever is recent) is necessary.

I also noticed that the package does not target `netstandard v2.0`, but rather `1.6` - this may be the reason the `StaticFiles` nuget package hasn't been/couldn't be updated.

**Comment by domaindrivendev** [comment]
The targeting of `netstandard1.6` _as a lower bound_ is a purposeful design choice because there's still many consumers who haven't upgraded to `2.0` yet. If I increase that lower bound, then I'm shutting those folks out. It's fully compatible with 2.0 and above bar the transient dependency issue you're referring to, which can be easily worked around by explicitly adding it.

With all that said, I do plan on upping the lower bound soon - just not yet. But, that doesn't mean this won't happen again. For example, if I up the lower bound to 2.0 then the release of 3.0 could introduce a similar problem. As a downstream library, I always want to strive for the lowest bound possible so that more people can leverage Swashbuckle without being forced to upgrade their versions of the Core framework.

**Comment by remcoros** [comment]
@domaindrivendev One solution to this is release a 3.0 Swashbuckle and up the lower bound. while still maintaining the 2.0 packages with the lower bound. probably needs some custom build/package scripting for that.

**Comment by slawomirbrys** [comment]
@domaindrivendev I just reached the same issue as @brazilianldsjaguar and lost 2 days on unexpected behavior of my web API project, there is different behavior under Kestrel and IIS Express. I had ```Microsoft.AspNetCore.All``` package included into my project and everything worked fine until I removed it and added only those packages which needed. Project was still compiling and running, but after some time (clear VS cache) started to throw exceptions in runtime (the same mentioned in #489 and #438). 
I can see that PR #473 upgrading to ```netstandard2``` stuck on build, but it would be **very helpful** for those who upgraded to ASP.NET Core 2 to get it resolved and be fully compliant with that standard.
