### ISSUE TITLE
information-container is empty, when using CustomIndex

### ISSUE THREAD

**Issue by kostyrin** [domaindrivendev/Swashbuckle.AspNetCore#758]
I have made custom index page. But I have a problem with rendering Info(License, Contact and etc.)
After rendering I am getting the result:
`<div class="information-container wrapper"><section class="block col-12"><!-- react-empty: 33 --></section></div>`
information-container is empty
You can look My Startup here: https://github.com/VirtoCommerce/vc-platform-core/blob/feature/swagger/VirtoCommerce.Platform.Web/Startup.cs
and this https://github.com/VirtoCommerce/vc-platform-core/blob/599aa797053290c16fdfe6125a88822f423ad57f/VirtoCommerce.Platform.Web/Swagger/TagsFilter.cs#L23
can you help me fix it?

**Comment by domaindrivendev** [comment]
While the swagger-ui comes bundled with Swashbuckle for convenience, it's a [completely separate project](https://github.com/swagger-api/swagger-ui) that's maintained and supported independently. Once you're using a custom index for it, you're essentially working with the swagger-ui components directly and therefore I would suggest post this question to the swagger-ui forums or repo instead of Swashbuckle.
