### ISSUE TITLE
[Required] attribute is ignored

### ISSUE THREAD

**Issue by andreypesoshin** [domaindrivendev/Swashbuckle.AspNetCore#768]
Using the last version (2.5.0) of nuget package Swashbuckle.AspNetCore I can't get [Required] attribute start working.
Recently I had an interface showing that the field is required just like this one:
![image](https://user-images.githubusercontent.com/148180/41502796-0be018d4-71cb-11e8-919b-578d5c05e225.png)

But now it doesn't (and it also does not require this param to be filled when submitting a form from swagger UI):
![image](https://user-images.githubusercontent.com/148180/41502805-347d914a-71cb-11e8-9760-89ec15d4adea.png)

At the side of the code it looks like:
![image](https://user-images.githubusercontent.com/148180/41502816-7407a620-71cb-11e8-8543-6d0dc9068be9.png)

And when submitting a form, asp.net core model binding does it's work well and shows the message as expected:
![image](https://user-images.githubusercontent.com/148180/41502831-b01907c6-71cb-11e8-8426-85a9e12b5486.png)

I noticed this problem just after an upgrade to Swashbuckle.AspNetCore 2.5.0 (but i'm not sure whether it is a reason or not). What should I do to fix a problem?

**Comment by domaindrivendev** [comment]
The current implementation mirrors ASP.NET Core's built-in validation behavior (i.e. `ModelState.IsValid`), which will essentially ignore the attribute because the property is non-nullable and therefore will never fail validation - so by definition it's _NOT_ actually required. If you make the property a nullable int, it should work.

Although there is a reasonable rationale to this approach, it's a little non-intuitive and therefore I'll be updating Swashbuckle to honor all `RequiredAttribute`s, regardless of the built-in validation behavior. This will be generally available with the 3.0.0 release.

**Comment by andreypesoshin** [comment]
@domaindrivendev thanks for your answer.

Just for the history.
My task was to show to the client that this `MyParam` should be passed amongst with other parameters. So I guess it's incorrect to have it as nullable int to only see it marked as required* in the spec.
I understand that model binding will bind it with the default value, but it is the implementation thing, not the contract one.

I got the expected behavior by replacing `[Required]` with `[BindRequired]` attribute, so I assume this approach is the optimal one for the moment.

**Comment by freeranger** [comment]
@domaindrivendev do you have an ETA for 3.0.0?  Thanks

**Comment by deadmann** [comment]
i got this one working:
[JsonProperty(Required = Required.DisallowNull)]
but the issue is, it wont enter the action, so i have no control over it, and the messages it returns...
