### ISSUE TITLE
How can I tell what's a Swashbuckle issue and what's a Swagger UI issue?

### ISSUE THREAD

**Issue by AnthonyMastrean** [domaindrivendev/Swashbuckle.AspNetCore#772]
I find myself a little anxious about where to post issues! I'm not sure how to tell where to draw the line? For example, I just reported this issue to the swagger-ui project:

https://github.com/swagger-api/swagger-ui/issues/4662

**Comment by domaindrivendev** [comment]
First and foremost, Swashbuckle is a Swagger generator for ASP.NET Core. That is, it automatically generates a JSON document that describes your API according to the [Swagger 2.0 Specification](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md). In addition to this, it exposes that JSON as a HTTP endpoint AND it exposes an embedded version of the swagger-ui. The swagger-ui is a popular tool in the Swagger ecosystem. It takes a Swagger JSON endpoint, and generates a corresponding UI and playground.

Keeping that in mind, here's some guidelines to help you decide where issues should be posted

__1) If you can't get to the UI page at all OR you can get to it but it displays a message saying "Failed to load API definition"__
Then it's most likely a Swashbuckle issue. To dig deeper, you should navigate directly to the Swagger JSON endpoint (/swagger/v1/swagger.json unless you've configured otherwise). Here you should see a full stack trace of the error.

__2) If you can see the UI but there's something not right or a feature you think is missing__
This is most likely a swagger-ui issue. However, it _could_ be a result of invalid Swagger JSON being generated by Swashbuckle. To rule this out, navigate directly to the Swagger JSON endpoint and copy the contents to your clipboard. Then go to the [Online Swagger Editor](https://editor.swagger.io/), paste the JSON and ensure there's no validation errors.
