### ISSUE TITLE
IModelFilter Default Does not Respect JSON Serializer Settings

### ISSUE THREAD

**Issue by RehanSaeed** [domaindrivendev/Swashbuckle.AspNetCore#78]
I have created a model filter setting the default value like so:

```
public class EntityModelFilter : IModelFilter
{
    public void Apply(Schema model, ModelFilterContext context)
    {
        model.Default = new Entity()
        {
            Property = "Hello"
            OtherProperty = null
        };
    }
}
```

The default `JsonSerializerSettings` also have the NullValueHandling property set to `Include`:

```
services.AddJsonOptions(
    options =>
    {
        // This is the default anyway.
        options.SerializerSettings.NullValueHandling = NullValueHandling.Include;
        options.SerializerSettings.ContractResolver = new CamelCasePropertyNamesContractResolver();
    });
```

When looking at the example JSON in the Swagger UI, the `OtherProperty` value is not displayed. I suspect this is a UI problem.

**Comment by domaindrivendev** [comment]
To comply with the [Swagger specification](http://swagger.io/specification/), the outputted Swagger JSON has formatting requirements that are independent of your application. So, by design, it doesn't use the same SerializerSettings because doing so could result in invalid Swagger.

However, ideally, all "example" and "default" fields within the Swagger document would use the application settings. But, this is non-trivial as it requires some advanced customization of Json.Net to enable conditional settings based on the field names.

**Comment by gmsDave** [comment]
@domaindrivendev, can you elaborate on how including null values or displaying enums as strings would cause an invalid swagger doc, or perhaps describe the approach that needs to be taken to solve this issue?  I'll gladly help if I can.

**Comment by jkubecki** [comment]
Is this the same behavior referenced in issue [#794](https://github.com/domaindrivendev/Swashbuckle/issues/794) on the main Swashbuckle repo?

**Comment by Dresel** [comment]
Some thoughs on [SwaggerContractResolver.cs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/1b8e109cdb2e21b57584ef4596a0d1a13af8b7eb/src/Swashbuckle.AspNetCore.Swagger/Application/SwaggerContractResolver.cs):

1) What is the `_appJsonSerializer` for?

1) Is the `_camelCasePropertyNamesContractResolver` really needed? Maybe it's sufficient to set

        NamingStrategy = new CamelCaseNamingStrategy()
        {
            ProcessDictionaryKeys = false
        };

    or similiar on the `SwaggerContractResolver`?

1) If I understood correctly, for Swagger properties you need to have `NullValueHandling.Ignore`? The Newtonsoft suite allows setting the `NullValueHandling` on property contract level, so for my understanding it should be enough to add this in the `SwaggerContractResolver`:

	    protected override JsonProperty CreateProperty(MemberInfo member, MemberSerialization memberSerialization)
	    {
		    var property = base.CreateProperty(member, memberSerialization);

		    // Something like that?
		    if (member.DeclaringType.Namespace.StartsWith("Swashbuckle.AspNetCore.Swagger"))
		    {
			    property.NullValueHandling = NullValueHandling.Ignore;
		    }

		    return property;
	    }
    Then you would't need to set in on the serializer directly.

**Comment by domaindrivendev** [comment]
@Dresel - thanks for your input.

One other requirement for the Swagger serialization is that "example" and "default" metadata fields are serialized according to the application's serialization settings as opposed to the swagger-specific ones. This is because these fields are used to provide example input/output values for the actual API.

I've created the following PR - #307 to try meet these requirements. It appears to work as intended but it is a little complicated and I'm wondering if there's a simpler way. I'd be interested to get your feedback if you have a moment.

**Comment by Dresel** [comment]
That looks good. I think we also have to take "Examples" from the `Response` object into account?
