### ISSUE TITLE
Is it possible to use this for OData?

### ISSUE THREAD

**Issue by christianquirante** [domaindrivendev/Swashbuckle.AspNetCore#807]
Good Day Everyone,

I am using:
 .Net Core 2.1
OData
Swashbuckle.AspNetCore (3.0.0)

And I am trying to use swashbuckle for odata and when I add the value controller I get this error:

![1](https://user-images.githubusercontent.com/37047861/42536343-578b7006-84c4-11e8-9196-b8a92985fc05.JPG)

And if I remove the value controller, I would get this on swagger:

![2](https://user-images.githubusercontent.com/37047861/42536528-ea464fb0-84c4-11e8-88a5-e11327d70b74.JPG)

This are the codes from my Startup.cs

**ConfigureServices**
```
       public void ConfigureServices(IServiceCollection services)
        {
            services.AddLogging();
            services.AddOData();
       
            services.AddMvc()
                .SetCompatibilityVersion(CompatibilityVersion.Version_2_1);

            services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "OData API", Version = "v1" });
            });
        }
```

**Configure**
```
   public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {

            Data.Core.Repository.LoggerFactory = LoggerFactory;

            if (env.IsDevelopment())
            {
                app.UseDeveloperExceptionPage();
            }
            else
            {
                app.UseHsts();
            }

            app.UseHttpsRedirection();
            app.UseCors();
            app.UseODataBatching();
           
            app.UseMvc(r => {
                var builder = new ODataConventionModelBuilder()
                {                    
                    //Namespace = "OData",
                };
                var eb = builder.EntitySet<Employee1>(nameof(Employee1));
                eb = builder.EntitySet<Employee1>(nameof(Employee2));
                eb = builder.EntitySet<Employee1>(nameof(Employee3));
                var model = builder.GetEdmModel();
                r.Count().Filter().OrderBy().Expand().Select().MaxTop(null);
                r.MapODataServiceRoute("odata", null, model, new DefaultODataBatchHandler());

                r.EnableDependencyInjection();
            });

            app.UseSwagger();
            app.UseSwaggerUI(c =>
            {
                c.RoutePrefix = "swagger";
                c.SwaggerEndpoint("/swagger/v1/swagger.json", "OData API V1");
            });
            app.UseAuthentication();

            Mapper.Initialize(cfg => {
  
                cfg.AddProfiles(typeof(Startup));
            });
        }

```
What can I do to make this work? I will really appreciate everyone who will help me out on my problem

**Comment by ThomasSteschulat** [comment]
Same problem here...

**Comment by igor-moskvitin** [comment]
May be will be usefull: you can provide some sort of documentation controller (derived from ControllerBase) that can replay path as ODataController did, but should be after OData in pipeline - than swaggerGen can produce valid swagger.json, but when request will be handeled by OData controller as expected.

**Comment by NetTecture** [comment]
So 7 months later. Any updates on the status how to integrate odata with swashbuckle? It is the missing piece to actually allow third parties to use it. At least my UI people permanently nag me about this.

**Comment by freeranger** [comment]
Perhaps it’s worth you creating the smallest possible runnable project that recreates the issue.
The original posted did not provide a full project and for sure had superfluous code in there.
The less noise there is and the easier it is to recreate the issue, the more likely it is that someone would find the time to look at it

**Comment by Mhirji** [comment]
When using Swashbuckle, together with https://github.com/Microsoft/aspnet-api-versioning, things seem to work on dotnet core.  Maybe there is a temporary workaround you could implement in order to get things going.  I see that @commonsensesoftware has struggled a lot to work around some of the issues caused by the implementation of OData and their routing system, maybe you can leverage some of his work.

**Comment by commonsensesoftware** [comment]
The issue is that there is no API Explorer for OData - on Web API or ASP.NET Core. On both platforms, the default OData controller base class opts out of the API Explorer. It's possible to work around this, but it doesn't help because the default API Explorer implementations do not understand how to discover OData routes.

I see the crux of this issue being that OData simply does not have an API Explorer. That is independent of, and should be external to, Swashbuckle or any other Swagger generator. If the OData team or anyone else (like API Versioning) provided API Explorer extensions, the consumer libraries like Swashbuckle _just work_. The idea that a Swagger library such as Swashbuckle should provide this support is the wrong approach IMHO. There have been previous attempts to do this in the past. Swashbuckle already does everything required, regardless of whether you're using OData, as long as it's provided in the API Explorer.

If you don't need or want versioning, but you still want Swagger support, then the next best option might be to use the [ODataSwaggerConverter](https://github.com/OData/WebApi/blob/master/src/Microsoft.AspNet.OData.Shared/ODataSwaggerConverter.cs) provided by the OData team. It's not nearly as comprehensive as what a fully-fledged Swagger library like Swashbuckle provides, but it _might_ get you what you need. At a minimum, it might provide an initial implementation to work from. There are also libraries and other tools that transform the EDM (a la XML) to Swagger (in JSON). This may be a workable solution as well.

As long as you generate compliant Swagger documents in a manner addressable by the Swashbuckle Swagger UI, things _should_ work end-to-end.

I hope that helps.

**Comment by domaindrivendev** [comment]
Dup of #581
