### ISSUE TITLE
Default parameters are required.

### ISSUE THREAD

**Issue by niemyjski** [domaindrivendev/Swashbuckle.AspNetCore#824]
I have a route with different overloads like

```cs
[HttpGet(“submit”)]
[HttpGet(“submit/{type:minlength(1)}“)]
```

Swagger generates both of those as separate but on the submit end point type is required. This is a bug.

**Comment by domaindrivendev** [comment]
I don't understand your issue. Please provide more detail, JSON examples, screenshots etc.

**Comment by WilCameronP** [comment]
Seems I got the same problem. 
`[HttpGet("channelConfigs/{channelName?}")]
 public async Task<IActionResult> GetChannelConfigs([FromRoute]string channelName)`
The “channelName” parameter actually is optional but on the Swagger ui prompts it required.

**Comment by domaindrivendev** [comment]
Swashbuckle does not support optional “path” parameters because the Swagger 2.0 specification does not support optional “path” parameters:

https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md#parameterObject

To describe your endpoint with Swagger, you need two separate endpoints as opposed to one with an optional “path” parameter. The easiest way to do this is two have two action methods.

**Comment by niemyjski** [comment]
Yes, but swashbuckle can detect this and create two endpoints with one having the parameter and one that doesn't. The current issue is we generate one and it's required and we can't just click execute without having a validation error.

**Comment by domaindrivendev** [comment]
I'm not keen on that approach - what if there's 2 optional path parameters, 3, 4 … you would need to generate an action for each combination and that would lead to some ugly docs. Sorry, but for now this is going to remain on the "unsupported" pile.
