### ISSUE TITLE
Generate definition when using [FromQuery]

### ISSUE THREAD

**Issue by Necronux** [domaindrivendev/Swashbuckle.AspNetCore#830]
```csharp
public class MyModel
{
    public int Prop1 { get; set; }
    public int Prop2 { get; set; }
    public int UnwantedProperty { get; set; }
}

public IActionResult ListAsync([FromQuery] MyModel sieveModel)
{
    ...
}
```

When using `[FromQuery]` this piece of JSON is generated:

```
"parameters":[  
   {  
      "name":"Prop1",
      "in":"query",
      "required":false,
      "type":"integer",
      "format":"int32"
   },
   {  
      "name":"Prop2",
      "in":"query",
      "required":false,
      "type":"integer",
      "format":"int32"
   },
   {  
      "name":"UnwantedProperty",
      "in":"query",
      "required":false,
      "type":"integer",
      "format":"int32"
   }
]
```

Is there any way to make `MyModel` to appear in the "definitions".

**Comment by domaindrivendev** [comment]
If I'm understanding your question correctly - you're asking how to omit `UnwantedProperty` from the generated Swagger?

If you don't want it in the docs, then I'm assuming you don't want it to be bound to a query parameter full stop? If so, I would recommend being a little more stringent with your use of model binding so that you're only allowing data through the parameters you intend it to come from. For example, in your case you can explicitly tell AspNetCore to ignore certain parameters when it's binding requests to models. And, Swashbuckle will also reflect this change and rightly omit it from the docs:

```csharp
public class MyModel
{
    public int Prop1 { get; set; }
    public int Prop2 { get; set; }
    [BindNever]
    public int UnwantedProperty { get; set; }
}
```

**Comment by Necronux** [comment]
@domaindrivendev That's useful and probably will work, but it won't work when using some third-party models, you would need some way to configure it fluently.

**Comment by domaindrivendev** [comment]
If you don't have access to the model source code, you can explicitly remove parameters from any operation with an Operation Filter (see readme).
