### ISSUE TITLE
Make `SwaggerGeneratorSettings.SwaggerDocs` a case-insensitive dictionary

### ISSUE THREAD

**Issue by dougbu** [domaindrivendev/Swashbuckle.AspNetCore#835]
The `documentName` route parameter is passed directly to a method which attempts to retrieve the `Info` from the `SwaggerDocs` dictionary. Since the dictionary uses the default comparer, it is case-sensitive. In turn, the document's URI is now case-sensitive though many web platforms (including ASP.NET Core MVC) route identically without regard to case.

Basically, I'm suggesting `/swagger/v1/swagger.json` and `/swagger/V1/swagger.json` should both return the document named `v1` (or `V1`).

**Comment by dougbu** [comment]
Oddity found in Swashbuckle v3.0.

**Comment by domaindrivendev** [comment]
Dup of #397.

TL/DR; While many platforms might ignore case when routing, it's not correct behavior - the HTTP spec clearly indicates that URL paths _should_ be considered case-sensitive (https://stackoverflow.com/questions/15641694/are-uris-case-insensitive)

**Comment by domaindrivendev** [comment]
If you're suggesting that because case-sensitivity is discussed in the context of client handling, that it's acceptable for servers to use different semantics, I disagree. For efficient communication, including mechanisms like caching and idempotent retries, all parties must agree on how to distinguish one resource from another. As an example, if a client used case-sensitive comparisons and the server used case-insensitive, then caching at the client would be 50% less efficient than it could be.

But, you're correct in saying that the current implementation does introduce some inconsistencies. I'm just not convinced which one should win over.

One thing we can agree on though, is that a failed match (case sensitive or case insensitive) should return a 404 instead of a 500. This used to be the case and it seems a regression must have been introduced at some point. I'll definitely fix this.

For the case sensitivity, we'll have to postpone the conversation and perhaps give others a chance to weigh in. Although I do like to indulge in a bit of bike shedding, I simply don't have the time right now :)

**Comment by domaindrivendev** [comment]
> One thing we can agree on though, is that a failed match (case sensitive or case insensitive) should return a 404 instead of a 500. This used to be the case and it seems a regression must have been introduced at some point. I'll definitely fix this.

See ea0e606a482d9b360864a267419f3316b7c362d9
