### ISSUE TITLE
Missing dependency when using .AddMvcCore() 

### ISSUE THREAD

**Issue by Xorcist77** [domaindrivendev/Swashbuckle.AspNetCore#851]
When using Swashbuckle.AspNetCore.Swagger with .AddMvCore(), instead of .AddMvc() a runtime error is thrown because Swashbuckle.AspNetCore is apparently dependent on Microsoft.AspNetCore.StaticFiles, but that dependency is not pulled through when adding the Swashbuckle.AspNetCore nuget package to a project.

System.MissingMethodException: Method not found: 'Void Microsoft.Net.Http.Headers.EntityTagHeaderValue..ctor(System.String)'.
   at Microsoft.AspNetCore.StaticFiles.StaticFileContext.LookupFileInfo()
   at Microsoft.AspNetCore.StaticFiles.StaticFileMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.StaticFiles.DefaultFilesMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIIndexMiddleware.<Invoke>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---

Adding Microsoft.AspNetCore.StaticFile to the project and restoring fixes the issue, but I feel like this should be implicit and not explicit.

**Comment by domaindrivendev** [comment]
This is a dup of #438.

It's worth noting that Swashbuckle _does_ include an implicit reference to `StaticFiles` which does get automatically added to your project. However, SB targets 1.0.4 as a lower bound (by design) and because `dotnet restore` doesn't ensure compatibility for transitive dependencies, it pulls in _that_ version despite being incompatible with the rest of your ASP.NET Core stack. IMO, this is a limitation to the way .NET Core resolves transitive dependencies that is going to continually cause problems for libraries that aim to be compatible with a wider range of ASP.NET Core versions. See the referenced thread for a full discussion.

So, the explicit reference workaround is to get the right version as opposed to anything else.

With all that said, for the next major version of SB, I've made the decision to upgrade the lower bound dependencies on ASP.NET Core to 2.0.0. So, this should help to some degree, at least for the time being.
