### ISSUE TITLE
ETA on next NuGet Release?

### ISSUE THREAD

**Issue by VictorioBerra** [domaindrivendev/Swashbuckle.AspNetCore#897]

**Comment by babrekel** [comment]
+1 Looking forward to the new changes.

**Comment by VictorioBerra** [comment]
https://github.com/micro-elements/MicroElements.Swashbuckle.FluentValidation/issues/15#issuecomment-425208894

**Comment by domaindrivendev** [comment]
Apologies for the delay here. I have several enhancements queued up in master that will break the public/config API and so would like to release them all together rather than having a series of major version releases in quick succession with breaking changes. As you can see from the [4.0.0 milestone](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/milestone/6), there's 1 feature that's holding things up. I'm trying to get that resolved ASAP. If I can't get that resolved soon, I may have to resort to separate releases, each with breaking changes :(

So, stay tuned and thanks for your patience.

**Comment by domaindrivendev** [comment]
In the meantime, you can always pull down the latest preview package, built from latest master, from myget.org:

https://www.myget.org/feed/domaindrivendev/package/nuget/Swashbuckle.AspNetCore

**Comment by NetTecture** [comment]
That does not really work for many of us. I.e. me - while this is possible on dev machines, swagger (currently in really breaking so no compabitiliby can be lost)... i simply am not allowed to pull build links from third party sources ;)

**Comment by VictorioBerra** [comment]
> i simply am not allowed to pull build links from third party sources

The public NuGet feed is basically third party sources. Can you fork, rename, and then publish the latest master to your own feed? Maybe MyGet?

**Comment by NetTecture** [comment]
As per https://www.extradom.pl/projekt-domu-rezydencja-floryda-WAH1858 there is a lot of changes in 3.0 asp.net anyway. I sugest you release.

@VictorioBerra Your words, nice. Mine too. Sadly that both does not matter, unless you are the CEO of a specific germany based 25k people company that pays my bills.
