### ISSUE TITLE
3.0.0 oauth2 application flow  in AddSecurityDefinition in ASP.Net core 2.0

### ISSUE THREAD

**Issue by arlan85** [domaindrivendev/Swashbuckle.AspNetCore#906]
Hi all, I'm facing with an issue after change my security definitions from implicit (works fine!) to application. When I specify client key and client secret on Available authorizations popup, this put me on the same popup an error : **auth errorTypeError: NetworkError when attempting to fetch resource.** . On chrome network tab it seems to be 200 the request but it is an OPTIONS request and when I make the same request via browser, Azure Ad tells me 

> Sorry, but we’re having trouble signing you in.
> AADSTS90056: This endpoint only accepts POST, OPTIONS requests. Received a GET request.

This are my security definitions:
 ```
options.AddSecurityDefinition("oauth2", new OAuth2Scheme
                {
                    Type = "oauth2",
                    Description = "OAuth2 App Authentication grant",
                    Flow = "application",
                    AuthorizationUrl = $"https://login.microsoftonline.com/{TenantId}/oauth2/v2.0/authorize",
                    Scopes = new Dictionary<string, string>
                        {
                          
                        }
                    ,
                    TokenUrl = $"https://login.microsoftonline.com/{TenantId}/oauth2/token"

                });

                options.AddSecurityRequirement(new Dictionary<string, IEnumerable<string>>
                    {
                        {"oauth2",new string[]{ }},
                    });
```

I add to this configs but with no luck in any case:
```
 app.UseSwagger().UseSwaggerUI(options =>
                   {
                       options.SwaggerEndpoint("/swagger/v1/swagger.json", "API V1");
                       options.OAuthRealm(_azureAdOptions.ClientId);
                       options.OAuthAppName("Swagger Client App");
                       options.OAuthScopeSeparator(" ");
                       options.OAuthAdditionalQueryStringParams(new { resource = $"{Audience}" });
                   });
```

What's happening with this options?
I'm using:

- ASP.Net Core 2.0
- Swashbuckle.AspNetCore 3.0.0
-  Azure Ad as Identity provider.

PS: Also happens with flow: password.

**Comment by erendrake** [comment]
swagger ui is a client-side app. this server-side grant type would have to send all of its information to the client for the ticket exchange and then you lose much of the benefits from the stricter grant type. 

also to use auth code you would need to send the secret to the client which is very insecure. 
https://github.com/swagger-api/swagger-ui/blob/master/docs/usage/oauth2.md

most oidc providers wont even let you use this grant type with client-side apps.

**Comment by erendrake** [comment]
I think the implicit flow is the correct one for using Swagger UI. 

It is less secure because all of the tokens are visible to the browser but at least everyone will know it ahead of time. If you use auth code and make the client secret available to the bowser that is even less secure because you are using a "server-side" flow on the client-side. If your team has decided they don't like the implicit grant type there will need to be a discussion on your team about how to manage this.

We have omitted the swagger ui client in our production system. In prod the swagger UI is a source of documentation not api experimentation for us. you could also limit the available scopes that the swagger UI client has to mitigate the risk. If you are setting up a public API you are using the Swagger UI as some kind of sandbox i still think implicit is appropriate for this use case 

that got kinda rambly. I hope that answered your question
