### ISSUE TITLE
Exception if enum base type is not int

### ISSUE THREAD

**Issue by mplesnik** [domaindrivendev/Swashbuckle.AspNetCore#954]
I have an enum defined as 
 public enum MyEnum:byte
{
        Val1 = 1,
        Val2 = 2
}
i get an error "Specified cast is not valid"

i drilled it down to this line
https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/b68bd9af27debe285c9827d887b1bc00a29018d9/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/SchemaRegistry.cs#L183

it assumes that every enum base type is int.

**Comment by nkalfov** [comment]
I have the question, was this possible in swashbuckle for .NET Framework? Because JSON (and JavaScript) does not have data type `byte`. The valid data types are `string`, `number`, `boolean`, `null`, `object`, and `array`. You may wish to [describe the enums as string](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#customize-schema-for-enum-types), but you would still need to have the enumeration to be of type `int`.

**Comment by yyjdelete** [comment]
+1 for this.
And is it possible to register an custom enums handler(Func<Type, OpenApiSchema> or etc) to convert all enums to OpenApiSchema with both description and value?(like something as $"{description}({value})"). Now it's possible to use `MapType<T>()` to map one of them one by one, but not one func to map all of them without known all types.

**Comment by domaindrivendev** [comment]
This issue was resolved as part of #1041 (See https://github.com/domaindrivendev/Swashbuckle.AspNetCore/pull/1041/files#diff-efe00ed63b102a704543003622d66c31R56 for the relevant area of code)

Will be available with the 5.0.0 release (previews available now on myget.org)
