### ISSUE TITLE
Add support for OpenAPI 3.0 oneof/anyof/allof/not

### ISSUE THREAD

**Issue by RKVitaly** [domaindrivendev/Swashbuckle.AspNetCore#955]
Specification:
https://swagger.io/docs/specification/data-models/oneof-anyof-allof-not/

Use case:
multiple response type for the same response code.

**Comment by SharpNoiZy** [comment]
Can you tell us something new to this issue here?
Any plans to implement this? For my customer that would be a huge help.

**Comment by cleftheris** [comment]
I think this is beond of the library as it seems to be a matter of implementation. Regarding oneof/anyof and polymorphism there are 2 concerns to tackle. One of them is related to api specification and the way that Swashbuckle generates the swagger definition. The other one though, is related to serializatrion and deserialization which is out of scope of this library.  

That said this is mainly up to the api implementation to deside and thankfully swashbuckle is extensible to work with almost any api scenario you can think. 

I have came up with a solution for polymorphism that consists of two Swashbuckle filters and a Json.Net `JsonConverter`
- [PolymorphicSchemaFilter](https://github.com/indice-co/Indice.AspNet/blob/master/src/Indice.AspNetCore/Swagger/PolymorphicSchemaFilter.cs) Takes care of adding the subclasses of a base class to the schema registry and takes care of inherited properies in the generated Open Api spec so that props are not duplicated. Also takes care of the TypeMapping and discriminator property.
- [PolymorphicOperationFilter](https://github.com/indice-co/Indice.AspNet/blob/master/src/Indice.AspNetCore/Swagger/PolymorphicOperationFilter.cs) Takes care of operation requests and responses so that they use the any of one of of the subclasses depending on the schenario (array, object)
- [PolymorphicJsonConverter](https://github.com/indice-co/Indice.AspNet/blob/master/src/Indice.Common/Serialization/PolymorphicJsonConverterBase.cs) Takes care of deserializing a base class `[FromBody]` using the discriminator propery into one of the available subclasses. Also takes care of serializing the subclass with the extra `discriminator` if needed so that on the other end a client can recreate the correct type.

Hope this helped.

**Comment by SharpNoiZy** [comment]
First of all, thank you for your Feedback.

I already used a custom filter solution from StackOverflow. (Will have a look at yours)
My Scenario is interface inheritance, I have IProduct and Hardware : IProduct, Car: IProduct.
Using NSwagStudio to generate Code from the swagger.json. 

I have an API returning an Array of IProduct. 

My issue with the custom solution is IProduct MUST have a property ProductType which is checked in an DocumentFilter as discriminator.

But how ugly is it to have a Hardware class with property ProductType with the value "Hardware" and have Car type with a property ProductType which the value "Car".

**Comment by cleftheris** [comment]
It is true the $type is very useful. But unfortunately JsonNet serializes the Clr type there which is not very friendly for other languages apart from csharp. My point here is that these scenarios are very difficult to generalize. I believe that the swagger part of the solution can be more standardized. The JsonConverter part is more opinionated and is far from a generic solution. The links I gave are an example that was tailored for my needs/style ([some tests for the serializer](https://github.com/indice-co/Indice.AspNet/blob/master/test/Indice.Common.Tests/PolymorphicJsonConverterTests.cs)).

**Comment by simonare** [comment]
> * pery into one of the available subcla

@cleftheris , 

Do you have working example for this? I tried to implement it however I have some missing points.

Thank you

**Comment by AndrewTakker** [comment]
> First of all, thank you for your Feedback.
> 
> I already used a custom filter solution from StackOverflow. (Will have a look at yours)
> My Scenario is interface inheritance, I have IProduct and Hardware : IProduct, Car: IProduct.
> Using NSwagStudio to generate Code from the swagger.json.
> 
> I have an API returning an Array of IProduct.
> 
> My issue with the custom solution is IProduct MUST have a property ProductType which is checked in an DocumentFilter as discriminator.
> 
> But how ugly is it to have a Hardware class with property ProductType with the value "Hardware" and have Car type with a property ProductType with the value "Car" and so on.
> 
> There is a Standard for it with the "$type" property:
> https://www.newtonsoft.com/json/help/html/SerializeTypeNameHandling.htm
> This property don't have to be on the model, it will be added on serialization (runtime).

You can try [https://github.com/manuc66/JsonSubTypes](url)

**Comment by cleftheris** [comment]
> @cleftheris ,
> 
> Do you have working example for this? I tried to implement it however I have some missing points.
> 
> Thank you

Hi unfortunately in the latest RC my code broke because it depends on `SchemaRepository.TryGetIdFor`. I am waiting to see what happens with an open pull request #1268

**Comment by domaindrivendev** [comment]
Support for oneOf, allOf and discriminator added by #1468
