### ISSUE TITLE
Example from <example> xml comment always has 'string' type

### ISSUE THREAD

**Issue by ar7z1** [domaindrivendev/Swashbuckle.AspNetCore#959]
For the model:
```csharp
public class Model
{
    /// <summary>
    ///     The maximum number of elements in a page.
    /// </summary>
    /// <example>10</example>
    [JsonProperty("size")]
    public int Size { get; set; }
}
```
Swashbuckle.AspNetCore produces the following example:
```json
{
  "size": "10"
}
```

As you can see, the type for the `"size"` property is a `string`, not `int`. The correct example should be:
```json
{
  "size": 10
}
```

This bug can be reproduced in the latest stable version 4.0.1.

**Comment by ar7z1** [comment]
@domaindrivendev I'll create a PR soon. ;-)

**Comment by MikeBeaton** [comment]
Since Swashbuckle is nicely written, it is possible to use this fix without waiting for a new release. 😊

I've put up [a gist](https://gist.github.com/MikeBeaton/ea9e47109f55fbaec0113756904b900e) containing the patched file (plus an `internal` extension method from the [Swashbuckle source](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/src/Swashbuckle.AspNetCore.SwaggerGen/Generator/JsonPropertyExtensions.cs) which it needs) and documented in #1021 how to apply the updated filter class in a live project without waiting for a new release.
