### ISSUE TITLE
Getting started documentation is wrong

### ISSUE THREAD

**Issue by TraGicCode** [domaindrivendev/Swashbuckle.AspNetCore#961]
**Summary**
The getting started section ( https://github.com/domaindrivendev/Swashbuckle.AspNetCore#getting-started ) of the readme is using the wrong class.

**What is wrong**
```
services.AddSwaggerGen(c =>
{
    c.SwaggerDoc("v1", new OpenApiInfo { Title = "My API", Version = "v1" });
});
```

**What is correct**
```
       services.AddSwaggerGen(c =>
            {
                c.SwaggerDoc("v1", new Info { Title = "My API", Version = "v1" });
            });
```

**Comment by domaindrivendev** [comment]
This isn’t a mistake. You’re looking at the master branch and therefore the corresponding docs for that branch. Technically you should be looking at the branch/tag for the version you’re using. Admittedly though this isn’t very clear. I’ll update the repo so that the default branch is the latest “stable” version as opposed to the “master” version

**Comment by domaindrivendev** [comment]
OK not sure that's going to work either. I'm in the process of moving official docs over to readthedocs.com and this will solve this issue and provide an overall improved documentation experience. In the meantime, you can look at the docs for the latest stable release here - https://github.com/domaindrivendev/Swashbuckle.AspNetCore/tree/v4.0.1

**Comment by TraGicCode** [comment]
Thanks, we can close this then
