### ISSUE TITLE
Description of Assign Explicit OperationIds in readme is not complete

### ISSUE THREAD

**Issue by nkalfov** [domaindrivendev/Swashbuckle.AspNetCore#964]
The [readme](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md) file has to be edited in section [Assign Explicit OperationIds](https://github.com/domaindrivendev/Swashbuckle.AspNetCore/blob/master/README.md#assign-explicit-operationids). 

I am using packages `Swashbuckle.AspNetCore 4.0.1` and `Swashbuckle.AspNetCore.Annotations 4.0.1`. I could not get any any operation Id into the swagger initially with both ways to do it (Option 1 or Option 2). I inspected SwaggerUIOptions and I found there is the method `DisplayOperationId()`. After invoking in, I was able to see the operation Ids in the generated swagger. 

My startup class looks like:
```cs
public class Startup
{
        //.... some other methods and properties
        public void Configure(IApplicationBuilder app, IHostingEnvironment env)
        {
            //.... some configuration on the IApplicationBuilder instance
            app.UseSwaggerUI(SetSwaggerUIOptions());
            //.... some configuration on the IApplicationBuilder instance
        }
        //.... some other methods and properties

        //.... some other methods and properties
        private Action<SwaggerUIOptions> SetSwaggerUIOptions()
        {
                var result = new Action<SwaggerUIOptions>(options =>
                {
                        options.SwaggerEndpoint($"/swagger/{ApiName}/swagger.json", $"{ApiTitle} {ApiVersion}");
                        options.DocumentTitle = $"{ApiTitle} {ApiVersion}";
                        options.DisplayRequestDuration();
                        options.DisplayOperationId();
                });
                return result;
        }
}
```

My controller looks like:
```cs
[Route("api/values")]
[Produces("application/json")]
[ApiController]
public class ValuesController : ControllerBase
{
        [HttpGet(Name = "get all values")]
        [ProducesResponseType(typeof(string[]), (int)HttpStatusCode.OK)]
        public IActionResult GetAll()
        {
                return Ok(new string[] { "value1", "value2" });
        }
}
```

**Comment by domaindrivendev** [comment]
The section you've referenced is referring specifically to the inclusion of `operationId` in the generated Swagger JSON, which I think it does reasonably well.

If I understand your comments correctly, you're wanting more details on the impact this field does or doesn't have on the `swagger-ui` - a completely separate component that's document [elsewhere in the docs](https://github.com/domaindrivendev/Swashbuckle.AspNetCore#apply-swagger-ui-parameters).

By design, the docs are broken down by component - i.e. there's a section related to the component that generates Swagger JSON, a section related to middleware that exposes that JSON, a section related to the swagger-ui etc. I'm not in a position to completely restructure the docs at this point and so I'm going to stick with this format for the moment.

With that said, there's a few situations where I do cross-reference between the SwaggerGen and SwaggerUI sections to add a little more color. See https://github.com/domaindrivendev/Swashbuckle.AspNetCore#add-security-definitions-and-requirements for an example. If you think something similar could work here, please put forwward a suggestion in the form of a PR.

**Comment by nkalfov** [comment]
@domaindrivendev, I would forward a PR with modification on the readme file :)

**Comment by nkalfov** [comment]
Added PR #967
